### ISSUE TITLE
pen colors not numbered correctly... sometimes

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1151]
130 is supposed to be blue.

![image](https://cloud.githubusercontent.com/assets/6549787/13367118/dda3cd62-dcad-11e5-88c8-86bd55c04863.png)

http://snap.berkeley.edu/snapsource/snap.html#present:Username=mfries&ProjectName=U6L2-MondrianBroken

**Comment by maryfries** [comment]
I think it's just that the scale has been split in half. Instead of 0 to 170, it goes from 0 to 85. This is much like #1150 where the shade scale is off by a factor of 2.

**Comment by jmoenig** [comment]
again, it's wrong to use Scratch's help screen. Snap has an hsv color model, where "color" resembles the hue on a scale of 0 to 100:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=Colors

**Comment by maryfries** [comment]
Actually, even 65 is giving me red right now.

http://snap.berkeley.edu/snapsource/snap.html#present:Username=mfries&ProjectName=U6L2-MondrianBroken2

Something is not right, and it's isn't only the help pages.

**Comment by jmoenig** [comment]
No, the "draw rectangle" custom block resets the color midway, so whichever color you set before gets reverted to red...

**Comment by maryfries** [comment]
I'm sorry. I'm so stuck with this and have been for hours now. Can you show me exactly where?

![image](https://cloud.githubusercontent.com/assets/6549787/13367808/4537a228-dcb3-11e5-9389-f68f64aea336.png)

**Comment by jmoenig** [comment]
Ha, I was wrong!
looking at the source code I noticed a loose end: When setting the pen shade, the hue always gets set to 1, hence the ubiquitous red:

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/objects.js#L2915

So, the - kludgy! - workaround until I fix this is to *first* set the shade, and only *then* the color, because setting the hue leaves the shade in place, but not vice-versa.

Sorry!

**Comment by jmoenig** [comment]
happy to report we've rethought and extended color for Snap5, so issues like this one should now be solved. Closing, thanks!
