### ISSUE TITLE
Blocks with sprites

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap#1152]
Hello,

I'm a french mathematics teacher .
Here is a summary of a project.
[http://nathalierun.net/depotLibre/milieuDyn0.html]
I don't understand why I am obliged to put a bloc “Forever” on sprites A and B to make my project turn correctly.

Moreover, the time reactivity is very slow…

I post this message here because I'm wondering whether it could be a bug ?

Another question. I am asking why it is not possible to choose names of sprites in a block entry when you choose an object entry.
The project is here
[http://nathalierun.net/depotLibre/Milieu.xml]

**Comment by jmoenig** [comment]
Hi! I'd love to help, from looking at your project and the summary I'm not quite sure whether I understand the issue. Can you explain a little more in detail what your project aims to accomplish? Thanks!

**Comment by nathalierun** [comment]
Woh ! Thank you…

What I'm trying to do is some dynamical geometric project. 
Sprite A is a point. Sprite B another point. 
Sprite named M is the midpoint of (A,B).

If you move A or B, M must follow.

Like here :
https://scratch.mit.edu/projects/96670059/

**Comment by nathalierun** [comment]
I would like to import new sprite wich is a file in svg to make a real vectoriel point so when you zoom the stage, it looks still like a point...

**Comment by jmoenig** [comment]
Aha, thanks for the explanation!
In Snap you can simply import an svg file, either via the "import" menu, or - easier yet - by dragging it with you mouse and dropping it into Snap (you can do the some for any image file, also for the coordinate system background of the Stage).

So, for the mid-point example, this can be done even easier in Snap than in Scratch, because we have a generic "When" hat block. Therefore I can do this with just a single script, which I put into the mid-point sprite's scripting area:

![midpoint](https://cloud.githubusercontent.com/assets/2596285/13392955/8711322c-dede-11e5-9a5d-a5db4ba13d01.png)

That's all the code you'll need, this should do exactly what the Scratch project does.

Note that I've also made the mid-point "undraggable", so the user cannot drag it with the mouse. Here's my quick implementation of this project:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=midpoint

Feel free to use this as a starter point, and please let me know if this doesn't work for you.
Thanks!

**Comment by nathalierun** [comment]
Ok. Thank you very much.
How did you do to import balls ?

And what about my second question with blocks 
_I am asking why it is not possible to choose names of sprites in a block entry when you choose an object entry._

**Comment by jmoenig** [comment]
Okay, so we can make the single script shorter yet because we don't even need the variables:

![mid2](https://cloud.githubusercontent.com/assets/2596285/13393450/e1b3311e-dee1-11e5-9e48-e2705628cdb3.png)

I saved the ball costumes to my computer (as svg files). Then I opened my finder (explorer on Windows) and simply dragged and dropped the file onto Snap (the browser tab with Snap open).

The OF block can be used to query other sprites' state. First you select the other sprite's name in the right drop-down, then you get a list of all available properties in the left drop-down of the OF block. This, btw. is exactly the same as in Scratch.

**Comment by nathalierun** [comment]
I had just removed local variables to see if it was working without them. Nice. Thank you.

I don't understand the second part, but I'll try to think about it to understand it.

**Comment by nathalierun** [comment]
I realize that you did not understand my question.

Please return to my project even if it is not correct. I was talking about the block called "milieu".
[http://nathalierun.net/depotLibre/Milieu.xml]
When you execute the block, you cannot choose a specific sprite to execute it. The entries stay empty. I tried everything to put a name of a sprite in one of the little empty turtles.

I don't know how to put an image here....

**Comment by jmoenig** [comment]
Ah! The OF block can take a *name* as an input. So, you just declare the block's inputs to be of type "text" rather than of type "object", and then you can use the formal parameters like variables inside the procedure declaration. Here's little GIF that shows how to do that:

![sprite_named_inputs](https://cloud.githubusercontent.com/assets/2596285/13394291/c66fc902-dee7-11e5-99ed-07adccca6f56.gif)

Does that help?

Also, here's another screen recording showing how you can import costumes in Snap:

![importingcostumes](https://cloud.githubusercontent.com/assets/2596285/13394315/ebe4e9e2-dee7-11e5-8945-2db5d324bfee.gif)

(You can simply drag & drop images into this Github forum to embed them)

**Comment by jmoenig** [comment]
The "object" input isn't really needed by Snap right now, as Snap does not yet support first-class sprites (only referencing sprites by their names, for which you can use a text-input). In future versions the object-type input will support first-class sprites. At the moment some users are taking object-type inputs for their own custom quasi objects (made out of lists or with closures). For example, if you make a "point" object or a "fraction" object using either a list or a closure, you might want to set an "object" input to such blocks, to make it clear that something complex goes here.

**Comment by nathalierun** [comment]
Thank you very much for taking time to make this little videos. Now, it is clear.

I understand that I cannot pass as argument an object sprite to a block. Is it going to be possible ?

I have a question on snap : is it a functional programming language ?
Because, when I read this page https://fr.wikipedia.org/wiki/Programmation_fonctionnelle, I understand that Snap is a functional programming language.
Does everything must be first class in a pure functional programming language ?

**Comment by nathalierun** [comment]
Is the sprite name "Alonzo" had be given in honour of Alonzo Church ?

**Comment by jmoenig** [comment]
I'm glad I could help!

referring to sprites directly (as opposed to by their name) will be possible in the next major release (4.1), although it's not yet clear when that will be ready. But it *will* definitely come!

Of course, Alonzo is a shout out to Alonzo Church, the inventor of the lambda calculus. That's also why the Alonzo mascot has a funny lambda-shaped haircut.

So, yes, Snap is a functional programming language, but not because "everything" is first class (that's just one of Brian's typical radical battle cries^^). It's functional, because *procedures* and *functions* are first class, and because (reified) functions remember their environment, i.e. they capture the local variables in the lexical scope they were created in, turning them into persistent non-local "closures". Support for higher-order functions (rings and custom C-shaped input slots in Snap) and for closures is what makes for a functional programming language. Snap also supports first-class continuations and proper tail recursion, which are also traits of a functional programming language (Scheme).

**Comment by nathalierun** [comment]
Thank's a lot for all these details ! 

I am very glad to learn that referring to sprites directly will be possible one day...

I notice your delicate attention towards Alonzo Church...

**Comment by nathalierun** [comment]
Hello,
Reading the Acknowledgements in the SnapManual, I wondered what was the MioSoft society (page 2). Is there any relationship with MicroSoft ?
It is told in the "About Snap!" that MioSoft has brought its support in the development of Snap! . How ?
Thanks by advance for your answer.

**Comment by brianharvey** [comment]
No relation to Microsoft.  They sell secure database back end support, Jens used to work for them, and they are volunteering to provide the back end storage for users' projects.

**Comment by nathalierun** [comment]
I am really glad to learn that MioSoft has nothing to do with Microsoft. Do you have a web site that present this company please ?
In fact, I have to present snap to colleagues who swear by completely free software, free in their license but also in the funds that have helped develop the project...

**Comment by nathalierun** [comment]
I have a technical question. I wanted to send an example of one of my project by imitating Jens syntax : http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=midpoint
So I want to show 
http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=CliquezMoi
but it doesn't work. I don't understand why because I do have a project named CliquezMoi in my nathalierun's cloud.

**Comment by brianharvey** [comment]
You have to share the project first.  (File menu, Open, then click on the project name and click the Share button.)

**Comment by nathalierun** [comment]
Nice, thank you !!!

**Comment by nathalierun** [comment]
Good morning,

I cannot reproduce this :
![capture du 2016-05-21 09 43 33](https://cloud.githubusercontent.com/assets/17542520/15446659/927db2f8-1f38-11e6-8f14-357eb8bad971.png)

My block is :
![testblock1](https://cloud.githubusercontent.com/assets/17542520/15446670/0395ec44-1f39-11e6-8de5-9313a10388d3.png)

And I get an error like that :
![capture du 2016-05-21 09 48 34](https://cloud.githubusercontent.com/assets/17542520/15446680/3a388d06-1f39-11e6-86b7-3cf460972b8a.png)

What's wrong with my script ?
Thanks.

**Comment by cycomachead** [comment]
You need a grey ring around `my attribute`. (Right click and select "ringify")

**Comment by nathalierun** [comment]
Oh, thank you !
It works.

**Comment by nathalierun** [comment]
Is it possible to change color of a basic sprite ? 
I would like to create clones with random colors in a block.

**Comment by cycomachead** [comment]
Yes, use the pen blocks to change the color.
ᐧ

--
Michael Ball | michaelball.co

**Comment by nathalierun** [comment]
Génial !!!

**Comment by nathalierun** [comment]
And now, I wonder whether I do have a bug or not :

When I execute this script :
![index](https://cloud.githubusercontent.com/assets/17542520/15447252/54588f06-1f4d-11e6-8077-2e1de7a174e9.png)
my sprite disappears but never comes back in the stage.

**Comment by brianharvey** [comment]
My guess is that you're misunderstanding what "rotation x" means.  You are setting the *rotation center* of the sprite, the point that will be (in your code) at (100,100) on the stage.  (More specifically you're setting the horizontal position of that point.)  Because your sprite isn't 200 pixels wide, you are setting the rotation center to be *outside* the sprite's costume.  So the sprite is at (100,100), but its costume is offstage somewhere.

I'm guessing from the POINT IN DIRECTION that what you really wanted to set was the sprite's direction.  If you change the MY block to say "my direction," then you won't need the POINT IN DIRECTION block; set attribute will do what you want.

**Comment by nathalierun** [comment]
Hello,
Thank you for your answer.
Ok, I really misunderstood what "rotation x" means.
But, I still do not understand why the command :
go to x:0 y:0 
don't make my sprite come back in the center of the stage. 

Another important thing is that I do not find in  MY block the item "my direction"  :
![capture du 2016-05-22 08 53 51](https://cloud.githubusercontent.com/assets/17542520/15452297/dac030be-1ffa-11e6-8423-5eef310e212c.png)

And it really miss (according to me).

**Comment by bromagosa** [comment]
(trying to unclutter gh issues a little bit)

Closing this as the forum is a much more appropriate space for Q&A :)
