### ISSUE TITLE
Input bugs, issues and questions.

### ISSUE THREAD

**Issue by AnastasiaDunbar** [jmoenig/Snap#1217]
### Input bugs:
- Increasing the number of inputs may make 3 inputs with one click.

![bug](https://cloud.githubusercontent.com/assets/11806048/15156048/92806dc8-16e5-11e6-8d53-6e6a4fd67d32.gif)
- Clicking out of the cursor may leave two cursors.

![bug](https://cloud.githubusercontent.com/assets/11806048/15156194/3c544a04-16e6-11e6-8dea-f4c6051a3b00.gif)
### Issues:
- ![block](https://cloud.githubusercontent.com/assets/11806048/15156657/5fdf936e-16e8-11e6-8816-2664c4e1e5f5.png) doesn't return a float but a integer.
- Sliders don't support floats.
### Questions:
- Will instruments in **Sound** be added?
- Will there be all effects from Scratch's in **Looks**?
- More Scratch look-alike theme? Like the stage on the left side and the background, buttons, costume editor and so on.
- [Pen transparency.](https://wiki.scratch.mit.edu/wiki/Pen#Transparent_Pen)
- Disable `*` as whitespace.
- Can Snap! be an offline app for Chromebook?

**Comment by brianharvey** [comment]
Oy.  Next time please submit separate issues instead of a big list!  This way it's harder for us to track which have been addressed.

I do think we should address all of these, except maybe the one about stage on the left.  I like the Scratch 1.4 look, personally.  But I can see that we might allow other skins; it's just low priority.

**Comment by jmoenig** [comment]
The first one is a feature: If you press and hold down the shift key while clicking on an arrow, the variadic input will expand / collapse by 3 items.

The second issue (multiple cursors) only happens - I think - if you experiment with the hidden and experimental "live coding" setting. Is that right?

Yep, random numbers only return floats if the bounaries are not integers. You can still make a random float of arbitrary precision by multiplying and dividing...

Musical instruments have been "in the making" for a long time, don't count on them being added anytime. soon. Same for graphic effects. I'm a little frustrated with the existing effects, if anybody is interested in working on them, this should be really easy and rewarding, but I've got other things on my list :-)

There is a "flat design" setting, that's about as bright as it gets. Personally I'm not convinced by the Scratch 2.0 layout with the stage on the left, so, that's a clear "no".

Pen transparency can be accomplished with JS blocks, I'm not interested in that at the moment.

Whitespace, and more important, *empty* inputs have special meanings in Snap, so that's going to stay.

**Comment by AnastasiaDunbar** [comment]
Didn't have experimental live coding setting on.
The random number integers are so annoying that I even made a block for it:
![block](https://cloud.githubusercontent.com/assets/11806048/15161405/63e63c90-16fe-11e6-87d2-6194ac135fef.png)
I mean, the old Scratch even behaved 1.0 as a float, not an integer.
Where's the `while()` block? I also made a block for it:
![block](https://cloud.githubusercontent.com/assets/11806048/15161586/0f7c9de2-16ff-11e6-92a7-30373a9c373c.png)
Can you disable anti-aliasing for blocks? It makes them blurry to read.

**Comment by liam4** [comment]
> Can you disable anti-aliasing for blocks? It makes them blurry to read.

I'd love this as an option.

> Where's the while() block? I also made a block for it:

That's the point :)

**Comment by brianharvey** [comment]
Backing up Liam, indeed the central reason for Snap<i>!</i> is that we don't have to provide everything anyone wants as a primitive.  Since we're in the business of teaching computer science, the more we leave as exercises the better.

However, the Iteration library does have all the different flavors of WHILE and UNTIL.

**Comment by cycomachead** [comment]
> Can you disable anti-aliasing for blocks? It makes them blurry to read.

What screen are you using? Disabling AA has had some issues in the past with the paint editor. (And really, that just makes things pixelated...)

There's a branch at snap.berkeley.edu/snapsource/dev/ that should have MUCH better support for high res screens.

**Comment by cycomachead** [comment]
> Yep, random numbers only return floats if the bounaries are not integers. You can still make a random float of arbitrary precision by multiplying and dividing...

Hmm, perhaps we should make an issue for this, but it does make sense to me that "1.0" should be treated as a float. However, I think '1.0' is treated as an integer everywhere else in Snap<em>!</em>? I don't know if that would break things or not...

**Comment by cycomachead** [comment]
Tagging

Sounds #1014 #95

**Comment by AnastasiaDunbar** [comment]
It wouldn't break projects, why would you put a decimal in the first place if you want it to be an integer.
Or do you mean it will break the behaviour?

**Comment by brianharvey** [comment]
1.0 *is* an integer!  It is the same number as 1.  Just because bad programming languages exalt the implementation details of computers to the status of mathematical truth doesn't make it right.

**Comment by AnastasiaDunbar** [comment]
Yes but I want to change the behaviour of `pick random`.

**Comment by cycomachead** [comment]
> 1.0 is an integer! It is the same number as 1. Just because bad programming languages exalt the implementation details of computers to the status of mathematical truth doesn't make it right.

You're right about that. 👍 

I do think that the use case of wanting a float back is fairly common. I was _going_ to argue that perhaps ranges of distance 1 should return a float in that range... However, since Snap<em>!</em>'s random function is inclusive (as is Scratch's), then a range [0, 1] is a _really_ simple way to get 50% probability.

Perhaps as part of the ever recurring idea of a math library we have:
![random](https://cloud.githubusercontent.com/assets/1505907/15169138/f59f48f0-16ec-11e6-8af8-02ac250aba28.png)

**Comment by brianharvey** [comment]
I think you mean 10^precision in the denominator, but yeah.

**Comment by cycomachead** [comment]
Oops, yes. I was getting distracted playing with the sharp-text version of Snap<em>!</em> :)

**Comment by jmoenig** [comment]
the original issues have since been resolved. I'm closing this now. Thanks!

**Comment by AnastasiaDunbar** [comment]
lol, I'm a bit sorry rereading my own comments from three years ago, saw this in my notifications.
