### ISSUE TITLE
Zeros Appearing in Input Slots when changing "and" to ","

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1438]
Note that zeros appear in the input slots after the change is applied.
![zeros-appearing](https://cloud.githubusercontent.com/assets/6549787/18971046/9e60705c-8661-11e6-936e-b02fbb7bbf7b.gif)

**Comment by jmoenig** [comment]
Yeah, so?
If you change the appearance and structure of the block, every existing instance must be adjusted. Snap tries hard - and does a pretty good job - to preserve the existing inputs, but there are limits.
BTW, Scratch "suffers" from the exact same problem, which isn't considered an issue there.

**Comment by maryfries** [comment]
I've never had an input appear after editing a block before.

**Comment by brianharvey** [comment]
I think this is just a particular instance of the general philosophical disagreement about the meaning of empty input slots. In Scratch an empty numeric slot is completely equivalent to one with a zero in it, so there's no reason to worry about whether or not to fill the slot.  Things are more complicated in Snap<i>!</i>.  Consider this case:
Before:  ![before](https://cloud.githubusercontent.com/assets/3885074/18973001/3d5820ae-8650-11e6-96f9-9e185a93598b.png)
After:  ![after](https://cloud.githubusercontent.com/assets/3885074/18973005/47d95e3a-8650-11e6-94aa-62c7bd9d2c7f.png)
Here the meaning has clearly changed.  But, again, I wouldn't want to solve this particular problem with a band-aid solution; I think we have to somehow resolve the underlying different points of view.

**Comment by liam4** [comment]
A workaround that I don't quite like:

![Workaround](https://cloud.githubusercontent.com/assets/9948030/18990194/b85a45d4-86e6-11e6-993a-c7a2ab133fe3.png)

Because `([])` is a separate block from `max of () lol ()`, `([])`'s value doesn't get changed when you change the labels of the `max` block.

I guess it works fine, but it doesn't seem to make much sense to actually drag a block in to force an input's value not to change like that..

**Comment by jmoenig** [comment]
Okay, this has since been fixed. Thank you! Closing...
