### ISSUE TITLE
codiflcation support 

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap#1541]
codiflcation support ，How to add code and call？
![452](https://cloud.githubusercontent.com/assets/20208703/20796811/ea93a628-b812-11e6-99c9-f0f8908ad198.png)

**Comment by BookOwl** [comment]
[Check out the codification example for details](http://snap.berkeley.edu/snapsource/snap.html#present:Username=bookowl&ProjectName=Codification%20Example)

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by aidiken** [comment]
@BookOwl
There are simple examples?

**Comment by BookOwl** [comment]
Just read the comments in the example

**Comment by zeroturn** [comment]
@aidiken, I realize your post is getting a little old, but here are a few comments.  I recently discovered "codification" and have been playing with it.  There are several "mapping" blocks (in the codification example referenced above by @BookOwl) that map the snap scripts to javascript, python, etc.  If you open the map block you will see the block editor.  In the block editor, certain "translations" of snap blocks have been entered.  Below is a screenshot of two block editors open.  The one on the left is the "map to python" block.  On the right is a new "map to ruby" block that I was playing with.  You can see that I modified some of the blocks to return ruby specific code rather than python code.

![codification-py-ruby](https://cloud.githubusercontent.com/assets/13770851/24629053/4adabaf6-187d-11e7-8cf1-eea17841e22b.jpeg)

The map to ... blocks work really well, but they will not know how to "translate" a custom block that you have made. (And "translations" for all of the standard blocks have not been included in those map to ... sample blocks.)  So, if the "translation" is missing, you will have to define that translation yourself.  At the bottom of that image, you can see that I created a custom block to calculate the area of a triangle using *Heron's Formula* (which calculates the area of a triangle given the length of the three sides).  As you can see, you need to define both a "header" and a "code" section.  I defined the ruby function in the *header* section, and then placed the call to that function in the *code* section.  Actually, you can use the `<body>` tag in the function definition and Snap will make an honorable attempt to translate the HeronsFormula script (because it already "has been told" how to handle all of the blocks that make up that script).  In this case, it is pretty close, but not quite right (as they say, "close" only counts in "horseshoes and hand grenades"  ;-) ).

When you click on my "map to ruby" block,

![map-to-ruby](https://cloud.githubusercontent.com/assets/13770851/24629404/802c37e2-187e-11e7-985a-55982cdab450.jpeg)

the ruby code is displayed in the code watcher:

![herons-formula-ruby](https://cloud.githubusercontent.com/assets/13770851/24629366/669d2c96-187e-11e7-9ce7-11267dba81e3.jpeg)

You would export your ruby (or whatever) code by right clicking on the watcher and selecting export.

By the way, the script that you save to the script variable *must be ringified*.  See the image below:

![set-script-toringified-herrons-formula](https://cloud.githubusercontent.com/assets/13770851/24630073/daeebf2c-1880-11e7-912e-80fee567bc62.jpeg)

I noticed that when I first inserted my custom block into the ring, the ring disappeared.  (This behavior is discussed in the reference manual if you have more interest in knowing why).  So, if your ring disappears, simply right click on your block and select *ringify*.

I hope you find these comments helpful.
