### ISSUE TITLE
is there a way to display fractions in Latex format?

### ISSUE THREAD

**Issue by AlainBusser** [jmoenig/Snap#1555]
Hi everybody,

I plan to write a Fractran interpretor where sprites read the fractions and try to multiply them with integers (see here: https://en.wikipedia.org/wiki/FRACTRAN the animated figure where the sprite is a red arrow, wearing an integer and sailing over the fractions). Sorry for you, Michael, I am still on imperative programming :-)

I want it to simulate some kind of parallel computing where several sprites, bearing each his own number, are sailing over the fractions. These sprites will then be small.

So, is there a way to display the fractions properly, with horizontal bars between the numerators and the denominators?

**Comment by Jonathan50** [comment]
You could use the LABEL block from the tools library to write the numerator and denominator and draw a line between them using the pen.

**Comment by jmoenig** [comment]
good idea, @Jonathan50 ! You could also use the "pen trails" library to then turn such a drawing into a costume for a sprite and have the sprite "wear" it. That way you could even move the fraction around onstage.

**Comment by cycomachead** [comment]
For most computers many of the fonts should have support for unicode characters so you can also write those with the label block.

See this list:
http://www.fileformat.info/info/unicode/category/Sm/list.htm

Otherwise, actually parsing LaTeX in Snap<em>!</em> does not sound like a good idea, though it would possible to use a JSFunction to install something like MathJax or Katex and render the output to a new costume. Possible, but it's likely a pain to get either library to put stuff in a Canvas element.

**Comment by AlainBusser** [comment]
great ideas, but where do I find these libraries? I think I missed something...

Another idea that I have is to split the fractions in two parts, the numerator being a sprite on the shore wearing an integer, and the denominator being another sprite facing it but under the water, and wearing another integer.

In this way, a Fractran program would be made of two lists of integers and one could still se the denominator **under** the numerator. But right now I lack some imagination for the drawing of these sprites (mermaids for the denominators?)

**Comment by ds604** [comment]
here's mathjax rendering latex, loaded through the JSFunction block:

<img width="1124" alt="screen shot 2016-12-12 at 1 46 10 pm" src="https://cloud.githubusercontent.com/assets/122734/21111992/e8df28c2-c071-11e6-88cb-c55949f35154.png">

it's just a div sitting on top of the canvas here. since mathjax doesn't render to canvas, i was trying to follow this (http://jsbin.com/hahubu/edit?html,output) to put the output on the canvas, but was having some trouble with html2canvas.js when i tried to do that

**Comment by brianharvey** [comment]
That's cool!  Could you share the project?  Thanks.

**Comment by BookOwl** [comment]
[MDN has a guide to rendering DOM elements to a Canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas)

**Comment by ds604** [comment]
thanks! here's the project: http://snap.berkeley.edu/snapsource/snap.html#present:Username=ds604&ProjectName=mathjax%20tests

i had a test page where i was trying to render the div to the canvas, but it was giving me the error: Uncaught TypeError: element.getElementsByTagName is not a function


```
<html><body>
<div style="font-size:20pt;">\[ a^2 + b^2 = c^2 \]</div> 

<canvas id='the_canvas' height='200px' width='699px' style="background-color:red"></canvas>
</body></html>

<!--<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.3/MathJax.js?config=TeX-AMS-MML_HTMLorMML.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js"></script>

<script>
MathJax.Hub.Config({
	tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
})

window.onload = function () {
    function canvasProcess(){
      //$math = $(".MathJax_Display")
		var math = document.getElementsByClassName("MathJax_Display"); 
		  html2canvas(math, {
        	onrendered: function(canvas) {
				canvas.id = 'copy';
				document.body.appendChild(canvas);
				var ctx = document.getElementById('the_canvas').getContext('2d');
				ctx.drawImage(canvas,0,0);
			},
      	});
    }
    MathJax.Hub.Queue(canvasProcess);
}
</script>
```

**Comment by cycomachead** [comment]
Yeah, in my experience html2canvas has lots of random issues -- there's a big PR on the KaTeX repo that's trying to add canvas export to the Katex library.

https://github.com/Khan/KaTeX/pulls


If you're cool with a floating div you could totally make this work, but it won't be able to really interact with a sprite. (I suppose you could make a whole "math object" library that makes moving and showing / hiding divs easy.)

**Comment by ds604** [comment]
I didn't know about KaTeX, actually. It looks pretty good

I guess if you set `div.style.pointerEvents = "none";` then it winds up acting pretty much as it would if it were stamped to the canvas.


Sorry for OT, but I have a question that's somewhat similar to this issue of how to get a dom element to work with the Snap world. I have this file (http://snap.berkeley.edu/snapsource/snap.html#present:Username=ds604&ProjectName=MIDI%20events) where I'm loading a library for WebMIDI, so that I can play on my keyboard, and the events (as I have it set up now) get logged to the console. How would I get these browser events to register with Snap? I guess I'd like to make something like an 'on MIDI event' block. I was reading through some of the documentation, and it looks like I have to register it as a morphic event. But I was wondering if there's maybe a simple example that shows how you might do something like this.

**Comment by nathalierun** [comment]
Nothing to do with the solution proposed by @ds604 .
I propose very simples solutions here to @AlainBusser, following @cycomachead's advise :
- either this one :
![frac snap](https://cloud.githubusercontent.com/assets/17542520/21129872/31e1273a-c11e-11e6-9fc6-1fa58a0031a7.png)

- either tis other one :
![frac1 snap](https://cloud.githubusercontent.com/assets/17542520/21129919/721ae944-c11e-11e6-963f-6054f550c511.png)

The project is shared here :
http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=FractionPourBubu
To have the Label block, you just have to _import tools_.

**Comment by jmoenig** [comment]
This is beautiful, @nathalierun , thanks for sharing the scripts and the project!

**Comment by nathalierun** [comment]
@AlainBusser 

I converted your Scratch project with Snapin8r2.
Here is your project :
http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=Fractran_without_fractions_0.Bubu

Now, you have to debug ;-)

**Comment by AlainBusser** [comment]
Great, this snapin8or, I have to try it!
@jmoenig maybe you could use it to remix your hilarious Eliza program ;-)

**Comment by bromagosa** [comment]
(trying to unclutter gh issues a little bit)

Closing this as the forum is a much more appropriate space for Q&A :)
