### ISSUE TITLE
Manupilating blocks

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap#1693]
Hi,

This very nice article on langages and programmation gave me an idea.
http://revue.sesamath.net/spip.php?article897

I would like to create a Peano curve, like this one :
<img width="383" alt="capture d ecran 2017-03-23 a 13 23 38" src="https://cloud.githubusercontent.com/assets/17542520/24243634/2f3c477a-0fd5-11e7-9c23-222158a8c94e.png">

I first made those two scripts (and I effectively have a correct recursive script which gives to me the peano curve above) :
![fractale motif base](https://cloud.githubusercontent.com/assets/17542520/24243655/4963de1a-0fd5-11e7-95aa-82aa38b12927.png)
![fractale motif recursif](https://cloud.githubusercontent.com/assets/17542520/24243659/4bf326ea-0fd5-11e7-9100-305d572ebbc0.png)

And now, I wonder whether I could do it **another way**.
In fact, if I have simple blocks A (move), R (move back), D(turn to the right) , G (turn to the left) ,
![a](https://cloud.githubusercontent.com/assets/17542520/24243730/89a90d88-0fd5-11e7-9b30-f6068c008b87.png)
and if I define this "world" of blocks :
![mot](https://cloud.githubusercontent.com/assets/17542520/24243766/a638e95a-0fd5-11e7-92c5-2069faec9516.png)
how can I replace the A block by the entire "world" block Mot ?
I've been thinking about it for several hours, and all I tried did not succeed. 

I have a few questions :
- how can I separate a block from a block of blocks ?
- Am I suppose to create a list with the whole blocks of my world block ?
something like that :
![liste blocks](https://cloud.githubusercontent.com/assets/17542520/24243940/5a1a9806-0fd6-11e7-8498-d43a2df306e6.png)

So at each step, I could replace the A block 
![a](https://cloud.githubusercontent.com/assets/17542520/24243987/900211e2-0fd6-11e7-898e-fd42f3bb11aa.png) by the entire world block : 
![mot1](https://cloud.githubusercontent.com/assets/17542520/24244004/a0f19d60-0fd6-11e7-97be-4a9066871ee5.png)

Thank you for any help ;-)

**Comment by micahcowan** [comment]
> how can I separate a block from a block of blocks ?

That part's not too hard: under "operators" there's a block that by default looks like 
![is-5-num](https://cloud.githubusercontent.com/assets/4712979/24266304/95515076-0fc3-11e7-8086-44bdfca9d897.png) - You can use the drop-down to change the selection from "number" to "list", and that will tell you if you have a list, or some other kind of thing.

The real problem, though, is that _Snap!_ doesn't appear to provide a good means to test whether a ringed function matches a particular one you're looking for:

![set-foo-to-ring](https://cloud.githubusercontent.com/assets/4712979/24267789/b29ffa06-0fc8-11e7-9af5-a4d1ab748adb.png)
![eq-foo-bar](https://cloud.githubusercontent.com/assets/4712979/24267796/b9f77ef0-0fc8-11e7-9368-4bb839384e97.png)

The equality test above looks as though it should report true... but it doesn't, because each "ring" results in a new, separate object, even if they're ringing the same function with no additional arguments. I'm not even sure how you'd create a working operator for comparing the two in a JavaScript function... maybe comparing `a.expression.blockSpec`, but I'm not at all certain of that.

**Comment by cycomachead** [comment]
What you're looking for is probably easiest by looking at the `blockSpec` -- though I expect there are cases with lambdas where you'd be best served by serializing the script and comparing equality that way, but if a single block, I don't see a problem, with the block spec approach.

**Comment by micahcowan** [comment]
One way I can think of that might be similar to what you were looking for, though it's a bit more complex: you could have reporter versions of the blocks, where `R`, `G` and `D` reporters are defined like:

![r-def](https://cloud.githubusercontent.com/assets/4712979/24271346/14208162-0fd6-11e7-8341-c39ff206524a.png)

and `A` is defined like:

![a-def](https://cloud.githubusercontent.com/assets/4712979/24271361/23f518a0-0fd6-11e7-9e24-d94158ae4f05.png)

where `replacement` is something like:

![set-replacement](https://cloud.githubusercontent.com/assets/4712979/24271455/77fbcd54-0fd6-11e7-97c7-47207108cc86.png)

And start with a list of the reporters (defined similarly to `replacement`). On each iteration, you generate a new list from the existing one, calling each item in the original list to produce results to tack onto the new list, and giving them as input the iteration counter (counting down from some number to 1 on the final iteration). Since all of them return blocks instead of reporters when they receive the "1" number, the final version of the list will be a list of the movement blocks, and you can then go through that list with "run".

**Comment by brianharvey** [comment]
I don't think you need to manipulate the definitions of blocks to do recursion, which is all you really want for this project.  You just need your A block to know what level of recursion you're at, and either move forward or make a recursive call.

The really straightforward way to do that in Snap<i>!</i> is have A take inputs for size and level.  MOT calls A; A calls MOT; and so on until A is called with its level input = 0, so it just moves forward instead of calling MOT.

But when we get hybrid scope working, you won't even have to have A take inputs.

**Comment by micahcowan** [comment]
> I don't think you need to manipulate the definitions of blocks to do recursion, which is all you really want for this project.

Actually, we weren't talking about manipulating the definitions of blocks; the context of using `expression.blockSpec` was for an attempt at equality testing between ringified blocks, which seems awkwardly difficult at the moment (and would be required for her to do what she originally asked: loop-and-replace).

Another approach could be to use strings or numbers representing the blocks she wants, and then convert only at the very end, prior to execution. But of course, recursive function calls are liable to be more efficient than "replacement" solutions.

**Comment by brianharvey** [comment]
Scheme doesn't let you compare procedures for equality either, so I don't feel too bad about this.  We could, I guess, check for "is identical to" which would be true for two pointers to the exact same block (not two blocks with the same innards).  To do equality testing correctly, we'd have to check not only the code but the environments in which they were created.

**Comment by cycomachead** [comment]
> To do equality testing correctly, we'd have to check not only the code but the environments in which they were created.

I'd say it depends on the definition of equality. Equality of the definition, even if it wasn't aware of the environment could still be useful.

Here's something for a very simple case, but it needs to be a bit more clever to handle other / more complex inputs:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=Spec%20Equity

**Comment by brianharvey** [comment]
Wait, isn't the blockSpec just the title line?  So the bodies could be completely different?

Actually if we're going to do real equality of functions, we should check _everything but_ the title line!  Two procedures with different names can implement the same function.  This is why Scheme punts on comparing functions.  It's too hard to get right.
x ↦ x + 2
x ↦ x - -2
are the same function.

I think for most purposes EQ? testing is good enough, isn't it?  = should ideally give an error "can't compare functions for equality; use IS IDENTICAL TO ? if that's what you want to know."

**Comment by cycomachead** [comment]
It's totally not perfect and to use it "correctly" in a program you'd need to make assumptions about how that author structures code. I think it's still a useful thing. 

In Snap! we can't have two global blocks with the same spec or but we could have two different sprite local ones. 

I want to write one that also compares the definitions. It's totally doable, we do it in the autograder, I just need to make it a block. :)

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
I guess.  At least it should require that the defining environments be EQ?.  That would let you compare global blocks (the main case) and still not falsely call procedures with different closures equal.

**Comment by nathalierun** [comment]
@cycomachead 
About equality of blocks, with your test  block called Equity, I have this stange thing :
<img width="282" alt="capture d ecran 2017-03-26 a 10 43 46" src="https://cloud.githubusercontent.com/assets/17542520/24329245/a370cb46-1211-11e7-80ae-7a76fbc75462.png">

**Comment by bromagosa** [comment]
(trying to unclutter gh issues a little bit)

Closing this as the forum is a much more appropriate space for Q&A :)
