### ISSUE TITLE
Code lost? "Load failed: TypeError: Cannot read property 'add' of undefined"

### ISSUE THREAD

**Issue by eprebys** [jmoenig/Snap#1714]
I wrote a bunch of code and saved the project. Now when I try to load it, I get this error:
Load failed: TypeError: Cannot read property 'add' of undefined

This is my project:
https://bjc.edc.org/snapsource/snap.html#present:Username=eprebys&ProjectName=Create%20Task%20Example

I am hoping I can get the code out of the project without having to rewrite it all.

This may be the same issue as the Open Issue described here:
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/953

**Comment by jguille2** [comment]
Hi @eprebys ,

  - Recovering your project.
    - I downloaded your xml by a JS script (lostProject.xml). I can't run this (same error).
    - I fixed _the input problem_ and saved (lostProjectRec.xml). You can run this.
    - I attached both files in this zip:
[issue.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/907172/issue.zip)
 
  - Initial problem
    - *flower* _custom_ block switch to a non existing costume (dandelion?)
    - You must arrange this. (Maybe is an old block that you can delete).
     - I think some of your blocks must be local (_sprite blocks_) because they switch sprite costumes.

  - Notes for developers (to show the origin)
    - The original block (I guess) is
![flowerblock](https://cloud.githubusercontent.com/assets/2926315/24824999/23ae1080-1c16-11e7-92a3-0e3306754f62.png)
    - _dandelion_ costume does not exist. But I think there is no problem if I export-import the project. Maybe the problem is saving to the cloud. We use "<snapdata" with the _media_ separated... and this is quite different.
    - But the problem is not direct. It introduces a `<l/>`  into the next _if_
![scriptproblem](https://cloud.githubusercontent.com/assets/2926315/24825060/3a4f447a-1c17-11e7-9250-82f882a5c56f.png)
  - Another curios thing is that I can open the original xml with Snap4Arduino (and also directly from the cloud). This is another thing, because the difference is Snap4Arduino don't crash with this ` <l/>` but the block is not the original because it.
![blockfroms4a](https://cloud.githubusercontent.com/assets/2926315/24825122/81efe9c8-1c18-11e7-80cc-67cf1b8e4c28.png)

**Comment by jguille2** [comment]
I only write down, that I can't reproduce the issue... and I don't get this `<l/>` added to my code (I've tested after renaming and erasing costumes).

Maybe the origin is other. @eprebys , do you know which was (exactly) the code of this _flower_ custom block? Maybe it's not the same as I assumed from the recovered code.

**Comment by eprebys** [comment]
That looks like what I had for the block. I wasn't calling the block
anywhere because I found some issues with the way the clones behaved,
especially some apparent bleed over behavior with size and costume. I
intended to delete the flower block when I got locked out of the code. I
had deleted the dandelion costume (as well as cleaning up a lot of other
methods, etc) and it sounds like that may have been the problem.

On Apr 8, 2017 8:06 AM, "Joan Guillén i Pelegay" <notifications@github.com>
wrote:

I only write down, that I can't reproduce the issue... and I don't get this
<l/> added to my code (I've tested after renaming and erasing costumes).

Maybe the origin is other. @eprebys <https://github.com/eprebys> , do you
know which was (exactly) the code of this *flower* custom block? Maybe it's
not the same as I assumed from the recovered code.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1714#issuecomment-292713879>,
or mute the thread

**Comment by jguille2** [comment]
Ok,

Then I guess you has your code again from my zip file and this issue can be closed, right?

**Comment by eprebys** [comment]
Yes, thank you much for recovering it.

Do you understand the underlying problem? Is it a good idea to implement
some sort of recovery mechanism that is available through the interface?

I am afraid that students working on a cs-principles create task could run
into this. As a user it feels like there is no recovery process when your
save file is corrupted. I assume other people are seeing this and not
logging bugs.

**Comment by jguille2** [comment]
Yes @eprebys, but as I said, I cannot reproduce the issue. I haven't any action to repeat this phantom `<l/>` into the code. Because this, I suggest to clole this.

I moved from cloud to xml with a single code (calling _SnapCloud.getPublicProject_ function with _ide.saveFileAs_ function as its callback). It's easy to implement this (_from cloud to xml file_) but I don't know if it's a good idea.

**Comment by eprebys** [comment]
Is it worth changing the error message to explicitly suggest logging a bug
(ideally with the URL included) as a method to recover the project?

**Comment by jguille2** [comment]
Hi @eprebys ,
Thanks to @bromagosa in [this comment](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1709#issuecomment-292864681), I've seen that Snap! in _snap.berkeley.edu_ already has a _#dl_ hash to do it (get xml of a project from SnapCloud).

Then, you can call [https://snap.berkeley.edu/snapsource/snap.html#dl:Username=eprebys&ProjectName=Create%20Task%20Example](https://snap.berkeley.edu/snapsource/snap.html#dl:Username=eprebys&ProjectName=Create%20Task%20Example) and you'll get your xml.

I've seen the format is not the best. Depending your browser, you'll get an error... but in the url you'll hava all your code. You must copy and paste it.

Now I think this issue is really closed.

Joan

**Comment by eprebys** [comment]
Nice find. It will help me with any students who run into problems with
losing their code. I'll post a brief summary to the Snap! discussion list
so other teachers know about the recovery procedure and have it as a
resource if they have students that run into similar problems.

I agree the issue is closed until/unless someone has effective reproduction
steps.
