### ISSUE TITLE
Script pic with result hangs when script is within a block editor

### ISSUE THREAD

**Issue by stirlingstout** [jmoenig/Snap#1740]
I really like the experimental (shift/right click on a script) _script pic with result..._ feature: a lot easier than screen grabbing.

However, I really like the feature that lets me save, in a custom block's definition, sample expressions for a user to experiment to get a feel for how the custom block is used. If I define a simple factorial script and place an example, e.g., _10 !_ on the stage I can get _script pic with result..._ to work (ignoring Firefox issues for the moment). However, if I put the example inside the definition of _!_, when I try _script pic with result..._ it hangs and Snap! is completely unresponsive (see attached image).

I've tried this on the 4.1 development and 4.0.10.2 website versions with the same result.

![unresponsivescriptpicwithresult](https://cloud.githubusercontent.com/assets/2162695/25543778/cd06e050-2c4f-11e7-8821-1f5827e7e253.JPG)

**Comment by cycomachead** [comment]
Two things here:
1. We have an infinite loop when there's an error, which seems bad.
2. There's an edge case in the internal API.

@jmoenig 2 is easy to fix, but I'm not sure what what's the best way to do so. 

We call `block.parentThatIsA(IDE_Morph)`, but since BlockEditorMorph isn't actually a child of the IDE this returns null and things break. We either need to get the IDE from the BlockEditorMorph / world, or move the `saveCanvasAs` function to some more easily accessible place...

**Comment by jmoenig** [comment]
Jeez, why am I only seeing this now?! Yes, it's an easy fix, @cycomachead . Sure, let's just get the IDE from the BlockEditorMorph. I'm pushing a fix now...
Thanks!
