### ISSUE TITLE
Persist Retina Display Setting 

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#1819]
See #1818 and various other threads. I think we should still make this a hidden setting, but that's a separate argument.

**Comment by brianharvey** [comment]
It can be hidden, that's fine.  You could even hardwire in username=bh, as long as it happens!

**Comment by jmoenig** [comment]
I'm not going to do this. Retina support is way too important. Brian can turn it off himself.

**Comment by cycomachead** [comment]
If it’s too important then the current setting doesn’t make sense. I still maintain the only problem BH has with retina mode (exporting images) is fixable.

I don’t think we really should need this setting, honestly, but as long as we have it, treating it as a “session” setting doesn’t make much sense. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
So, Jens, you and I agree that it's really important.  You think it's really important to have it turned on, and I think it's really important to have it turned off.  _This is precisely why settings were invented!_  So that Alice can have things her way, and Bob can have things his way. By making this particular setting keep resetting itself to your preferred value, you're just punishing me for having different taste from you.

(P.S.  Aren't you supposed to be on vacation? ☺)
