### ISSUE TITLE
Enhancement request: Import script snippets

### ISSUE THREAD

**Issue by davidsturman** [jmoenig/Snap#1883]
I am using Snap! to teach as part of the TEALS program.
In grading, it is often helpful to add scripts that can help me examine student programs.
Having to re-enter these scripts for every student's assignment is a nuisance.
Is there any way to import individual or groups of scripts to add to an existing project?

Scratch has a backpack that allows you to do this.  Can Snap get a similar facility?
Doing this with sprites and costumes would also be useful.

**Comment by cycomachead** [comment]
First, I'd be super curious to learn more about what those scripts do. Do you have the same ones for each project or is it more specific?

In the meantime, dropping an XML of a block (from Export Blocks) is the best work around. 

> Doing this with sprites and costumes would also be useful.

You can export a sprite by right clicking on it in the corral and re-import it, by dragging and dropping the XML file or using the import command.

There's an open pull request to add support specifically for scripts, so this might happen soon. 

The cloud functionality is something we'd like, too, but this is much harder since there's not much effort being dedicated to cloud development.

**Comment by brianharvey** [comment]
Since a sprite includes its scripts, you can put your script in its own sprite, export that, and then import it to student projects.  (And then, if necessary, drag the script onto another sprite's icon in the sprite corral.)

**Comment by jmoenig** [comment]
in the upcoming new version 4.1 there is also an experimental feature that lets you export / import arbitrary scripts from the scripting area (shift-right-click).

**Comment by davidsturman** [comment]
Michael,

This was very helpful and provided the functionality I was looking for.

My use case was in grading the TEALS Introduction to Computer Science Lab
2.2 (
https://tealsk12.gitbooks.io/introduction-to-computer-science/content/lab_22.html)
where students fill the stage with a brick wall without drawing extra
bricks.  In order to see if they are drawing extra bricks off-stage, I
change the size of the stage and draw a rectangle where the old stage is.
I can do this in a few seconds now by dragging in the stage-outline-drawing
sprite .xml file into each project.  I've attached the .xml file in case
anyone is interested.  The script draws a red rectangle in response to the
's' key.  I don't have a way to automate changing the stage size.

 -djs
