### ISSUE TITLE
Set Pen Color not working

### ISSUE THREAD

**Issue by Brooks99** [jmoenig/Snap#1906]
In SNAP! release 4.1.0.2 the Set Pen Color <number> is not working using Chrome browser.  Running Windows 10 Insiders Release and using chrome Version 61.0.3163.100 (Official Build) (64-bit).  To duplicate drag Set Pen Color to number block and enter 130.  This should a render a Red color sprite when executed.  Note: There is a known bug with the help text.

**Comment by jmoenig** [comment]
Hmm... it works for me in Chrome Version 62.0.3202.75 (Official Build) (64-bit).

**Comment by Brooks99** [comment]
Jens,
I will investigate using same chrome version. Also, I have trouble with code not stepping in custom blocks.  Believe Not related.  Thanks for ur work in helping kids learn computer science.

**Comment by jmoenig** [comment]
You need to open the block editor *after* turning on visible stepping

**Comment by jguille2** [comment]
And about _set pen color_ issue, I think there is no changes from previous versions.

@Brooks99, I think you are reporting the current (current and previous versions) behavior of Snap! Let's check this:
  - If you open a new project, default pen color is grey. Then, even if you _set pen color to 130_, you will not get a red color because, althought its hue is certainly red, it's too dark.
  - You can test this: Open new project (sprite is grey), _set pen color to 130_ (you get a darker red sprite), and then _set pen shade to 100_ (and you'll get the full red color you expected!)
  - After _shade_ is fixed to 100, you can change the hue and get other full colors.
  - Also, you can pick a color with the _set pen color to (palette)_ . If you pick colors from the top half of the palette you'll later get _bright_ colors with the _set pen color to (number)_ block. But if you pick colors from the bottom half, you'll get darker (or too dark) ones.
  - As you said, help text is wrong and _hue_ scale is 0-100 without wrapping. Then 130 (and all greater than 100) is red and not blue (as the help text says).

  - I think you can close this issue

@jmoenig, excuse me, I've already written too many lines about this subject... but the current behavior will continue to generate doubts and problems. There are already several opened issues [about this](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/labels/cat%3A%20pen) (and others not labeled like this one)

Many hours discussing about this (#1736, #1659, [different docs](https://github.com/jguille2/jguille2.github.io/blob/master/docs/progress.md)...). But if you agree I can reopen it and work on it as much as necessary. Beyond the problem of the concept of _hue_ (the most conflicting point), I think there are two basic axes:
  - Set clearly *scales* and *wrappings* (rollers, %...) , making clear the affectation respect Scratch behavior, current Snap! behavior and a 'natural - clearer' behavior.
  - Rewrite core to ensure a robust behavior (now is mixing rgb, hsv and hsl...and different methods) and causing some confusion (like this issue, where a block that changes Hue is also changing Saturation (fixing to 1) but keeping Value (brighness))

**Comment by Brooks99** [comment]
I upgraded to Chrome Version 62.0.3202.75 (Official Build) (64-bit per @jmoenig first not duplicatable response and change pen to color <number> now working as specified.  Issue closed.

**Comment by ToonTalk** [comment]
I'm having problems with set pen color in both Chrome 68 and FireFox 61 (Windows 10). 4.2.1.3 The colours are very dark. Also the help sample code seems to assume the heading is 0.

[pen color problem.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2299341/pen.color.problem.zip)

![image](https://user-images.githubusercontent.com/2138696/44298028-87815780-a2d3-11e8-99a8-437779ccfa0a.png)

**Comment by brianharvey** [comment]
Another problem from borrowing Scratch's help screens.

Do SET PEN SHADE TO 100 before your program.

**Comment by jmoenig** [comment]
Thanks all. Colors have been completely reimplemented and extended for Snap5. I'm expecting this issue to be resolved. Closing...
