### ISSUE TITLE
Suggestion for pixel library 'create costume'

### ISSUE THREAD

**Issue by LeadToGold** [jmoenig/Snap#1930]
<img width="456" alt="create costume" src="https://user-images.githubusercontent.com/8217635/32704398-263d37dc-c7b9-11e7-9732-09644f659fc0.PNG">

I found myself wanting to create a costume out of calculated pixels. I implemented this block to do it. Is it worth adding to the pixel library? Is there some other way of doing it?

ltg

**Comment by brianharvey** [comment]
I guess Jens's expectation was that people would do image processing on pre-existing costumes (using the UPDATE block in the library) rather than create them _ab initio_ (that's how you say "from scratch" when you don't want the hearer to get confused about Scratch).  For that task we have the PEN TRAILS block; you draw your costume on the stage and then ADD (PEN TRAILS) TO (MY COSTUMES).  It's a little easier than your way because Snap<i>!</i> automatically finds the minimal bounding box.

Given that, do you still want to argue for adding your way?  I don't hate the idea, although honestly it's lower on my list than selectors for the dimensions of an existing costume.

**Comment by LeadToGold** [comment]
I was writing a Mandelbrot implementation and wanted to display a 400 x 360 representation on the Snap canvas.  Pixel by Pixel drawing (using pen down, move) is very slow so I looked for an alternate method.  My first try was to write it directly on the stage but (not fully understanding Canvas API) managed only to screw up the canvas.

I can of course create a 400x360 costume and use the pixel library to set the costume pixels. But I thought it might be useful to be able to dynamically create a costume of arbitrary size.

ltg

**Comment by LeadToGold** [comment]
Alternatively (but probably even less likely) the ability to splash some pixels directly to a rectangle on the screen.

ltg

**Comment by brianharvey** [comment]
Ah, I see.  Okay, that's a good reason.  :-)  Jens?

**Comment by jmoenig** [comment]
In the new Snap5 you can now create custom Costumes using the new STRETCH primitive. Closing, thanks!

**Comment by LeadToGold** [comment]
Thanks Jens!

sean
________________________________
