### ISSUE TITLE
For loop needs improvement

### ISSUE THREAD

**Issue by bjr1822** [jmoenig/Snap#2004]
The current for loop block should:
1) be standard and not part of additional imports
2) be fixed to prevent the "0-length list" issue with the current form of the block.
i.e. currently when running a standard 'for' loop of the form
for i = 1 to list.length
for a 0 element list, it runs twice, once at i = 1, and another when i = 0, which is nonsensical. It should run 0 times.

This can be fixed by taking a page from the old VB6 / VBA looping construct using an optional Step argument. Back compat can be easily maintained with this suggested change.
Pseudo Code:

for i = <begin> to <end> [Step <step>]
{
if <step> = ""
  do old behavior to calculate step = 1 or -1 depending on begin < end or begin >= end
end if

if <step> < 0 then
  set compOp = [>=]
else
 set compOp = [<=]
end if

for (i = begin; compOp(i, <end>); i += <step>)
   do code
end for

}

For back compat, step can remain blank to opt into existing behavior. However, new inserts of "for" I would recommend exposing the step field and defaulting it to 1. That way the default behavior and setting eliminates the currently extremely annoying 0 length list issue.

I would be happy to code this change to make it happen. I would need some guidance on how to go about making a pull request and making such changes to underlying library blocks.

**Comment by brianharvey** [comment]
I agree with you about making it primitive.  Jens and I have a longstanding disagreement about exactly which blocks should be primitive (and a related disagreement about automatically loading the tools library into every new project),

As to the behavior of FOR, it's the way it is partly because its implementation shows off the use of procedures (namely the end-test predicate) as data, which is one of our central pedagogic ideas.  But I agree that people find it confusing in practice.  On our medium-short-term list is a feature to allow making a group of inputs and title text variadic, and also a feature to set minimum, default, and maximum number of instances of a variadic input slot.  Then we can have
![unstep](https://user-images.githubusercontent.com/3885074/35773619-8bb040ca-090c-11e8-82bf-3ed6b96786d0.png)
![step](https://user-images.githubusercontent.com/3885074/35773622-9c0e3d14-090c-11e8-92aa-d4e46e0ca404.png)
Given all that, I'm reluctant to introduce a change to FOR that we're just going to change again.

(One of the issues is that Snap<i>!</i> supports our [curriculum](//bjc.edc.org) and every time we make a user-visible change we have to recreate a bunch of pictures.  So we try to minimize them.)

**Comment by bjr1822** [comment]
Fair enough, that proposed change would work nicely. Note that my proposed solution would still illustrate the procedure-as-data concept. That is what the 'compOp' is, which would still be required depending on whether step is calculated to be positive or negative.

**Comment by brianharvey** [comment]
Yeah, that's true.  We'll get there.

**Comment by jmoenig** [comment]
FOR is now going to be a primitive in Snap5. I guess that's the big news. Closing, thanks!
