### ISSUE TITLE
"real" offline version / desktop app needed

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap#2116]
we urgently need a "real" offline version of Snap! for use in German schools and in Africa Code Week (we probably also need it for other areas in the world with poor internet accessibility). "Real" means it basically needs to be the same as Snap4Arduino, i.e. a self-contained node + webkit app with platform specific installers and access to libraries, costumes, sounds and examples.

**Comment by gdavid04** [comment]
Maybe using [ElectronJS](https://electronjs.org/)?

**Comment by brianharvey** [comment]
I've been using the Snapp<i>!</i> page to make them, but you're right, that doesn't provide all the libraries (in the broad sense).  Is this something you'd be willing to assign to a 12-year-old?  The only required change to Snap<i>!</i> itself would be changing getURL and resourceURL to be able to look on the local disk, I think.  But making the installers and stuff should be straightforward.

**Comment by jmoenig** [comment]
I would love to get @jguille2 's input here (nudge, nudge ^^), or @bromagosa 's :-) Those I have compete trust in :-)

**Comment by jguille2** [comment]
For me is clear: my Snap! desktop version is Snap4Arduino. :stuck_out_tongue_winking_eye: 

Two considerations...

### 1. Snap4Arduino goals
Snap4Arduino is "only" a full Snap! with three additions:
  - A desktop version, to run a full Snap! offline (you know `file://` have some problems)
  - A Firmata serial connection. for many devices (not only Arduinos) to get a physical-electronics interaction.
  - And a webServer. to implement active IoT solutions and to connect different devices (PCs, phones...) and different projects (connecting different Snap! or Snap4Arduino projects).

We need these addons to answer to the needs of our schools and classrooms. But you know we are not focused in Arduinos (or other boards). We are focused on Computer Science projects. You know we are Snap! lovers. :kissing_heart:

### 2 Logistics
We are only two persons making this version in our free time. :sweat: We always want to improve our task (and the _todo_ list is always full)... but we have not more time. A desktop version is not complicate... but it requires time... and it adds always different platform issues. The problems we know about browsers changes, are multiplied by other projects (node, nwjs, other node_modules, builders... Linux, Macs, W$ and versions... 32/64arch...) 

Then, I vote for employing all the efforts in only one desktop version. If you need features that Snap4Arduino has not, ask us for them... and we will try to implement them. :construction_worker_man: :construction_worker_man:

**Comment by brianharvey** [comment]
The only problem with that is version skew.  So my counterproposal would be to merge all the S4A stuff into the main repo here, and write a make script that makes all the assorted installers whenever there is a new release here.  The stuff that's really Arduino-specific could be a library, as a good test case for making sure users can get access (maybe with JSfunction) to all the needed infrastructure.

**Comment by jguille2** [comment]
But I like a clean Snap! repo, without builder scripts and a lot of dependences.

Snap! code only needs a browser. And yes, sometimes we have problems created by browser projects evolution. But desktop version has more dependencies. For example, right now we have to look for a new builder, because the Mac version is not built well (Bernat builds this version by hand).

And a last comment, about the logistics, organization and efficiency. If you need to have a cleaner version (without Snap4Arduino options, with standard logos...), for me it's better (easy) to introduce params and code into Snap4Arduino repo to be able to build this version (or build only one version with a parameter to toggle between "cleanDesktop/Snap4Arduino") than to create another project.

**Comment by bromagosa** [comment]
@gdavid04 that's an offline version but not a desktop version. HTTP requests will still have the same CORS issues as the online version, it won't have automatic updates, a desktop icon, an installer/uninstaller, etc.

Your suggestion is, however, super easy to implement, so if that's all they need for Africa Code Week, we can do that pretty quickly.

**Comment by introlinux** [comment]
@gdavid04 I use what you say all the time when I have a slow internet connection. Specifically, I use python in the Snap folder:

`python -m SimpleHTTPServer & firefox http://localhost:8000`

**Comment by cycomachead** [comment]
Woah, how did i miss this issue. I have had an electron version working for a while, but I never got around to the auto updating fully working. I also wasn't sure if I could compile the windows version. 

I have no problem with documenting and providing a simple script, but I don't think we should pretend that this will solve the problem for many. 

I'm happy to have anyone contribute to the electron app, and provide an auto-update server. (I was running GitBookIO's [nuts](https://github.com/GitbookIO/nuts) and i think it should work fine.)

**Comment by nathalierun** [comment]
Fantastic ! It would be great to have this offline version for next school year.
In Reunion Island, it begins the 16th of august...
As I told to @jmoenig, I proposed 2 researches on Snap! in highschools for next school year (2018-2019), as part of the IREM (Research Institute for Mathematics Education in France). They are accepted by the scientific council of our department. So I'm happy to tell all of us that I'm going to do a lot of Snap! activities in my classrooms.

Snap! has come a long way in France in a year, especially in the minds of the decision makers of the new mathematics programs in high school. 
And I will show everyone (in France) that Snap! is the best and most appropriate tool for learning algorithms in the classroom. 

Simplify the use of a offline Snap!  is urgently required because our new president is restructuring the school completely, including the content of mathematics programs. The Ministry of Education has (finally) planned to introduce a real computer specialty. They are thinking now about the contents of this specialty.
And I advocate for the use of Snap! in class...

**Comment by ToonTalk** [comment]
I've found localhost: in the browser works great but file: works almost as well.  The [offline documentation](https://github.com/jmoenig/Snap/blob/master/OFFLINE.md) is very good but neglects to mention that if the microphone or camera is used then one is asked for permission for each use (at least in Chrome). The CORS issue with reading HTTPS URLs should be documented as well.

I did discover a problem with file: that probably is easy to fix. "Libraries" acts like "import" but the download now should include local copies of the libraries. At least it should open the dialog in the libraries folder. Also something to document in the OFFLINE doc.

I've been helping with workshops in Indonesia where it was very easy for them to use localhost to avoid these problems. In Windows there are simple web servers that are trivial to use. They use miniweb.exe (109K) and no configuration (other than to move the Snap! files to a "htdocs" folder). There must be similar static web page servers for other OSes.

I would also consider using [Progressive Web Apps](https://developers.google.com/web/progressive-web-apps/). From what I've seen and read it is the perfect solution but no first-hand experience with it (yet).

**Comment by cycomachead** [comment]
I’ve been meaning to mention this for a while, but the offline file mode really only works decently in Chrome. It works mostly because chrome has changed security models for some features in the past few versions, though this isn’t well documented. :/ (for instance, cameras working offline.)

The import thing just won’t work right in the file mode — we can’t asynchronously request a file and there’s no file system access. There’s a terrible hack of dynamically inserting a JS script tag, but doing so requires wrapping content in valid JS functions, which doesn’t really make sense for XML content. 

PWAs are a great solution for offline access and they address the main specific offline challenges, like importing libraries and accessing cameras. This biggest tech challenge I believe is managing caching, but that’s solvable. 
PWAs are super easy to “pre-install” like you would a typical app, which is what we have heard some users would like to do. 
PWAs are also fairly closely tied to Chrome. That may change, but also means they aren’t necessarily universal. 

However, a desktop wrapper would provide us real file system access and is easier to pre-download to a system, simply by copying a binary places. 

Right now, I think a PWA is probably not too hard to setup and doesn’t prevent us from also building a desktop app too. OTOH, there’s just so much more we can do with a desktop app... 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by ToonTalk** [comment]
By "The import thing just won’t work right in the file mode" I think you meant loading libraries without it acting like import , right? Import works fine. One could on each release generate a JavaScript file which contains strings for each library's XML. Either one file for all or one each.

I went to [Can I Use](https://caniuse.com/#search=pwa) and it did say "Firefox status: in-development". [Google says](https://developers.google.com/web/progressive-web-apps/desktop) they;'ll work on any desktop except Macs and that's planned for early 2019.

I know of many schools that make it very hard for teachers to install an executable (since as you say "a desktop wrapper would provide us real file system access") while I assume there isn't such an issue with a PWA. A school's IT staff can be assured that the PWA is as secure as a web page.

**Comment by cycomachead** [comment]
But IT staff can’t really “install” PWAs, and they can still be turned off as they require some additional access.

The thing is that PWAs and electron really address different concerns with offline access. 

To be clear, I’m not against having PWA support in Snap!, I think it’d be a help, but I’m not sure that it solves all of the problems still. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by ToonTalk** [comment]
Right. 

My understanding is that it is possible for a user to click on a link and the PWA is just like a web page except one can easily then indicate one wants to cache it locally and to have a nice launch icon.

**Comment by jmoenig** [comment]
This has since been addressed by having a "really working" and better packaged version of the sources. Closing. Thanks!
