### ISSUE TITLE
For loop over 180 times faster than map

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2130]
I implemented dot product using map as

![image](https://user-images.githubusercontent.com/2138696/41809957-52b10f54-76f6-11e8-9d1d-2c2426f41f24.png)

Then comparing it with this

![image](https://user-images.githubusercontent.com/2138696/41809941-04dc1c2e-76f6-11e8-8d08-4071b23d5fbe.png)

I found the for loop version on lists 300 long took about 7ms while the map version took 1.29s. This was with warp. Without warp I was surprised to see the map version was a few times faster.

I suppose the map version could only run fast with a very clever optimising compiler. Sad.

**Comment by KingDavid12** [comment]
@ToonTalk A quick test seems to show that you are correct that map is the slow part. You can dramatically improve performance by implementing the map function in Javascript:
![example](https://user-images.githubusercontent.com/12404374/41810061-58cfbeee-76b5-11e8-92d6-13f084aa431c.png)

Some quick testing seemed to show that if you used the standard map function, then a list of about 1000 items takes about five seconds, whereas if you use a version of the map block that is implemented in Javascript, then a list of about 1000 items takes about 100 milliseconds.

**Comment by jmoenig** [comment]
hmmm, this must either be an inefficient implementation of the MAP variant you're using, @ToonTalk , or some kind of glitch in the threading system. The fact that FOR is faster shows that Snap! can be fast enough and doesn't really need to use direct JS, since FOR is also just a custom block, same as this version of MAP. I'll investigate...

**Comment by jmoenig** [comment]
Looks like an inefficient implementation. Snap! can do it really fast without any custon JS:

![untitled script pic 3](https://user-images.githubusercontent.com/2596285/41811040-4c83d834-7708-11e8-8f10-1d56ef239efc.png)

What am I missing?

**Comment by jmoenig** [comment]
looks like an inefficient implementation. Snap! can do dot products really fast using MAP and COMBINE, without any special JS code:

![untitled script pic 4](https://user-images.githubusercontent.com/2596285/41811061-b0957cb0-7708-11e8-80bb-5dd3003d32b7.png)

What am I missing?

**Comment by KingDavid12** [comment]
@jmoenig Nothing. The problem is that the indexed block maps over the second list for every item in the first list. For a list of 10000 items the normal map takes about half a second. The map from list utilities also takes about half second,  but if you split the list of 10000 items into two lists of 5000 items then the list utilities map takes about __28 seconds.__ The normal map block did 10,000 iterations, the indexed map block did a ridiculous __25000000__ iterations.

**Comment by ToonTalk** [comment]
The version of map I was using came from the List Utilities standard Snap! library. I think it is prettier code when you map over two lists but apparently it doesn't do it very efficiently.

**Comment by KingDavid12** [comment]
@ToonTalk as a still reasonably pretty alternative you could make a zip block that merges two lists into a list of pairs, and then map over the pairs. While it would not be as efficient as jmoenig's solution, it would still be much faster then mapping over the two lists with the block from List Utilities.

**Comment by KingDavid12** [comment]
@ToonTalk The List Utilities map is slower than the normal map, have you tried copying his method of using a script variable with the normal map?

**Comment by jmoenig** [comment]
yeah, I never liked the old MAP that's now in list utilities, because I've always found it to be too slow. But I *love* the simple and elegant version we've not put into tools. Maybe @brianharvey can explain why the list-utilities version is so slow (or look into it, for that matter).

But yay! We did manage to find a fast solution purely in Snap! right?

**Comment by ToonTalk** [comment]
Sorry I the timing I reported 5 minutes ago was flawed. The map version was 50 times faster than the version mapping down two lists. But it is still over 3 times slower than the for loop.

**Comment by jmoenig** [comment]
Haha, that goes to show the old finding that imperative programming is unreasonably efficient :-)

**Comment by jmoenig** [comment]
to be fair, our imperative implementation enumerates both lists only once, whereas the functional one does so twice. that explains why it takes longer...

**Comment by ToonTalk** [comment]
The problem with combine of map is that the map needs to construct a list only to have it reduced. A very long time ago I wrote a paper about how a partial evaluator could automatically rewrite the code so no data structure is constructed.

Ken Kahn. The compilation of Prolog programs without the use of a Prolog compiler. In Proceedings of the Fifth Generation Computer Systems Conference, 1984.

**Comment by ToonTalk** [comment]
I just timed a JavaScript-defined dot product and it was 2.5 times faster than the for loop Snap! version. The code is

function (list1, list2) {
    if (list1.length === list2.length) {
        let result = 0;
        list1.forEach(function (item, index) {
            result += item*list2[index];
        });
        return result;
    }
}

**Comment by jmoenig** [comment]
Did you compare it against the new JIT-compiled version?

![do product script pic](https://user-images.githubusercontent.com/2596285/41811610-19bd7c7e-7713-11e8-8be7-4d83719edeb2.png)

(you need to use SET VAR instead of CHANGE VAR because my compiler doesn't yet support CHANGE..., but otherwise it's really fast)

**Comment by jmoenig** [comment]
Playing around with the JIT-compiler I'm really pleased because it can to dot-product of two one-Million-item lists in the blink of eye

**Comment by ToonTalk** [comment]
I tried to reproduce your example and I get

![image](https://user-images.githubusercontent.com/2138696/41811905-8afabf8c-7718-11e8-810a-75ed8ec5ab19.png)

Project attached.
[possible JIT bug.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2130075/possible.JIT.bug.zip)

**Comment by jmoenig** [comment]
Oh yeah, looks like I forgot to special case ```doDeclareVariables``` for the JIT compiler. Looking into this now. Thanks!

**Comment by brianharvey** [comment]
Why does everything happen when I'm asleep?

One problem with multi-list MAP is that it internally does single-list MAP of car and cdr over its list of input lists.  I can probably do that iteratively; I'll look into it.

But what all this tells me is that we really need to get around to the dual-definition feature (primitives implemented in JS but with Snap<i>!</i> code when you click Edit).

**Comment by cycomachead** [comment]
The list utilities map included the `#` variable, because it's sometimes useful and is different than the one in tools. I think keeping track of that index is also what made it a bit slower.

**Comment by jmoenig** [comment]
Now that we've made MAP (and FOR) a primitive I'm expecting this to be less of an issue...
