### ISSUE TITLE
Moving/setting a rotation_X to the most far left pixel(s) of the costume?

### ISSUE THREAD

**Issue by DyslexicAwe** [jmoenig/Snap#2170]
Is there any programmatical way to do it? (An idea is also to have a rotation center position 'style' which could either be "the most far left", "center" (now the default and only option), or "the most far right" pixels of the costume. Similarly to how now GUI has a 'style' of rotation itself, i.e. "can rotate", "only face left-right" or "can not rotate at all" 'style' for any sprite.

I am aware that the rotation center position can manually be changed in costume Editor and I did it, but I need a programmatical solution because of too many costumes in the project [here](https://snap.berkeley.edu/snapsource/snap.html#present:Username=kinestheticlearning&ProjectName=Rotation_center_most_far_left). 
![rotation center most far left pixel](https://user-images.githubusercontent.com/16387241/43763571-5bbf335c-9a2b-11e8-8cf4-734e72e739e5.png) and because in animation, the black parts of the costumes now overlap, and in order to make them transparent, instead of black, I will need to redraw them in an external paint editor, and then "re-import" (drag) them into Snap!, and - if there is no other solution - manually move their centers to the most far left pixels of the costume, again one by one for each costume...
![rotation center change](https://user-images.githubusercontent.com/16387241/43763528-3949b342-9a2b-11e8-8187-bdfb803ad03c.png)

**Comment by brianharvey** [comment]
I bet you can use the pixel library to find out the dimensions of a costume, and then you'll be able to set the rotation center to -1/2*(horizontal size).

**Comment by DyslexicAwe** [comment]
Thanks. I imported the pixel library to find a block suitable for determining the width (i.e. horizontal size)... 

I failed. 

But, nevertheless, playing with the data listed by the `pixels of costume (...)` block from the library, it occured to me that the width itself is needed first, in order to uncover the implicit ('hidden') positions of the pixels data. 

Uncovering the implicit positions was fun. See the 'experiment' sprite in the updated project [here](https://snap.berkeley.edu/snapsource/snap.html#present:Username=kinestheticlearning&ProjectName=Rotation_center_most_far_left).

**Comment by KingDavid12** [comment]
@DyslexicAwe I have a library for working with costumes that allows you to set the rotation center. Here's how you would set the rotation center of the current costume to the far left:
![example](https://user-images.githubusercontent.com/12404374/43902745-2372ddd6-9ba8-11e8-83d3-452659655458.png)

The library also contains a block for getting a list of all the sprite's costumes. Using that block you can do a foreach over the list of costumes, and set each costume's rotation center.

Here's the link for the library:
[Costume Blocks.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2274401/Costume.Blocks.zip)

**Comment by DyslexicAwe** [comment]
@KingDavid12 
That's awesome! Thank you. 

P.S.
Your library is just too good to be available only to us, reading this post.  I don't want you to feel you are being punished for doing a good deed, but would you consider allowing Brian and Jens to include your library into the official libraries as separate "costumes/rotation center" library? What do you think?

**Comment by KingDavid12** [comment]
@DyslexicAwe I am not opposed in any way to the library being merged into, or added as, an official library. Also, feel free to share the library. I have attached the updated version of the library. (If it is going to be shared, or used in Snap! then I want the error handling to be better, and the error messages less cryptic.) Also if you have any suggestions for improvement, errors you noticed or any such thing, I would be happy to hear about it, so that I can make the library even better.

P.S. I don't see sharing something I made as a punishment, but rather as a reward of sorts, because it means somebody found what I did useful. All that to say, feel free to share anything I send.

[Costume Blocks.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2278158/Costume.Blocks.zip)

**Comment by KingDavid12** [comment]
@brianharvey Whoops! You didn't do anything wrong, that's an error in my library. Here's a fixed version:
[Costume Blocks.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2279818/Costume.Blocks.zip)

I rewrote it to have slightly better error messages, but I have not yet figured out what the optimal error message would be. For example, the "set name of costume" block reports the error "can't set the name of a thing that is not a costume", or something like that, in your example when the sprite/stage has not costumes.

**Comment by brianharvey** [comment]
Thanks.  I'll worry about the error messages as I'm merging your code with mine.

**Comment by KingDavid12** [comment]
@brianharvey Okay. Feel free to ping me if there is anything I need to change, or you have any other questions.

**Comment by DyslexicAwe** [comment]
Hey, @KingDavid12 your block enabled me to build upon my experiment and make a custom block for transposing a {pixel list}, and then a block for transposing {any list}. See [here](https://www.youtube.com/watch?v=lLwlhTf0Ads&list=PLkHPPpAaV6zbcoA2w3My7isJUOjN9D0lq&index=2&t=6s). 

![24 08](https://user-images.githubusercontent.com/16387241/44577119-8c8d4d80-a790-11e8-8a2e-6398425c651b.png)
However, as the block is not very fast, I wonder if it could be re-written in JavaScript to make it faster? What do you think?

**Comment by KingDavid12** [comment]
@DyslexicAwe Why certainly, here it is: 

The code as a standalone javascript function that works on arrays:
```javascript
const transpose = function (input_list)
{
    if (input_list.length === 0)
    {
        return ([]);
    }

    const in_height = input_list.length;
    const in_width = input_list[0].length;
    const temp_list_of_lists = [];

    for (let n = 0; n < in_width; n++)
    {
        temp_list_of_lists.push([]);
    }

    for (let i = 0; i < in_height; i++)
    {
        for (let k = 0; k < in_width; k++)
        {
            temp_list_of_lists[k].push(input_list[i][k]);
        }
    }

    return (temp_list_of_lists);
};
```

The code inside a Snap! block (Yes, this version works on lists):
![snapblockjavascript](https://user-images.githubusercontent.com/12404374/44589568-2267af00-a776-11e8-9905-eda48f76c7ca.png)

And of course, the Snap! library:  [Transpose.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2318691/Transpose.zip)

**Comment by DyslexicAwe** [comment]
Wow, I didn't expect you to reply so soon as everyone seems to be on vacation these days (or on the Constructionism2018 conference, as Jens and Brian are), so it is a pleasant surprise to see you answering so soon. I like your solutions in all three forms. Thank you.

**Comment by KingDavid12** [comment]
@DyslexicAwe Your welcome. I hope you find the javascript version useful.

**Comment by KingDavid12** [comment]
And TADA:
```javascript
const getPixels = function (costume)
{
    const pixels = [];
    const src = costume.contents
        .getContext("2d")
        .getImageData(0, 0, costume.width(), costume.height());
    
    for (let i = 0; i < src.data.length; i += 4)
    {
        pixels.push({
            r: src.data[i],
            g: src.data[i + 1],
            b: src.data[i + 2],
            a: src.data[i + 3]
        });
    }
    
    return (pixels);
};

const transpose = function (input_list)
{
    if (input_list.length === 0)
    {
        return ([]);
    }

    const in_height = input_list.length;
    const in_width = input_list[0].length;
    const temp_list_of_lists = [];

    for (let n = 0; n < in_width; n++)
    {
        temp_list_of_lists.push([]);
    }

    for (let i = 0; i < in_height; i++)
    {
        for (let k = 0; k < in_width; k++)
        {
            temp_list_of_lists[k].push(input_list[i][k]);
        }
    }

    return (temp_list_of_lists);
};

const make_a_3d_list_of_costume_pixels = function (costumes, name)
{
    const costume = costumes.find (costume => costume.name === name);
    const costume_pxls = getPixels (costume);
    const width = costume.contents.width;
    const numberOfRows = (costume_pxls.length) / width;
    const costume_pxls_positioned_transposed = [];
    
    for (let row = 1; row <= numberOfRows; row++)
    {
        const current_pxls_row = [];

        for (let col = 1; col <= width; col++)
        {
            const i = (row - 1) * width + col;
            const { r, g, b, a } = costume_pxls[i - 1];

            current_pxls_row.push ([ r, g, b, a ]);
        }

        costume_pxls_positioned_transposed.push (
            transpose(current_pxls_row).map (v => v)
        );
    }

    return (new List (
        costume_pxls_positioned_transposed.map (
            group => new List (group.map (row => new List (row)))
        )
    ));
};
```
The library: [Blocks.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2328662/Blocks.zip)

Usage of the library for your example:
![image](https://user-images.githubusercontent.com/12404374/44732644-fc5a4b80-aaa2-11e8-8ed7-3329a8ab353f.png)

I did not have time to recreate your code, so I don't know if the Javascript is correctly doing the same thing. So before you remove your code, run a few tests to make sure the Javascript block is doing the correct thing. If it is not, then send me a message, and I will fix it later.

**Comment by brianharvey** [comment]
It's often a good idea to recode core algorithms for speed, but rarely necessary to cram a whole complex program into a Javascript block -- you might as well just write in Javascript altogether!  As a rule, your first recourse should be to the WARP block.  This is just a general remark; I haven't run any version of the program under discussion.

**Comment by DyslexicAwe** [comment]
@brianharvey You're right, I should have used WARP block to speed it up, but I got distracted in the process. 

In the same project there is another script (one that I _really_ wanted to speed up by using WARP, but it turned out I can not), which makes use of the "3D list of costume pixels" (for each "pixel" in the list) to make a short trails (with pendown), creates clones based on row/column combinations at specific positions while "converting" the trails to costumes for the clones and after that animates the clones (independently movable "pixels") for various visual effects -- see [https://snap.berkeley.edu/snapsource/snap.html#present:Username=kinestheticlearning&ProjectName=Table_transposed_KingDavid12](url) 

It seems that the un-_speedup(by WARP)_-ableness of this "trails/clones" script, has in my mind supressed the fact that WARP could still be useful - in the other script - as you pointed out.

**Comment by DyslexicAwe** [comment]
@KingDavid12 Thank you. 

I am curious about how have you converted the small green block, which I nicknamed "valuefication" [here](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/2186#issuecomment-412841345), to the JavaScript equivalent? Do I understand correctly, as shown in image below
```javascript
 (v => v)
```
is how you did it?
![29 08](https://user-images.githubusercontent.com/16387241/44772691-d4381e80-ab6e-11e8-8026-2bb1f6f3bdea.png)

**Comment by KingDavid12** [comment]
@DyslexicAwe (v => v) is in fact the translation of that block. That is because the block is just the identity function. The only reason you would map it over a list is to get a copy. It is not entirely necessary in the javascript version, and that line could be replaced with: 
```javascript
transpose(current_pxls_row).slice()
```

**Comment by KingDavid12** [comment]
@brianharvey You are correct about the warp block, but sometimes warp isn't enough. Over my time of using Snap!, I have discovered places where warp simply doesn't work, but a few custom javascript blocks can do a lot in terms of performance. For instance, the easy way to write one of those spaceship games where the ship can move about, rotate, and shoot, is to make all the shots clones of one original shot. The major problem with this is that looping over the list of shots to update them can become very slow very quickly. Adding warp into the system only makes it worse, as now Snap isn't updating the rest of the program very often. The only intermediate solution I have come across, is to write custom versions of the foreach and repeat blocks in Javascript, ones that instead of running one iteration at a time, que a number of iterations. Just swapping out foreach can change the time for looping over a list of 100,000,000 items from 60+ seconds to 3 seconds.

**Comment by DyslexicAwe** [comment]
@KingDavid12 Talking about the clones, would you please share a link to any of your projects that use the costume Javascript blocks, maybe I could learn something from it to make my project(s) faster.

**Comment by KingDavid12** [comment]
@DyslexicAwe I don't have a Snap cloud account, and unfortunately do not have any projects using the libraries. This is because I mostly wrote the libraries for use by people I know. That, and I enjoy writing libraries more than I enjoy writing projects.

I am not sure that the costume blocks will be much help in speeding up a project, but I do have some blocks that could help.

Here's a library that has Javascript versions of some of the tool blocks: 
[Tools [Compiled].zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2332658/Tools.Compiled.zip)
One of the things to watch out for with that library, is that it ques all the iterations simultaneously. So if you have a list of 1,000 items, the foreach block will add 1000 items to Snap's que.
The "Tools [Compiled]" library also includes some Javascriptified (just made that up) blocks.

If you are interested in the list blocks, then take a look at the "Bigger Data" library. Past that, all I can offer in terms of advice, is write replacements for the built in tools library. The tools library often prefers style over speed. For instance the tools library includes a very functional approach to writing the map block: it uses the cons operator (in front of) to build the result as a linked list. If you rewrite the map block to use a simple imperative foreach loop, where you added each item to the list using "add () to ()", you will find the map block much faster than before.

The project that showed me a number of issues with clones and trying to perform an action for each one of them, actually belongs to someone else, and therefore, I do not currently have permission to post it.

**Comment by jmoenig** [comment]
The upcoming Snap5 release now has primitives to let you query both costume dimensions as well as the actual sprite bounding box. Closing. Thanks!

**Comment by DyslexicAwe** [comment]
@jmoenig As I would not be able to make [this](https://forum.snap.berkeley.edu/t/how-to-use-map-block-to-make-letters-or-other-parts-of-a-costume-transparent/957) project without using the following blocks, that were created and shared above by KingDavid12 - could you please add them to your (official) pixels library,
![depends on these custom looks blocks](https://user-images.githubusercontent.com/16387241/66397535-520a6280-e9dc-11e9-884a-ee63bf6c54b1.png)
![please add to your pixels library](https://user-images.githubusercontent.com/16387241/66398506-2b4d2b80-e9de-11e9-80a2-499504b42fcb.png)

**Comment by jmoenig** [comment]
Great Project, thank you!
I think you can totally make that project without those blocks now, even easier than using the old blocks from the former Pixels library. Let me look into it....

**Comment by jmoenig** [comment]
... in fact, @DyslexicAwe here's a version of your project I've just edited now, that only uses the new Snap5 primitives: https://snap.berkeley.edu/project?user=jens&project=Media_Map_Transparency_edited_by_jens

**Comment by KingDavid12** [comment]
It's great to hear that hacky javascript blocks are no longer required to achieve those kinds of things.
