### ISSUE TITLE
repeat until stops sooner than I expected

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap#2226]
I have a question about the performance of a "repeat until" loop in the project whose link is below.

In class I clicked the "repeat until" script, enclosed in a red rectangle in the first png attached.  As you can see the x position ended at 200 rather than the 201 I expected. 

After class I clicked the same script again and the loop ended with 201 as shown in the second png attached.

Could it be that in the first run the x position got to a very small amount over 200 and the loop stopped?  I must admit we are changing the x position a lot in the block "plot a point" - we wiggle the pen via move to make our point on the stage.

[https://snap.berkeley.edu/snapsource/snap.html#present:Username=jcaldw737x&ProjectName=156%2010-09%20Continue%20plotting%20our%20first%20function](https://snap.berkeley.edu/snapsource/snap.html#present:Username=jcaldw737x&ProjectName=156%2010-09%20Continue%20plotting%20our%20first%20function)

![10-09 repeat until ended strangely](https://user-images.githubusercontent.com/5361659/46775222-efe52780-cccb-11e8-8022-ec3cc1c3190a.PNG)

![10-09 repeat until ended as expected](https://user-images.githubusercontent.com/5361659/46775239-025f6100-cccc-11e8-8482-f1f60cd6ea4a.PNG)

**Comment by jcaldw737** [comment]
You may well know this, but just in case.  After I posted this issue I checked the enclosed link by clicking it.  I did not get to the SNAP project in question.  However, when I copied the link and pasted it into my browser, the project did come up.

**Comment by jmoenig** [comment]
Hmm... I can't reproduce this, when I try your project it always stops at x=201. I also experimented with different scalings of the stage, but got consistent and right behavior.
(I also edited your comment and fixed the url, so it now should actually take your to the project)

**Comment by jguille2** [comment]
Hi @jcaldw737 ,

The problem is sure with _rounding_ and with _non-integer numbers_.

If you see, in your second sample, `y=401`. So, in the last iteration, _x_ was initialy 200 (not greater than 200), and so,after `x=x+1`, the final value is 201.

In the first sample, `y=399.000000001`. This is a rounded value, but in any case, is a number greater than 399. So, the _x_ value is also greater than 199, and after the `x=x+1' the value is not 200: is greater than 200. And then, the last iteration is not done.

So, the behavior is right. The question is why the value is not an integer. I guess you introduce a change in the variable value in any place of the project. This "long" values (9.00000000001) are a common problem in Snap (and all the javascript environments) because we have not real integers and floatPoint numbers have these issues ("[denormal numbers](https://en.wikipedia.org/wiki/Denormal_number)").

Easy conclusion:
-Be sure you are not introducing anywhere a change in the _position values_ The watchers are rounded... and maybe you see 200 and the real value is 200.0000000000000000001 (or 199.9999999999998). When you want integers, introducing decimals or divisions cause problems.

-To avoid these problems, take care on the conditions, or use the `round` block to be sure you are evaluating what you want.

Joan
