### ISSUE TITLE
Booleans in "when" hat block should be able to pass upvars to script

### ISSUE THREAD

**Issue by rdococ** [jmoenig/Snap#2249]
![when <I collide with (sprite)>
say (sprite) for (2) secs](https://user-images.githubusercontent.com/3169568/48168853-f2499a00-e2e8-11e8-9d08-e0b069df56ed.png)

Ideally, the upvars in the boolean should be accessible to the script. This would allow "when" hats with booleans such as "I collide with" to pass data to their scripts, as shown above.

**Comment by brianharvey** [comment]
Okay, people have been asking for the ability to define their own hat blocks, and I've been saying that the generic hat block solves the problem, but you have a use case that's still problematic.

Your script has an obvious-to-users meaning, and it would be nice to find a way to support it.  The trouble is that the SAY block is not being run within the scope in which the upvar is created.  (@Jens: Even hybrid scope wouldn't do what xe wants, would it?  By the time we get to the SAY, the predicate block has finished and is no longer on the dynamic stack.)

I can't offhand think of a way to make this work that wouldn't be a horrible kludge.  But I'll think more about it.

**Comment by jmoenig** [comment]
yes, Brian, I agree about your analysis.
@rdococ you can accompolish what you want by using Snap's somewhat secret "send" functionality, where you broadcast a message to a single sprite using a list of two items inside broadcast, the first item being the event name, and the second the receiver (either the sprite itself or its name).

**Comment by jmoenig** [comment]
I agree that this should work.
Investigating...

**Comment by jmoenig** [comment]
I have to admit, this is a fascinating idea, @rdococ !

**Comment by jmoenig** [comment]
So, this is really awesome. I'm very happy that we can now - also due to the new HOF primitives in Snap5 - do you exact use case example, @rdococ 

https://snap.berkeley.edu/snapsource/dev#present:Username=jens&ProjectName=Generic%20Hat%20Blocks%20with%20Upvars&editMode

<img width="605" alt="When_upvar" src="https://user-images.githubusercontent.com/2596285/58797268-da789100-85ff-11e9-866d-9499e109db58.png">

Thanks for this great suggestions, and also thank you, @cycomachead for insisting that this is, indeed, a great idea!

**Comment by jmoenig** [comment]
Okay, we can make ```I collide with```  smaller:

![Generic Hat Blocks with Upvars script pic](https://user-images.githubusercontent.com/2596285/58803301-6219cc00-860f-11e9-98a0-b2c2339d83ca.png)
