### ISSUE TITLE
Sample program ballon pop does not work

### ISSUE THREAD

**Issue by normanbauer** [jmoenig/Snap#2262]
In the file https://snap.berkeley.edu/SnapExamples.pdf, there is a cute little program:

Balloon Pop
(playable game by Cheddargirl from Scratch)
http://snap.berkeley.edu/snapsource/
snap.html#present:Username=jens&ProjectName=Balloon%20Pop

It  has a little problem, it does not work.  It a victim of the asymmetric touching syndrome. The needle to pop the balloons is hidden.  When a balloon checks for touching the needle which is hidden, it fails and the balloon does not pop. The needle has to be shown to trigger the touching.  Since the needle is offset from the floating girl's hand (which could be fixed to be more accurate), I fixed it by showing the needle and setting ghost effect to 100. The same problem is experienced by the balloon supporting the girl and can be fixed the same way. Please fix or I shall have to report this to the me-too movement and you don't want that. Imagine Berkeley flooded with pussy hats.

**Comment by jguille2** [comment]
Hi!

Yes, that example must be fixed, because Snap! changed this behavior (using the ghost effect, or maybe better putting these sprites (visible) in the right place (overlapping the "CG" sprite over the right place (needle and balloon))

You can see past discussions on #233, #472 and #479 (this past two issues can be closed). And "detecting collision with hidden sprites" was disabled on [April 12, 2018](https://github.com/jmoenig/Snap/commit/b432da2dfe32d1715c56415bc07ce354d12cdf93).

Thanks,

Joan

**Comment by jmoenig** [comment]
Okay, thanks, @normanbauer !
I've just now updated that project so it works with the new behvior.
Cheers, and thanks!
