### ISSUE TITLE
Inconsistent behaviour related to block variables in custom blocks.

### ISSUE THREAD

**Issue by DavidGasku** [jmoenig/Snap#2274]
Hi, I've encountered an inconsistency in block variables. I use this "first time ()" block, that only is true when some property goes from false to true, using an internal block variable.
![bug first time block script pic](https://user-images.githubusercontent.com/5382201/49297198-7f33dd80-f4ba-11e8-828d-0a16f8b12eee.png)

Check the following project. The counter increases twice per 'a' press, as expected.

https://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=lanuzamakers&ProjectName=bug%20first%20time%20block

But only fires once when the block is encapsulated in another block ('b' key), as if they are accesing the same block.

**Comment by jguille2** [comment]
Hi @DavidGasku ,

I think this _block variables_ feature is under construction... and Jens can explain the aim of that... but  what I see is clear:
+ _block vars_ are living inside each instance of a block
+ So, your two _first time_ blocks have their own _lastState_ variable. Then, each block remember its own last state. And you have these two increases.
+ Your _encapsulated first time_ block calls the _first time_ block. But all the instances of that _encapsulated first time_ block use the same _first time_ instance. That instance is created by the prototype. I you create other blocks, all those blocks will use the same instance.
+ So, you have only one "last State" for all your _encapsulated first time_ blocks. And then, only the first realizes the "state change".

Joan

**Comment by DavidGasku** [comment]
Yes, that's the problem. The program should be the same "folded" than "unfolded". Encapsulating shouldn't change the output. So each outer block should have it's own copy of the inner block.

**Comment by brianharvey** [comment]
This whole feature has dubious semantics, and is a kludge Jens invented in a hurry to get around the lack of internal definitions.  Let's not put too much effort into it...

**Comment by jmoenig** [comment]
Objection! Block vars are neither under construction nor were they designed in a hurry to make up for anything else. They are a somewhat hidden intellectual gem in Snap! that opens the door to a completely different way of thinking about blocks. I made block vars as an alternative for creating reactive code. Joan's explanation is perfectly correct: Block vars are really block *instance* vars. If you use a block with block *instance* vars inside another block's *definition* it's the same *instance*. The beauty of block vars is that is lets you create scripts that are themselves computational *objects* rather than *expressions*, more like sodering actual circuits onto a board. It's a quasi-physical feature. Thus, there is absolutely no inconsistency here, it's behaving exactly as it should: Each block *instance* goes its own way.

**Comment by brianharvey** [comment]
Hmm, sorry, I thought I remembered you starting to have second thoughts about them last time we talked.  I still maintain that the semantics are cloudy.  For example, what happens if you right-click-duplicate a script that calls a block with block vars?  I'm sure there's a consistent answer to that question, but as a user, it's not at all obvious to me what the answer should be.  What if you drag the script onto a different sprite?  The notion of a "block instance" just doesn't line up with any meaning-bearing idea for me.

And, in defense of Joan, if you hover over the "block variables" entry in the context menu of the hat block in a block editor, the hover text is "experimental -- under construction."

Maybe there is some deep idea in this feature that I'm missing.

**Comment by jguille2** [comment]
Yes, I said "under construction" because those "hover texts" (it is also over the "translation" option, on the block editor). Maybe they can be updated, deleting this "under construction" text.

Anyway, as Jens said, I think this feature "has absolutely no inconsistency there". David question if "each outer block should have it's own copy of the inner block", but  we need a really reachable instance to associate these _block variables_. 

Jens talked about "quasi-physical feature" and I think Snap! visual metaphor is brilliantly consistent here: the only way to see the "inner" block is inside the "block editor", and there is only one "block editor" for each custom block. So, the conclusion is easy: only one block and only a set of block variables. Our "visual stepping" also helps to see this feature: all the "outer blocks" use the same "inner block" (the one is inside the block editor).

Ok. I think this issue can be closed.

Joan

**Comment by rdococ** [comment]
> Objection! Block vars are neither under construction nor were they designed in a hurry to make up for anything else. They are a somewhat hidden intellectual gem in Snap! that opens the door to a completely different way of thinking about blocks. I made block vars as an alternative for creating reactive code. Joan's explanation is perfectly correct: Block vars are really block _instance_ vars. If you use a block with block _instance_ vars inside another block's _definition_ it's the same _instance_. The beauty of block vars is that is lets you create scripts that are themselves computational _objects_ rather than _expressions_, more like sodering actual circuits onto a board. It's a quasi-physical feature. Thus, there is absolutely no inconsistency here, it's behaving exactly as it should: Each block _instance_ goes its own way.

Can you explain what you mean by scripts as computational objects, or give some examples? It doesn't make much sense to me at the moment...

**Comment by brianharvey** [comment]
I'd be happier about it if they were _called_ block instance variables.  Even happier if they were called block persistent variables.  That would give users like @rdococ a chance of understanding them!

**Comment by rdococ** [comment]
What uses would blocks as objects have in terms of creating interesting projects?

**Comment by brianharvey** [comment]
Procedures that remember local state are at the heart of object oriented programming.  See chapter 8 of the Snap<i>!</i> manual.  Block _variables_ are just a different notation from the lambda-based one in the manual, except the latter allows for sharing the local state variables among several methods.

A different aspect of procedure as object is using procedures as _data._  See the "vee" project in the Examples collection for an example.
