### ISSUE TITLE
Bug with the pen

### ISSUE THREAD

**Issue by fridolinux** [jmoenig/Snap#2286]
Found a bug:
You can detect something stamped with the pen, through the block **touching _color_ ?**. But if you are in full screen mode, it can not be captured, because it is blurred.
Sorry for grammar mistakes, but I'm from Germany and I don't talk English.

**Comment by jmoenig** [comment]
that's due to how the browser scales images and beyond our control. In general color collision detection is discouraged, better to use collision detection between sprites and with the pen trails layer:

<img width="197" alt="pen trails collision detection" src="https://user-images.githubusercontent.com/2596285/49687472-63a48480-fb03-11e8-9d73-bf67fbdef98e.png">
