### ISSUE TITLE
switch costume works inconsistently clone versus sprite

### ISSUE THREAD

**Issue by normanbauer** [jmoenig/Snap#2298]
I have a program that takes a number (integer) and displays it as a decimal string. I cloned the basic sprite to be a number of digits, with the sprite being cloned having ten costumes named for the integer number it represents ( 1=, 2=2,....9=9,0=0). When I use the switch costume block with the sprite, 0 displays properly. I would guess the underlying code takes the switch sprite argument as the name of the sprite. However, when I use the same method in a clone, the 0 comes out as the turtle ( I guess costume 0).  If I convert a costume number of 0 to 10, things work well (maybe it uses the costume number, not the costume name?). Attached is the XML version of the program with the "kludge" to change the costume number to 10.  Remove the two lines and you will see the error.

https://snap.berkeley.edu/snapsource/snap.html#present:Username=crankings%40aol.com&ProjectName=pc%20digits

**Comment by normanbauer** [comment]
Thanks, that is good information.  I always wondered how it determined how to process arguments. So the join make the argument a string.  I think you mean use one of the arithmetic operators (+, -, *, /) to convert a string to a number.  Very cool, it even works.

**Comment by brianharvey** [comment]
No, 0 is a valid costume number; it just refers to a fixed, built-in costume.  I think the behavior you report (different result in child vs. parent) is a bug, although not at the top of the urgency list.

My guess is that the underlying problem is that Javascript overloads 0 to represent false, the empty list, and so on.  Scratch 1.4 had a similar problem (I haven't checked 2.0 or 3.0) and kids would invent workarounds similar to the one Joan gave you.  Occasionally one of those things pops up in Snap<i>!</i> and we fix them more or less as they're reported.  But I'm guessing without looking at the code.  :)

**Comment by brianharvey** [comment]
P.S.  Jens may disagree with me about 0 being a costume number, because he argues that the turtle isn't a costume, but rather the sprite's unadorned body.  So far the only way this disagreement has affected anything is that I can't convince him to fix the misfeature that "next costume" doesn't work from costume 0.  (We are agreed that "next costume" from the highest-numbered costume should wrap around to costume 1, not costume 0, but I don't see why that rules out a useful response to "next costume" when the turtle is visible.)

**Comment by jguille2** [comment]
Hi @normanbauer ,

I don't understand your last question. For me it's fine.

Number zero, as Brian have said, is the turtle. But you have named the costumes with the numbers... So you want to use the names, not the numbers. Then, if you are using "switch to costume ( join ("my mod") )", you are using the names, and this must be ok for all the cases (also for "0").

**Comment by normanbauer** [comment]
You are correct jg, using the join rectifies the problem for the zero number case. Since numbers 1 through 9 work fine without the join, I suspect Brian is correct in that there is different processing that occurs when the number 0 is passed to the switch costume block. This conjecture  is just the guttural vibe from years of programming experience.

**Comment by jguille2** [comment]
No, the processing is the same in all cases.

Numbers 1 through 9 work fine without the join because number (order) and name are the same. But without the "join" the block is using always the number of the costume (not the name). You can verify this changing the order in the wardrobe. The problem with the 0 is that it is the costume "0" (name) but is the costume 10 (order).

With the "join" all cases are using the string (name) and so, you can change the order inside the wardrobe or add more costumes... and the script keeps running fine.

**Comment by brianharvey** [comment]
So why is the behavior different for clones?

**Comment by normanbauer** [comment]
I wish to withdraw this issue. @jguille2 is correct.  Snap! executes the same for clones and non-clones.  I misinterpreted my output.  As @jguille2 indicated, Snap! does not allow for typing of objects, but it is important for some blocks such as **switch costume** which accepts an id which may be a string or a costume number which has to be a valid positive integer greater than or equal to 0 . (turtle is 0) and less than or equal to  
![costumes](https://user-images.githubusercontent.com/16528654/50549370-94627000-0c10-11e9-82b4-23e0b4081847.jpeg) . If outside of this range, the turtle is presented.   I believe cloning has nothing to do with the processing.  Perhaps a better title would be "Warning turtle costume used when costume number out of range".  I apologize for my lack of research before presenting this issue.

**Comment by brianharvey** [comment]
Ah, glad to hear it.  No problem.
