### ISSUE TITLE
jmoenig and cdglabs, Can you release Snap 5?

### ISSUE THREAD

**Issue by MiroslavRD** [jmoenig/Snap#2305]
@jmoenig @cdglabs **DO NOT IGNORE THIS**

First, i found out that @cycomachead requested email confirmation for signup on #2300.
But i want more updates...

# Update Wishlist:
Ability to zoom GUI (for 4K and 8K monitors)
Better Logo
Fix a ton lot of glitches and optimize a ton lot of lags
All options except Turbo Mode are enabled by default
Remake most Scratch features
A "Language Detector" that sets Snap!'s language to your browser's language by default (You can still choose other languages in Gear icon > Language.)
More stage size presets (480x270 will become default stage size) ([check this link for all the aspect ratios we need,](https://en.wikipedia.org/wiki/Display_aspect_ratio) [and check this link to calculate 480x360 in other aspect ratios](https://calculateaspectratio.com/))
And more...

**Comment by cycomachead** [comment]
Hey, 

Thanks for the feedback, but at the moment we're not calling things "Snap! 5" -- we are however making regular and sometimes large improvements to Snap<em>!</em>.

It's also best to make 1 issue per feature request on GitHub. Otherwise, it's hard to track work. 
Also, we're definitely interested in the enhancements you mention (like language detection), but the others (like "optimize lag") are nearly impossible to implement without more information. Feel free to clarify or share example projects.



> Ability to zoom GUI (for 4K and 8K monitors)

BTW, you can adjust this by editing your browser font size or using the zoom page function.

**Comment by Axis-Denied** [comment]
I'm just hoping for an improvement on the performance impact of sprite-based color detection.
I have to run my project in a tiny screen for now...
