### ISSUE TITLE
Minor: Is _ a number? reports TRUE for space (shouldn't, though)

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap#2332]
subject says it all

**Comment by joker314** [comment]
I have no experience with this sort of thing, but intuitively: you can use a space in every context where you can use the number "0", so maybe they are just different representations of the same number? And so I think maybe the current behaviour is okay.

I would also petition that < "NaN" is a "number" > should be true, or at least < (0 / 0) is a "number" > be true, because division outputs numbers, and lots of programming languages have this behaviour also.

**Comment by brianharvey** [comment]
The "or at least" part isn't any easier than the "NaN" part.  Snap<i>!</i> is an applicative-order language, which means that the 0/0 has been evaluated before the IS A block.  The latter doesn't know anything about the expression that produced the input.

I have mixed feelings about this.  "NaN" stands for "Not a Number," so it seems perverse to say that it _is_ a number!  I think that in a situation in which a value might be NaN, you should check for that explicitly before you check its type.

The original problem about space is a misfeature, because the space is treated as zero by arithmetic operators.  (I think that's a misfeature too, but that's a long argument.)

**Comment by jmoenig** [comment]
Sigh. This is, of course, easy to "fix", albeit at the cost of introducing a special case for a bunch of certain characters - actually a whole lot of them - that needs to be performed whenever *any* type check happens, e.g. for asserting that an input is a list where a primitive expects one.

Yeah, I know, y'all are gonna suggest some funky regex, but can we please let this be? It's one of the cases where JavaScript bites us but the "fix" slows down a lot of other operations down the lane.

Peace?

**Comment by ddgarcia** [comment]
Space is not a number, even if it's treated as zero by arithmetic operators.
NaN by its very name is not.
±Infinity is.
I believe the only things that should be true are ±Infinity or [0-9]+

**Comment by brianharvey** [comment]
No, Dan, some strings with E in them are numbers, too.

Jens, I don't see why fixing the IS __ A __ ? block entails type checks everywhere.  The truth is, the boundary between numbers and text strings is deliberately porous, so elsewhere it's okay if you can apply an arithmetic operator to a space.  (I've proposed changing that, but that's a separate issue.)  The current discussion is just about this specific block, and what it should report for things that are primarily strings but accepted as numbers too.  And in this block I think the extra check is warranted.  Strings of spaces should consider themselves to be text (including the empty string).

**Comment by ddgarcia** [comment]
Ah, yes, good call Brian. 1E6 + 1 works nicely (but only if 1E6 is wrapped in a join or identity block), so I'm wondering if it makes sense to remove the restriction on E in the numeric round input?

**Comment by jmoenig** [comment]
Brian, if you did look at the code you'd know :-)

We have a type system in place where we make sure that every datum fits exactly one type. We use that type check whenever we test for ... types, such as asserting something is a list. The code is such that every special case needs to be tested for first. So, yes, I guess we could cut some corners for some other special cases, but I don't want to do that for obvious reasons (those corner will come back to haunt us with a vengeance).

Guys, we've had this issue before. Some professor dudes made me introduce all kinds of special cases for our equality testing code, and those special cases keep popping up in every single performance log. It's such that Snap's equality testing is one of the main reasons why a lot of operations are way slower than they would otherwise be. I really, really, don't want to slow things further down for the sake of hairsplitting.

**Comment by ddgarcia** [comment]
I wonder if there's configuration option that can offer performance speed wins at the cost of equality testing not doing some things. We have "thread safe scripts", I wonder whether the "equality-test safe scripts (makes things slower)" can be an option that most users would leave unchecked if they knew they'd get a huge speed win.

**Comment by brianharvey** [comment]
No, Jens, that's a _different_ issue.  I understand why you're against strict domain checking in input slots.  But when someone explicitly asks for the type of something, that's a separate question.  We can do infinitely detailed and slow checking just in this one block, without in any way changing the behavior of the rest of the language.  If _this block only_ has to check explicitly for strings of spaces, so be it!

**Comment by jmoenig** [comment]
Yeah, sure. But see, whenever we introduce these modes things become less apparent, not just for students, but also for teachers trying to help students. 

Listen, I am going to introduce a fix. But with a heavy heart. It's super easy to find edge cases of falsey and "nullsy" stuff that does weird things under contrived conditions. It's the stuff people like Shriram can endlessly gloat about....

... okay, just reading your comment Brian ....

Oh, why are you so not understanding how code works? When we check for types we ... check for types, regardless where this happens, whether "just" in this block or in input slots. Software works by calling functions, remember?

I'm getting really frustrated by discussions such as these. As I've said, there are probably zillions of edge cases you'll come up when you look for them. Every single one ends up requiring a special case. And, of course, every single one feels super important once you've come across it.

Screw it. I'm doing the change. My computer is fast enough. I'm really sorry for those kids who are using slow, underpowered Chromebooks, because they will end up preferring Scratch.

**Comment by brianharvey** [comment]
> Oh, why are you so not understanding how code works?

Hmpf.  What I understand about code is that if an abstraction (such as abstracting type checking into a procedure) doesn't do the right job in one particular case, you can write that one particular case not to use the abstraction, but to use its own algorithm instead.  No?

I'm sorry you're upset, but ad hominem attacks don't help.

**Comment by brianharvey** [comment]
P.S.   This bug report originated with a _kid_, forwarded to us by his teacher on Piazza.  So talking about professors isn't responsive either.
