### ISSUE TITLE
Issue Regarding the Use of Mathematical Applications

### ISSUE THREAD

**Issue by Studentm76** [jmoenig/Snap#2342]
Hi so recently I have been coding something for a project on Snap! I believe I have run into a glitch when running the program. In the video: https://youtu.be/ijCqiI0SFLA I am buying something from the custom shop I made. The current item I am buying would be 1 ice which costs .21. The money variable is set to the number 90. As shown in the video for a while Snap correctly subtracts .21 each time I hit the 1 button. However at the 3rd time I am presented with a number that doesn't make sense for it has more then 4 digits. I am curious if there is any problems with my code or Snap, and thank you very much for looking into the issue.

**Comment by brianharvey** [comment]
No, this problem would come up in any language.  It's one of the annoyances of floating point (non-integer) numbers in a computer.  Since there are only a finite number of representable numbers, and the real numbers (or even the rational numbers) are dense (in between any two numbers there are infinitely more numbers), it follows that _almost all numbers_ cannot be represented exactly.

The solution to this problem is to represent money in cents, not dollars, inside your program.  You can still show the values to the user as dollars by multiplying or dividing by 100 (rounding, if you multiply) when needed.
