### ISSUE TITLE
My SNAP project doesn't work with Lego Wedo sensors

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap#2364]
Thanks to a lot of help my SNAP project below works fine with Lego Wedo motors, but both the distance sensor and the tilt senor show blanks when clicked even tho they are attached.  We are using the USB version of Lego Wedo

[http://extensions.snap.berkeley.edu/snap.html#present:Username=rre2019b&ProjectName=ezSNAP2019_LEGO](url)

**Comment by jguille2** [comment]
Hi @jcaldw737,
I guess you've noted the blocks of the other project [http://extensions.snap.berkeley.edu/snap.html#present:Username=jguille2&ProjectName=wedo1](http://extensions.snap.berkeley.edu/snap.html#present:Username=jguille2&ProjectName=wedo1) are different.
Test both projects... and maybe you will find the answer.

I didn't test it yesterday because I had not any Wedo1, and also, Wedo1 is not running over Linux64.

Today I will try to test it... and will report my feedback.

Joan

**Comment by jguille2** [comment]
Hi @jcaldw737 ,

I've tested last project with Wedo1.0 (running S2Bot 0.8.6 chrome app) and all run OK. I've tested a motor and tilt and distance sensors. We can run only two modules at the same time.
The S2Bot window show the info about these two modules (module name and current state/value). So, before solving problems about Snap! blocks, be sure Wedo control is fine from S2bot.

Joan

**Comment by jcaldw737** [comment]
Maybe I am not using the sensors correctly.  Is there more to do than plugging them in and clicking on the appropriate block and looking to see what is in their "bubble" ?

Btw, I don't see any sensor blocks in

[http://extensions.snap.berkeley.edu/snap.html#present:Username=jguille2&ProjectName=wedo1](url)

Are you saying that the sensor blocks in the following project work for you?

[http://extensions.snap.berkeley.edu/snap.html#present:Username=rre2019b&ProjectName=ezSNAP2019_LEGO](url)

**Comment by jcaldw737** [comment]
Btw, The motor blocks in your project work fine on my laptop.

**Comment by jguille2** [comment]
Motor blocks are on the _Motion_ category, and sensor blocks on the _Sensing_ one. Those are the blocks you have to test.

**Comment by jcaldw737** [comment]
The sensors and motor blocks in the project below work just fine!

Thank you very much!

This issue is CLOSED!

[http://extensions.snap.berkeley.edu/snap.html#present:Username=jguille2&ProjectName=wedo1](url)
