### ISSUE TITLE
Why does the camera display like a mirror but not save costume as such?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2365]
E.g.

![image](https://user-images.githubusercontent.com/2138696/55057485-47bdf200-50a4-11e9-9751-8c08ea2e42bb.png)

I'm not sure which is better but shouldn't it be consistent?

**Comment by brianharvey** [comment]
Short answer:  Because that's how Scratch does it.

Longer answer:  It's all about people's expectations.  When you look at yourself in a mirror, which is essentially what you're doing before taking the picture, you expect to see yourself one way.  When you look at a photo of yourself, you expect the other way.

**Comment by ToonTalk** [comment]
My guess is that anyone who has ever taken a selfie on a phone expects the photo to be mirrored. (At least that is what Android does.)

I guess it is too late to change this.

So if one wants to flip a costume horizontally they must save the costume and then edit it to flip it?

**Comment by bromagosa** [comment]
> So if one wants to flip a costume horizontally they must save the costume and then edit it to flip it?

That'd be one way, yep.

It's not too late to add a "flip" control to the camera dialog, but we've got quite a lot of much more urgent work to do at the moment...

**Comment by jguille2** [comment]
Hi @ToonTalk 
As Bernat have said, maybe this is not the right moment... but also, I want to comment that maybe the right moment will be when we implement VideoMotion blocks, because with them, there are the options of flipping, transparency... of the camera images.

Current behavior is like Hangouts or Skype. You see your mirror image, but other people see your real image (not flipped). I think this is a right behavior when you see yourself (like a mirror) but if the webcam is pointing to an object, nonFlipped images will be better.

In the meantime, I share a workaround I use when the webcam points to an object (for example, an Arduino board :smile: ). Inside "Other" category, you have a "hack block" (you must click it once) and, after this, the toggle block changes the flipped behavior. Camshots are always the same (like now, the real image) and you can change the Camview (flipped or real).

https://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=jguille2&ProjectName=cameraFlipping

Joan

**Comment by cycomachead** [comment]
> My guess is that anyone who has ever taken a selfie on a phone expects the photo to be mirrored. (At least that is what Android does.)

iOS, for what it's worth, does the exact opposite. The live view is mirrored and then saved image is not. 

I agree with Joan, though.

**Comment by jmoenig** [comment]
Closing this, because we now do have video sensing blocks that let you take mirrored snaps. Thanks!
