### ISSUE TITLE
Slider in Zoom blocks shouldn't go so high

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2373]
I think 5 is plenty, but ask Michael.  (You should still be able to type in bigger numbers.)

**Comment by cycomachead** [comment]
makes sense.

**Comment by brianharvey** [comment]
But, what should the upper limit be?  I'm voting for 5, or even 4, but Mary says people who are nearly blind magnify text way more than that, maybe more than 10.

**Comment by jmoenig** [comment]
I'm going to take "zoom blocks" out, because y'all are using it the wrong way. I made "zoom blocks" for one single purpose: So Dan can export high-res pics of blocks and scripts to print them on posters.

If you are presenting or visually impaired you want *everything* to be bigger, not just the blocks. This you can accomplish by zooming your browser. For my own presentations and video screencasts I'm usually using a zoom of 150%. Then you *reload* Snap! once to get the full graphics resolution, and then you always have that zoom level when you open Snap!.

Your browser's zoom setting is Snap's zoom setting, because Snap! is a web app.

**Comment by brianharvey** [comment]
No, I don't agree.  It's not possible for _everything_ to be bigger!  The physical screen is only as big as it is.
<img width="1176" alt="Google Chrome002" src="https://user-images.githubusercontent.com/3885074/55857404-ee34d900-5b21-11e9-8c45-a3026cc9f6bc.png">
Huge stage.   Huge palette.  Tiny scripting area.  Green flag, pause, and stop lost off the right end of the window.  Also, I didn't capture the entire screen, but the sprite corral is lost at the bottom, and I can't quite scroll to the "make a block" button at the bottom of the palette.  This is at zoom 150%.

I really love zoom blocks.  It does just what I need.

**Comment by jmoenig** [comment]
that's not how it looks even on the tiny screen of my 11" MacBook Air. It's okay if you like zoom blocks, just please don't use it for your presentations of screencasts, because it'll make other elements *smaller* for your audience and distort the proportions of widgets like the make-a-block dialog.

Hey, I don't get it. For years y'all have been urging me to make it so *everything* scales evenly (https://github.com/jmoenig/Snap/issues/865 https://github.com/jmoenig/Snap/issues/431 https://github.com/jmoenig/Snap/issues/335 https://github.com/jmoenig/Snap/issues/28) and now that we actually have that you don't want to use it.

**Comment by brianharvey** [comment]
I can't speak for anyone else, but what I wanted was for widgets (most especially the make-a-block one) to scale, but keep the large screen areas (stage, sprite corral, palette, all those) fixed.  In fact, I don't see any need for anything that's on the stage (esp. costumes) to scale -- they're big enough already.

**Comment by cycomachead** [comment]
NO. 

Seriously, I hate that you two shout, but I'm going to start participating.... 

**SOME** people who are visually impaired want everything bigger...**SOME** want just text to bigger. Some have other visual impairments where text size doesn't matter but color and contrast do.

For one thing, text is _fundamentally_ different than UI. Glyphs are more detailed. It's important to read most or all of the text in blocks because that's the part that makes it unique. UI elements are unique based on their location, colors, shapes, etc. You (generally) have many more affordances there that makes text different. 

Every browser has an option that treats zooming text are different from general page zoom. Users toggle between them. Most browsers have "reader" modes because text and UI are not the same thing. Applications have font size settings because text and UI are not the same thing. 

Zooming the entire UI is definitely appropriately in some cases -- though it's not perfect either. You lose usable space. Sometimes it's worth it.


--- 

As far as the actual issue: The current limit is 12, and that seems fine to me. Beyond about 5 Snap<em>!</em> becomes unusable due to scrolling. 

(And Snap<em>!</em> is not a normal webpage and we should stop pretending that is one.)

**Comment by cycomachead** [comment]
> everything

None of those are reports are for zooming "*everything*." Zoom blocks doesn't make other things smaller, it just doesn't make some things bigger. In fact, despite a couple oddities with the make a block dialog, it is _very_ accurately named.

**Comment by cycomachead** [comment]
And for the love God, would people stop saying with others with disabilities need. It's really infuriating and insulting.

**Comment by jmoenig** [comment]
Sorry, Michael, not to insult anyone, especially not *you*! Zoom blocks has been the single most complained about feature in Snap, which bewilders me. I'm ready to set the damn zoom limit to 5, but I really, really, honestly do not understand any of this discussion. People have different display resolutions and wildly different display sizes, and printers, too, have a huge range of resolutions. For actual printing I've needed the 12x zoom a lot myself.
But hell, yeah, let's all vote.
