### ISSUE TITLE
SET dropdown should take variable block input

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2453]
As Brian knows, I regularly try to drop variables into the dropdown input slot of the SET block only to have to drop them back in the palette and then click the dropdown. 

I figured it was just me, but I just watched another experienced Snap user do it. Is there any way to make that slot accept block inputs?

**Comment by brianharvey** [comment]
This has been a contentious issue for a while.  In BYOB you could drag an expression (not just a variable blob, but including those) onto the first input slot, and what it meant was that _the value of the expression_ had to be the name of the variable to set.  It's a neat feature, but not strictly necessary.  And it confused people, who expected dragging a variable onto the first input meant to set that variable, not to set the variable whose name was the value of this one.  So we decided to avoid the confusion by just not accepting drops onto that slot.

Of course we could make SET (and CHANGE) a special case, that would accept only variables, not general expressions, dropped on them, and wouldn't evaluate the variable.  There's the minor problem of what to do if you drag a variable that's out of scope onto that slot, but that's not the heart of it; the real problem is that we don't like special cases, which make it hard for people to learn the general evaluation rule.

On the third hand, now that we have unevaluated input types in custom blocks, it wouldn't be quite so much of a special case now.

The really right solution would be to treat expressions dropped on that slot the way BYOB did, and to let you drop a _ringed_ variable to get the behavior you want.  It's the right thing because what a ring means is not to evaluate what's inside the ring.  But that would confuse people worse than not having it at all.

But, we've gone all this time without the indirect addressing feature (the one where you give an expression that names the variable to set), so we wouldn't lose anything if we did what you want.  It'd be a kludge, but users would love it.  Jens?

**Comment by jmoenig** [comment]
You cannot assign a value to an expression. A variable "blob" is not "a variable" but an expression reporting the value of a variable, not a handle to the variable itself (which nobody would understand anyway).

Think of a reporter as being trailed by ... OMG I'm not saying this ... parentheses in a language like, say, Python:

```foo()```

as in:

```print(foo())```

and now tell me that what these teachers want:

```foo() = 42```

is something that we should strive to enable. Nobody would argue for that, right?

This is a great example of how being "intuitive" is not "right". In fact, often, if not most of the time the "intuitive" conception is a misconception. That's what this whole education / constructionism / pedagogy thing really is about, isn't it?

A block is *not* colored text with a funny box around it. Blocks are elements of a programming language. I always tell "my" teachers that we have several kinds of blocks:

* commands *do* something. They are also known as *statements*
* reporters *return* something. They are also known as *expressions*
* hat blocks ...

Alan always used to tell stories of how our intuition is mostly wrong about almost everything, and he always used optical illusions to make his point. And - for once - this convinced me.

Teachers, of all persons, should be willing to learn. This is *not* an issue of *design* at all, but one of understanding Mathematics.

**Comment by brianharvey** [comment]
Oh, I know all that!  That's why I said the really right thing would be to require a ring around the variable.  But we have, from time to time, made allowances for users' actual needs and expectations.  For example, let's take sprite inheritance.  You and I agreed, at one of our f2f design discussions, that a new clone would inherit _everything,_ so that users would have a clear model to understand.  And then you started doing projects and decided that certain things had to not be inherited by default, to match users' expectations, notably sprite-local variables.  I was shocked to discover that (the manual is probably still wrong because I don't have a clear understanding of what is and isn't inherited) when running the actual software!  But you were right, because of the common use of clone index variables--something I use myself.  Another example is that variables in the CALL and RUN rings are automatically unringed.  That's a kludgy special case, and users _could_ just always do it themselves, but it's still the right thing.

So I think it's possible to discuss whether this should be one of those cases.

Users of those other languages all seem to understand that you can't say x+y←3.

P.S.  In my idiolect, a "reporter" is one block, whereas an "expression" is a reporter with its inputs filled, perhaps with other reporters, or a constant expression, which isn't a block at all.  Similarly, a "command" is one block, whereas an "instruction" (no particular reason I don't use "statement" except that that always reminds me of BASIC) is a command with its inputs filled in.

**Comment by Jonathan50** [comment]
Since SET is a special form, I don't think it really make more sense to drop an expression whose value is a procedure whose text is a variable reporter into SET than it does to drop a variable reporter into SET. Also, Common Lisp has a special form, SETF, which lets you write things like
```cl
(setf (car pair) 'foo)
```

**Comment by brianharvey** [comment]
I don't think of SET as a special form.  Dropdown inputs generally represent objects, at least internally; for example, the first input to TELL represents a sprite, not the name of a sprite (although yes, Snap<i>!</i> has to look up the name to find the sprite).

Imagine the old BYOB behavior, in which you can drop a general expression onto the first input of SET, and the value of the expression is taken as the variable to set.  Often the expression would be something like JOIN prefix (numeric variable) to get variables FOO23 and so on.  In that context it would make perfect sense to ringify a variable, which would mean what it always means, namely, don't evaluate this, but instead thunk it by attaching the current environment to it.  Then SET would look up the ringed variable in the attached environment, and get a variable object to set.

But even though that's a totally consistent way to handle dropped expressions, I'm not recommending it.  What I'm recommending is to *make* set a special form, not evaluating its first input.  That's what the users want.
