### ISSUE TITLE
Upvar does not seem to work with recursion

### ISSUE THREAD

**Issue by ge-ko** [jmoenig/Snap#2489]
The following program:
![image](https://user-images.githubusercontent.com/991964/64834990-f1f6eb00-d5ec-11e9-9803-0901e4982227.png)
outputs:
inside 5
outside 5
inside 3
outside 5
inside 8
outside 5
inside 1
outside 5

**Comment by ge-ko** [comment]
Thanks, Brian. I did change UNLESS and CDR but the result is still the same.
![image](https://user-images.githubusercontent.com/991964/64855878-7e270380-d629-11e9-9029-73942c099c35.png)
The only remaining operations with side effects are "SAY" and "SET item to CAR(list)". I cannot think of how to change the later as item is upvar and I need to set it. What is strange is that the "inside" SAY sees the side effect on item but the "outside" SAY does not see it.

**Comment by ge-ko** [comment]
Just for reference, the pure functional version works fine:
![image](https://user-images.githubusercontent.com/991964/64857904-8df51680-d62e-11e9-9f35-edf55a2be424.png)

I was wondering why "item" upvar is not captured by ref from the "do" lambda.

**Comment by towerofnix** [comment]
>I was wondering why "item" upvar is not captured by ref from the "do" lambda.

Right, since you're passing the same lambda (the one with "say") into the sub-call of "for each", you'd think the blank slot would (in "join") would always refer to the value that script is called with...

Obviously I'm not sure :P but this seems like a bug to me. Maybe this is just a workaround, but would doing "for each (cdr (list)) { run (do) with inputs [(empty)] }" (instead of just passing "do" directly in) work?

**Comment by brianharvey** [comment]
Serves me right for not actually running your code -- although you should post a project URL.

This isn't exactly a bug, although it's confusing and I agree it'd be better if it worked.  Here's why it doesn't do what you want:

First, forget about upvars and think about a simple recursive function with an input FOO.  Each recursive call creates a new local variable FOO.  The calling procedure might still need its own FOO, so we can't just reuse the original variable.

Now imagine that this input is an upvar.  When the outer script calls the procedure, the outer name is bound to the same variable as the inner name.  That outer script doesn't know that the procedure made a recursive call.  The outer name is still bound to the same variable as always.

Now, it happens that in your code, the recursive call is a tail call (although it'd be really hard for us to figure that out, because the recursive call actually happens from inside another procedure, UNLESS) and so in principle we could get away with reusing the same variable.  But I'm not sure we'd want tail calls to have a different semantics from embedded calls.  (As opposed to tail calls just quietly running faster than embedded.)

Saying all this differently, an upvar is the called procedure giving you access to its internal variable.  It creates a _new_ binding in the caller's frame, separate from the caller's own variable.

You could imagine that if you called a procedure with an upvar, and you already had a variable by that name in your environment...  No, that wouldn't work.  The whole thing with upvars is that the outer name and the inner name are bound to _the same variable_ -- the same memory location.  If you imagined having two variables but linking them, then every assignment would have to set two locations in memory, which is too horrible to contemplate.

So, sorry, this is the speficied behavior, even though it's confusing.  (It confused me!)

**Comment by rdococ** [comment]
This is why I'm not quite certain on upvars - it's difficult to do recursion with them. Maybe there should be some way to *explicitly* say "I don't want to create a new upvar, I want to reuse this existing variable as the upvar"?
