### ISSUE TITLE
Can't open costumes dialog (from Piazza)  Chrome 76 and newer

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2491]
File....costume doesn't open

When the student tries to change costume from default arrow, costume pop up window doesn't open, instead it renders a few costume pics on a completely white background (not even in the SNAP project anymore!). She is in Chrome. When she logs into SNAP on my laptop, it works fine. So it is something with her Chrome or laptop (Windows 10). I cleared cache, cookies and browsing data, then restarted Chrome.....no luck. Any ideas?

**Comment by jmoenig** [comment]
opening projects and libraries now also takes much longer than it used to... in Chrome.

**Comment by jmoenig** [comment]
seems to be a memory resource issue. When I switch to non-retina mode I can both open the costumes dialog and the open project dialog.

**Comment by ablakey** [comment]
What happens if you disable hardware acceleration for canvas 2d in chrome? This workaround hurts performance in other ways but fixed the underlying issue that was breaking hit detection in Openlayers.

Might be a workaround to reccommed until chrome 78 ships.

**Comment by jmoenig** [comment]
disabling hardware acceleration does address this issue, but it is not a scalable workaround for schools and classrooms around the world, especially since there doesn't seem to be a way for us to do it programmatically. We'd have to tell teachers or students to manually touch every single computer's Chrome installation. Many schools won't let students' computers access Chrome settings at all, and - worse - some schools totally reset students' computers every night.

**Comment by ablakey** [comment]
Yeah that's a fair point. Certainly not scaleable. And given the way school boards do IT, cannot really rely on a singular solution for all. Maybe updating Chrome is the simplest, maybe updating Snap! is.

It's interesting that this issue, which doesn't actually change the behaviour of the underlying function, only makes it a lot slower, outright breaks Snap! features rather than just makes them slower.

I did some digging but, as I'm sure you know far better than me, there doesn't appear to be a straightforward workaround to apply to Snap!

**Comment by jmoenig** [comment]
It's really easy to hate browsers these days. Seems that every fall Google breaks Chrome's Canvas API just in time for schools to start using Snap! and it takes them until winter to fix it again just in time for the TEALS students to move on to Python. It's almost like there was a conspiracy against visual programming :-)

**Comment by jmoenig** [comment]
this has now been fixed in the latest version of Chrome (v78)
