### ISSUE TITLE
Write to user's paste buffer

### ISSUE THREAD

**Issue by jcaldw737** [jmoenig/Snap#2502]
As usual I don't know if this is the right place to ask the following, but I ALWAYS get such incredibly excellent help here ...

And by the way I did at least search the SNAP Ref. Man.

Finally, is there a way using SNAP to write to the user's paste buffer?

thank you!

**Comment by jguille2** [comment]
Hi @jcaldw737!

Maybe [our forum](https://forum.snap.berkeley.edu/) is now a better place for these questions... but anyway...

I guess your question is about the _clipboard_ to copy _data_ and paste it outside?
If this is the question, the answer is Yes but Not, because you must be check (or change) the browser permission to do programmatically  _copy_ and _paste_ actions.
If you want to work with this, read the [Clipboard docs](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) and you will see all about methods and permissions.

If you don't want to work with permissions or hacky procedures... maybe a first step i to make an script to select (on background) a Snap! content. And then, you can manually do _copy_ and _paste_ actions ( [Ctrl]+C and [Ctrl]+V).

Something like this:
![selectingContent](https://user-images.githubusercontent.com/2926315/65831135-87190580-e2b6-11e9-8e62-82bfcee864d7.png)

Joan

**Comment by jcaldw737** [comment]
Thanks so very much for the quick response!  I will use the forum next time.

Here's is what I am trying to do.  For example, if I am looking a list of my files on Google Drive, I can right click on one of them and select "Get shareable link".  Then I will have a link in my paste buffer.

So what I want to do in SNAP is generate some stuff and then put it into the user's paste buffer. 

Thanks again!

**Comment by jguille2** [comment]
Ok,
Then, you can do it with my example code (put any data inside that hidden _textarea_ and select it to be able to _copy and paste_). But maybe it's easier to get a selectable area on the Snap! IDE itself.

You see some info is not selectable (like _reporters_, _say_ and _think_ **bubbles**). But you can **use _lists_ reporters** to do it.

Example. If you want to catch sprite _x position_, you can...
- Inside the scripting area, use a list to report your data, and this info is selectable.
![listReporterSelection](https://user-images.githubusercontent.com/2926315/65838806-43022100-e307-11e9-921b-d2dc0d922981.png)

- And if you want to do programmatically, you can use the stage, again with a list to get the info selectable.
![sayListInfo](https://user-images.githubusercontent.com/2926315/65838858-aab86c00-e307-11e9-9afc-e29352cc56fb.png)
and then...
![listSaySelection](https://user-images.githubusercontent.com/2926315/65838861-b60b9780-e307-11e9-982e-8a9633018f59.png)

That's all,

Joan

**Comment by jcaldw737** [comment]
Thank you very, very much Joan!!!
