### ISSUE TITLE
Use "this sprite only" block in "tell" block

### ISSUE THREAD

**Issue by swiperthefox** [jmoenig/Snap#2512]
"Tell" block is used to call other sprite's method (block), but how can I get access to other sprites blocks in a given sprite.

Let's say I have a rabbit sprite, which has a "this sprite only" new block "hop". 

I want to add a script to "Stage", and in this script I want to call the rabbit's "hop" method. How can I add the hop block to the "tell" block's ring?

If it's a common block like the "move" block, I can switch to "rabbit" sprite, drag and drop the "move" block onto the "stage", and it will appear in stage's script area, and I can drag it into the action ring of the "tell" block. But I cann't do this for "this sprite only" blocks.

Thanks.

**Comment by jmoenig** [comment]
In Snap! a sprite can only ```tell``` another sprite something it knows about. If another sprite has a local block that the sender doesn't know about it can access it in the ```of``` block's dropdown menu and ```run``` it:

<img width="203" alt="local block" src="https://user-images.githubusercontent.com/2596285/67743164-2c420d80-fa1e-11e9-9d7c-15da357cc942.png">

if it's a complicated script the "receiver" can also expose it as an attribute by assigning a ring to a local sprite-only variable, which in turn the sender can find in the ```of``` block's dropdown menu:

<img width="517" alt="local script" src="https://user-images.githubusercontent.com/2596285/67743248-5e536f80-fa1e-11e9-8354-c15ea9060dcd.png">

Conceptually ```tell``` and ```ask``` are problematic, because they penetrate object encapsulation and let one object use another one as a "puppet". If you find yourself using ```tell``` with more than one block often it's a good practice to consider broadcasting an event instead.

Does that help?

**Comment by swiperthefox** [comment]
Thanks for your quick reply, it helps a lot.

This is exactly I want to know: if this restriction is by design or I've
missed something in the manual.

I am aware of the message passing method. The reason I am looking at "tell"
and "ask" is that they resembles the "synchronized/sequential" programming
model
we normally found in most programming languages. "broadcast ... wait" can
do that, but the callee can't return values and for every method, I need to
create a short "when I receive..." stub.

Thanks for the hint of  "run ... of ..." pattern. I also found the "call"
block while checking out the "run" block in the manual.

Best,
Zhenlei

P.S.

More thoughts on the "tell" and "ask": if they can't access the target
sprite's block, then these blocks are doing wrong things. In my example, if
the stage tells the rabbit to do something, that thing must be something
that the rabbit can do, instead of something the stage can do. I tried it,
if the stage has a "refresh" block, I can create script like "tell rabbit
to refresh", running it caused a type error.

Given the existence of "run" and "of' block, are the "tell" and "ask"
blocks unnecessary, misleading and need to be removed?

It seems that the "run ... of ..."  is the right way for "tell", and "call
... of ..." is the right way for "ask".

(Sorry for the long message, it starts with a short thank you note:)

Jens Mönig <notifications@github.com> 于2019年10月29日周二 上午2:37写道：

**Comment by jmoenig** [comment]
this is, in fact, a part of Snap! that I have very carefully thought through and there is no kludge here that I'm aware of. A sprite already makes its methods available to others in the OF block. That's the general case. TELL and ASK are shortcuts if the sender also has similar blocks.

**Comment by jmoenig** [comment]
That's actually something I've been thinking about myself - the dropdown idea.

**Comment by brianharvey** [comment]
That wouldn't be so bad.  It's one of the proposals I made in email.  :-/

**Comment by jmoenig** [comment]
:-)

well, the "problem" still would be that you have to use "with inputs..." on it...

**Comment by craff** [comment]
I post on this old topic, as the situation is not really satifying. You can access the value of another script variable if and only if you have a variable with the same name. The same is true for custom block. That is a bit strange ?
