### ISSUE TITLE
Negative number parameters in javascript functions interpreted as text values

### ISSUE THREAD

**Issue by CrazyOldGeet** [jmoenig/Snap#2539]
First post so let me quickly say thank you for all the hard work that has gone into this awesome offering, much appreciated by the whole family.

I am finding that negative numbers passed as parameters in javascript functions are being interpreted as text values instead of numbers.

Example 1 produces a text value of "1-1":

![snap bug js param text script pic](https://user-images.githubusercontent.com/35629012/71182119-d0ee0800-2275-11ea-9c00-4f1be4c4a3c9.png)

This can be addressed using the Number() function to force a numeric value.

Example 2 produces a numeric value of 0:

![snap bug js param text script pic (1)](https://user-images.githubusercontent.com/35629012/71182190-ef540380-2275-11ea-8d74-da728adb8df2.png)

Thanks in advance.

**Comment by jmoenig** [comment]
Thanks!

The issue you're having is that we are not coercing the type of arguments passed into the ```JavaScript function``` block from whatever is written into the ```with inputs``` slot of ```run``` or ```call```. We simply have no idea which type of argument your JavaScript function expects, it could be anything. That's why by default we keep such inputs as strings and leave the typecasting up to the author of the JS-function:

![typeof](https://user-images.githubusercontent.com/2596285/71187057-9ccb1500-227e-11ea-946e-fab4cebb7afb.png)
