### ISSUE TITLE
Automatic project deletion (and arbitrary code execution)

### ISSUE THREAD

**Issue by otisdog8** [jmoenig/Snap#2549]
By using XMLHttpRequests in javascript code blocks, it is possible to delete all the snap projects on a user's account, even if they just open the project via a link (because snap automatically runs blocks under the "green flag"). 

Here is a proof of concept that displays all the projects on a user's account, but does not delete them. 
https://snap.berkeley.edu/snap/snap.html#present:Username=hacktest&ProjectName=Snap%20Project%20Grabber

In order to delete someone's snap projects, one simply needs to simply send DELETE requests using the snap API. 

Additionally, snap allows arbitrary javascript code execution. Snap allows someone to arbitrarily execute code on a project when it loads loading simply by putting code under the "green flag" block. 

Overall these issues are massive security vulnerabilities that could pose problems for snap.

**Comment by otisdog8** [comment]
Only works when someone is logged in on the browser.

**Comment by jmoenig** [comment]
yep, only when someone is logged in, and those scripts only affect Snap. This is a risk we're aware of, and - frankly - the alternative is to disable the JS-function block in Snap altogether. I've already introduced a mechanism that lets me easily switch off all JS functions once that situation arises, and starting with v5 we've moved to a design strategy that no longer relies on the JS block, because user-side scripts are going to be disabled by browsers in the future anyway. This is somewhat of a bummer, because kids love the JS block and teachers even more, because it lets them write scripts in text.

**Comment by DyslexicAwe** [comment]
What is a rationale for disabling user-side scripts by browsers in the future? Can you give a link where I can read more about it? And will we loose the fast (JS based) MAP block, etc?

**Comment by jmoenig** [comment]
security.

eval() and new Function() already doesn't work in Chrome apps anymore:
https://developer.chrome.com/apps/contentSecurityPolicy

so all those libraries already stopped working in the Snap4Arduino Chrome app.

But it goes beyond Chrome apps:
https://developer.chrome.com/apps/sandboxingEval

So, no we will not loose anything except the possibility to roll your own JS functions. We mostly don't need them anyway, because all the important things (like fast MAP) are primitives anyway. The JS-function block is really nice to experiment with new APIs and with rolling our own changes to Snap! without having to fork it. I think we're going to be fine for another couple of years, but yeah, looks like eval() and new Function() are going to go away at some point.

**Comment by DyslexicAwe** [comment]
>
>  I think we're going to be fine for another couple of years, but yeah, looks like eval() and new Function() are going to go away at some point.

How will Snap! work afterwards (i.e. when eval() and Function() are gone)?

**Comment by jmoenig** [comment]
don't worry, Snap! doesn't need eval() or new Function(), only for the JS-function block and for the JS-compiler. We can compile to Byte-code instead, Snap! will be fine and fast :-)

**Comment by DyslexicAwe** [comment]
> ... the important things (like fast MAP) are primitives anyway.

But the 'fast MAP' is not a primitive, it calls JS, as I can see in the image below:

![fast_map](https://user-images.githubusercontent.com/16387241/71977397-fb016d00-3218-11ea-9192-e3622a62ad63.png)

**Comment by jmoenig** [comment]
This block has been superseded by a primitive in v5:

<img width="384" alt="compile" src="https://user-images.githubusercontent.com/2596285/71981743-49b40480-3223-11ea-853b-b79791656293.png">

**Comment by bromagosa** [comment]
It still is a bummer and a huge step back for browsers to disable user-side scripts. Many client-side programming languages, transpilers and interpreters are going to stop working altogether, and we won't be able to prototype libraries _in_ Snap! anymore, like we're doing for the Math+C project at EDC :(

**Comment by DarDoro** [comment]
"CSP - content security protection" is a declarative, opt-in restriction for html pages, set by site/page owner. Chrome extension and Chrome App CSP are just predefined CSP policies, enforced by Google for privileged content : extensions and apps.
Regular Web pages have quite relaxed policy, but even for the strictest policy, there is a "local sandbox" able to execute arbitrary "dangerous" code. So these changes, seems to have no imediate impact for pages served over Web / Snap. 
In edge cases, user side script can be dynamically proxied/reflected by SNAP server to pretend it has safe origin.

**Comment by DyslexicAwe** [comment]
...
> In edge cases, user side script can be dynamically proxied/reflected by SNAP server to pretend it has safe origin.

I won't pretend that I understood anything you wrote, but this is good news, isn't it?
