### ISSUE TITLE
Height of a sprite not an integer

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2597]
![image](https://user-images.githubusercontent.com/2138696/83238559-2fc29080-a1c9-11ea-960f-6e0f5e3fb912.png)

in 
[height not an integer.zip](https://github.com/jmoenig/Snap/files/4700517/height.not.an.integer.zip)

And yet the watcher for `h` shows 231.

In beta version

**Comment by jmoenig** [comment]
watchers round gently

**Comment by ToonTalk** [comment]
But should the height of a sprite be a non-integer?

h != round(h)

**Comment by jmoenig** [comment]
Hmm, I don't understand, Ken. Are you saying we shouldn't gently round watchers (we're trying to keep them meaningful by preventing them displaying too much precision, as is Scratch:

<img width="481" alt="Screen Shot 2020-05-29 at 11 06 30" src="https://user-images.githubusercontent.com/2596285/83242851-5f5ba380-a19d-11ea-929b-9293186c4101.png">

here's our attempt:

<img width="428" alt="Screen Shot 2020-05-29 at 11 08 06" src="https://user-images.githubusercontent.com/2596285/83242892-6c789280-a19d-11ea-887f-87d9f61bf484.png">

Or are you saying we shouldn't ever round a number for display?

**Comment by ToonTalk** [comment]
Sorry, I think I combined two issues:

1. Watcher was doing rounding -- your reply addresses this well
2. The height of a sprite isn't an integer in the beta release but is in the standard release (h = round(h)) reports different things in the two releases)

Sorry about the confusion

**Comment by jmoenig** [comment]
Ah, now I *do* understand, thanks!
yes, the new version allows for more precision in Morphic shapes, because technically we no longer need to create an actual Canvas element for each morph. That's why the current version needs to truncate morph dimensions to integers (because there's no such thing as half of a pixel in a bitmap), but the version doesn't. (It's also the reason why some shapes are ever so slightly cut-off in the current version, but shouldn't be anymore in the new one).
