### ISSUE TITLE
Use "parameter objects" internally instead of variable names

### ISSUE THREAD

**Issue by rdococ** [jmoenig/Snap#2598]
As of now, Snap! only stores the names of variables in variable blocks. When it encounters a variable block during execution, it checks to see if a variable of the same name is in scope, and if so, it uses that variable.

Preferably, however, variables should store a reference to some sort of parameter object. In this case, a "parameter object" would represent a variable in the context of a script that has not been run yet. Parameter objects would replace the role of variable names internally - each variable reporter, 'set' block and 'change' block would store a parameter object instead of a variable name.

It would be these parameter objects that are given labels, as opposed to the names being stored directly in the environments that each variable is held in.

This would allow variables to be renamed easily, and on the fly, even while scripts that are using it are running.

One possible downside of this is that two variables may have the same name, but refer to different parameters. I think that this should be detected, and either prevented, or variables brought into a scope where their name refers to something else should have their parameter objects automatically swapped over.

**Comment by brianharvey** [comment]
Long ago, when the world was young, that's how BYOB did it.  It was problematic for the reason in your last paragraph.  It's true that if all such problems could be caught as the user was editing a script, rather than at runtime, Snap<i>!</i> would be a bit faster at runtime because it wouldn't have to look up variables.  But it's not just dragging in a variable that would have to be detected.  What if a variable three scopes out changes its name, thereby either shadowing or unshadowing the same-name variable four scopes out?  So I'm not sure this would be worth the effort.  @jmoenig, what do you think?

**Comment by jmoenig** [comment]
not sure whether @rdococ isn't just suggesting gensyms.

But, generally speaking, you know

> There is no problem in computer science that can't be solved using another level of indirection

**Comment by brianharvey** [comment]
Oh, maybe!  But it comes to the same thing; he wants the orange blob to point to what we have been taught to call the variable, i.e., the value cell.  As it does already, of course, indirectly (via the environment).  So the question is whether he's _eliminating_ a level of indirection (as I think) or adding one (as you think).

So, @rdococ, help us understand your suggestion by telling us what it's supposed to accomplish.  Is this a question of speeding up variable references, of adding information for the benefit of debuggers, of catching user errors at script-building time rather than at runtime, or what?

**Comment by rdococ** [comment]
> So, @rdococ, help us understand your suggestion by telling us what it's supposed to accomplish. Is this a question of speeding up variable references, of adding information for the benefit of debuggers, of catching user errors at script-building time rather than at runtime, or what?

I was thinking it would help to catch user errors at script-building time - for example, Snap! could determine if a variable is out of scope before you run the script - and that it may also make it much easier to implement proper variable renaming (which isn't always available as of now).

It has occurred to me that I probably don't know enough about how to implement this kind of thing to have good ideas about how it should be done, but oh well.
