### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by TheInfinityUser** [jmoenig/Snap#2655]
I am facing a lot of lag problems in some of my projects. For instance where I created a sine wave, when I change the sliders of the variables it lags. It has only sine waves for now. I can imagine how laggier it will get when I add new kinds of waves. I suggest you optimize the program a bit more so that loops inside warp blocks do not cause much lag.

Also, variable updates are too slow in this program. The speed of a variable update is like 1 update per second. It is hard to observe what is happening when the variable is at a certain value because of this reason. 

If the optimization and variable update issues are fixed, then I won't have to use scratch and its limited features anymore.
Hope you are looking forward to fixing these issues in the later updates.

**Comment by bromagosa** [comment]
Variables update instantly. What you mean is that the update interval of the variable *watcher* takes a second (it actually takes 0.5 seconds, if I recall). I believe that interval is totally intentional.

However, what is stopping you from creating your own variable watchers? Here's a simple one:

![MQTT chat script pic(1)](https://user-images.githubusercontent.com/1016697/87938500-f6a2f000-ca96-11ea-8324-85df452289f6.png)

**Comment by bromagosa** [comment]
Sorry accidentally closed this, although I do believe it should not have been filed as an issue. Issues are for specific bug reports, not for general wishes. These go in the forum.

**Comment by TheInfinityUser** [comment]
Oh sorry, I am using GitHub for the first time and I report all my problems here.
