### ISSUE TITLE
Weird bug with warp block

### ISSUE THREAD

**Issue by TheInfinityUser** [jmoenig/Snap#2657]
I have made a project where a sprite is connecting some other sprites together with the pen feature. However when I move one of the sprites, the sprite is stopping momentarily while moving. I have have provided the project here: 
[project.ZIP](https://github.com/jmoenig/Snap/files/4952070/project.ZIP)
<b><i>Instructions: press the 2 key and then use wasd and arrow keys to move the sprite (the blue dot).</i></b>

**Comment by jmoenig** [comment]
I can't spot anything unsual in this project, except that you use `warp` in places where it doesn't have any effect, such around a stack inside a loop that only sets a bunch of variables. That script doesn't yield anyway so I don't get why you think `warp` accompolishes anything.
I'm closing this issue here. Please use the Snap! forum for questions about how to use blocks etc. Thanks!
