### ISSUE TITLE
Huh? (Sprite Variables created via create sprite var block are not working with the other blocks if told to another object)

### ISSUE THREAD

**Issue by MrIceblock** [jmoenig/Snap#2707]
![image](https://user-images.githubusercontent.com/69524536/97383734-39335e80-1909-11eb-91e6-1a322ad018a7.png)

(Info not much; just this image as I'm too lazy to explain)

**Comment by jmoenig** [comment]
since you're too lazy to explain I'm too lazy to investigate

**Comment by MrIceblock** [comment]
> since you're too lazy to explain I'm too lazy to investigate

I kinda got the explanation now: 

**HOW TO REPRODUCE:**
This block 
![image](https://user-images.githubusercontent.com/69524536/97414560-1623a180-193f-11eb-97e0-7b9bef993a5c.png)

**EXPLANATION**
I was only trying to make a checkbox object for my *Purble Place* clone, but then I ran into this bug when using the Create Variables: Sprite Variables created via the create sprite var block are not working with the set [var] to [val] blocks on the same library. I don't have much to explain right now. But just try to fix this.

**Comment by jmoenig** [comment]
Okay. I hate this library and I'm not supporting it. It's really a bad idea to offer this, because... what are you even trying to do, and why do you think you need a programmatic way to make a variable?

Rule of thumb: Whenever you need the "create variables" library you're doing it wrong.

**Comment by MrIceblock** [comment]
> Okay. I hate this library and I'm not supporting it. It's really a bad idea to offer this because... what are you even trying to do, and why do you think you need a programmatic way to make a variable?

Ok. + I am making a checkbox object for checkboxes, so I made the parent tell its children to make sprite variables as settings. I give up.

**Comment by jmoenig** [comment]
Could you let us know some more about this "checkbox object for checkboxes" plan? I don't understand... Why don't you just let the children inherit the sprite-only variables of the parent?

**Comment by MrIceblock** [comment]
> inherit the sprite-only variables of the parent?
Okay.

**Comment by MrIceblock** [comment]
I'll try to explain more clearly: The checkbox object is for making selectable checkboxes, the reason why I'm making a checkbox object a parent is because I do not want to waste time and size duplicating the object over again and again: + Inheriting? I don't think so anymore, because the variables are not shared across each children and their parent. Here's how the checkbox parent works: It hides itself, and tells its children to: 

- Switch to its costume
- Create their own variables, each named bool
- Once they're clicked, if their bool variable is false, then they change it to true, otherwise vice versa. 
- Wait until the user lets go of the left mouse button,

There you go, I think I should explain even more clearly.

**Comment by jguille2** [comment]
Hi @MrIceblock ,

**1.** I guess you are **using clones**, aren't you? Then,

- You don't need to "create variables".  If the parent has a "sprite var" (you have "bool"), all their clones have that variable. It has initially the same value, but each clone has its own value.
- And then, you don't need the "create variables" lib, because you can assign values with normal primitives, and use the "bool" variable block from the palette.
- Also, playing with clones, you can use "tell" but it is not necessary. You can code the parent, and all the clones do the same. You can use "When..." hat blocks.

**2. **Note about "create variables"
If you write down the variable name (here "bool"), you don't need it. Because you can use Snap! primitives and IDE actions. It doesn't bring you anything interesting.

**3.** More about "create variables" lib
@jmoenig, I'm sorry and I don't want to bother you. It can be deleted. But it was done (current version... he former one had many more problems) with change over change following your (Brian and you) discussion.
To write down what's happen: following the "Eisenbergification" ideas, it allows to do programmatically IDE actions over variables. Scope issues (script-sprite-global) are running fine.
But it has problems with "launch" and "tell-ask" because evaluation problem (problems detecting "homeContext" receiver).
It can be fixed... or maybe it's better to take it away.

**4.**  And an extra programming comment for @MrIceblock 
Just do
![boolIssue](https://user-images.githubusercontent.com/2926315/97523361-59fbc280-19a2-11eb-9ffe-7abad6cfabdb.png)

Quite simple... and beautiful solution, isn't it?

Joan

**Comment by MrIceblock** [comment]
No no no, I am using separate sprites and assigned the Checkbox object as their parents.

**Comment by jmoenig** [comment]
Okay, can you just share a project?

**Comment by jguille2** [comment]
@MrIceblock ,

I don't understand your problem. Your Checkbox object can be one of the "checkboxs", or you can hide it. That's no problem.

Test with a simple project to see clones behavior...

![clonesBehavior](https://user-images.githubusercontent.com/2926315/97572862-327c1880-19e9-11eb-9003-81ed74b5f234.png)

Or closer to your project... (create before a "sprite variable" called "bool")

![clonesBehavior2](https://user-images.githubusercontent.com/2926315/97573227-b7673200-19e9-11eb-8352-d7633790df7d.png)

Joan

**Comment by jmoenig** [comment]
Plus, you don't even need a variable for a binary switch at all. You can just check whether the costume # equals 1 or 2. That's all the state you need. I don't understand why you'd ever need to dynamically create a named variable at all. How did you come up with that idea?

**Comment by jguille2** [comment]
Oh yes!
I also guess (now) he uses it to change its costume (checked or not).
This part (costumes manager) is not in the example reported and I didn't think about it.

**Comment by MrIceblock** [comment]
I am now using clones, thanks jguille. + No no no Jens, I will use a cloned sprite of the checkbox that is on the place of the checkbox, because I do not want to waste size.

**Comment by MrIceblock** [comment]
I am back to parents and children for some reason: I said I am using separate sprites and assigned the checkbox as their parents.

**Comment by jmoenig** [comment]
Can you - please - share what exactly you are trying to accomplish? I don't know what you mean with "checkbox of checkboxes". I mean, I have an idea what that might be, but it would be so easy and trivial to implement that it's probably noit what you're trying to do. So, please, please, pretty-please, tell us more about that project. You can share a project and we'll be able to help you. Also, can you tell us a little more about yourself and your motivations for the project? Are you a teacher?
I'm absolutely sure that you don't ever need that variables library and that there must a misconception about what a variable is and how it works. We can clear that up, talk to us!

**Comment by MrIceblock** [comment]
Here's an extended example of what am I trying to accomplish. (For some reason it's now saying stage is null to me.)

https://drive.google.com/file/d/19vlDxiHJA1TYyGz9jta17CXw9cLoP1o6/view?usp=sharing

**Comment by jmoenig** [comment]
No, I mean, share as in Snap! Just share the url. Are you a teacher?

**Comment by jmoenig** [comment]
I can open your project, but I don't know what you're trying to do. C'mon, talk to me! I understand English and I can read complex sentences. This is getting on my nerves, I'm annoyed by your lack of communication. Tell me in plain words what it is you want to do. Can't be any harder than fidgeting around with all that code! Grump.

**Comment by MrIceblock** [comment]
https://snap.berkeley.edu/project?user=lee%20maccloudy%20728&project=hi Sorry for being late, because I wasn't focusing on this issue + No, I am not a teacher.

**Comment by jmoenig** [comment]
Just showing me code doesn't give me direct access to your idea or plan. I suggest you learn about variables.

**Comment by MrIceblock** [comment]
> Just showing me code doesn't give me direct access to your idea or plan. I suggest you learn about variables.

Then, you can't help, because the project is in early development. :(

**Comment by jguille2** [comment]
We can't help you because we don't know what you want.
