### ISSUE TITLE
Text Costumes library costume starting with "A" too small in speech balloon

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2712]
This is really weird.  If you give it a text starting with capital A and just click it in the scripting area, the picture of the costume is tiny, even though the speech balloon is big enough to hold the correct size costume.  If you have the sprite wear the costume, it's the right size on the stage.  It's only text starting with A that behaves this way!

Chrome 85.0.4183.121, MacOS 10.13.4

**Comment by jmoenig** [comment]
interesting!

For the letter "A" the costume width seems to be always 480 pixels, which is waaaay too wide, and the reason for it ending up tiny inside a watcher or symbol:
![untitled script pic (43)](https://user-images.githubusercontent.com/2596285/98509449-80064a00-2261-11eb-8f7a-e19bdf45090e.png)

Investigating...

**Comment by brianharvey** [comment]
... but only if the "A" is the _first_ character of the text.

**Comment by jmoenig** [comment]
Actually, I can reproduce it with other chartacters as well. The Problem is that at one time we decided to start printing at the very *left* edge of the Stage. Afterwards we're trying to determine the pen-trail's bounding box, and since the very *first* column of pixels already contains opaque colors we stop, leaving the width at whatever the Stage's width is. Solution: start writing at one pixel to the *right* of the Stage's left edge.

About to push a fix for the next Snap! patch.
Thanks!

**Comment by jmoenig** [comment]
Oh, wait! Maybe that's the wrong fix. Lemme check some other cases...

**Comment by brianharvey** [comment]
While you're at it, make a variant called "button" that puts a rectangle around the text and makes the interior white instead of transparent.

**Comment by jmoenig** [comment]
The "button" generator is a nice project idea that we're actually doing with kids.

**Comment by jmoenig** [comment]
Turns out the bugfix requires some more internal tweakings, it also happens in other "edge-cases".

**Comment by brianharvey** [comment]
Re "button":  We've stopped refraining from providing tools just because they make good projects.
