### ISSUE TITLE
Costumes not updated (refreshed) after "editRotationPointOnly"

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap#2715]
Hi,

- Edit "rotation point only" of any costume.
- Change its rotation point and save this action (Ok).
- The sprite does not move!
- Make a change (for example, change of costume and return to it) and you will see the change (the sprite will be moved).

I think we must change the way to call the editor in this action of "editRotationPointOnly". If we do the same change (only rotation point) from the main editor, changes are instantly visible when saved. That "refresh" must be ordered by the caller, because from the costume I can't do it.
This affects to other costume manipulations (I working on a svgCostume fitting) but I need to see where is the problem clearer.

Thanks,
Joan

**Comment by jguille2** [comment]
Thanks Jens (@jmoenig)

One question... Do you want to force to wear that costume?
We can edit a costume that we are no wearing. Then maybe something like
```javascript
    action = () => {
        editor.accept();
        if (anIDE.currentSprite.costume === this) {
            anIDE.currentSprite.wearCostume(this, true); // don't shadow
        }
    };
```

And if you agree, maybe we can do the same with the "edit" functions ( `Costume.prototype.edit` and `SVG_Costume.prototype.edit`). Now, we have this forced action (wearing the costume edited).

And another question (I didn't submit any PR because I don't know these details). Do we need this other line?
`anIDE.hasChangedMedia = true;`

Thanks!
Joan

**Comment by jmoenig** [comment]
Hi Joan (@jguille2),
yes, I want the behavior to be the same when editing just the rotation center and when editing the costume graphics, the sprite should end up wearing the costume. The fact that it wasn't already doing that was a longstanding oversight.

We currently don't use the `hasChangedMedia` flag. That used to be needed for deciding whether to upload the whole project - including all costumes and sounds - or just the code (blocks) part. But afaik @bromagosa and @cycomachead decided to always upload the whole project to the new backend. But it doesn't matter anyway, because we're setting that flag before we call the function in the GUI, so it's all good.
