### ISSUE TITLE
Pararellism bug-

### ISSUE THREAD

**Issue by DavidGasku** [jmoenig/Snap#2745]
https://snap.berkeley.edu/versions/dev/snap.html#present:Username=davidgasku&ProjectName=Concurrency%20bug

This program gives a different result if executed normally, or with stepping enabled.

![bug](https://user-images.githubusercontent.com/5382201/101533480-2c893800-3996-11eb-96e2-5e58d1686553.png)

**Comment by Barthdry** [comment]
Yes that is truly a bug and thank you for reporting it when stepping it gives result 1 and when in normal mode gives the result 2

**Comment by jmoenig** [comment]
Hi @DavidGasku, 
even though this looks like a bug it really isn't one, it's a race condition and those happen in concurrent environments. Usually we tend to avoid them using some clever heuristic to determine protected areas in the code, bu in stepping mode we drop these guards in favor of ... stepping.
What's happening here is that two threads fight over the `when I receive "b"` script. As you know, clicking on a script starts it and - this is crucial - clicking on a *running* script stops it. The same happens with broadcast messages: An already running script *stops* and then *restarts* from the beginning. Usually you don't notice this, because in the case of "normal" running mode the `b` script runs in a single step, so it doesn't get interrupted before it can change the variable. However in single-stepping mode it takes several steps to evaluate the inputs and then execute the `change` command. If, like here, in the meantime it gets triggered *again*, it will restart and only the second trigger gets to complete.
What's the takeaway here? `Broadcasting` messages is *not* the same as invoking a subroutine or calling a function! It is a mechanism that lets you synchronize music and games, but if you're serious about race-conditions, use functions.
Hope that helps.

**Comment by DavidGasku** [comment]
Ironically, I discovered this bug while designing an activity to explain race conditions, in the sense of a non deterministic execution that leads to an arbitrary variable value. Forcing the order in which the "function" is called, to see the different results.

While I respect your design choice, I'll try to mimic the function behaviour in a PR. As I usually miss the function definition in the same ScriptsMorph for teaching purposes, I often mimic it by using the message system.
One alternative would be having the function definition in the sprite's ScriptsMorph, as in Scratch, at least for local functions (the global ones would be inappropriate, as they don't belong there). This could be toggleable in the custom block's menu.

**Comment by brianharvey** [comment]
We do have sprite-local custom blocks.  Tiny radio buttons in the dialog, same as for variables.

**Comment by jmoenig** [comment]
@brianharvey I think @DavidGasku wants the block *definitions* to be visible in the scripting area - like in Scratch - and not "hidden" inside a block editor. That's the design choice he means.

**Comment by brianharvey** [comment]
I got that.  I was reacting to "(the global ones would be inappropriate, as they don't belong there)."  But I guess he already knew that; on first reading I got the impression that he thought he had to invent sprite-local blocks before he could invent his visible-in-scripting-area feature.  Sorry...

**Comment by jmoenig** [comment]
yeah, it's interesting how we sometimes get those wishes to always see custom block definitions in the main scripting area. And it's equally interesting how in Microblocks where we do just that (same as in Scratch) we're going out of our way to let users hide those again.
