### ISSUE TITLE
ignore WARP when visible stepping

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2782]
I have a procedure that I thought worked, but now seems not to be, so I try to single-step it, but the whole body is inside a WARP, and so it all gets counted as one step.  I think the WARP should be ignored so that the stuff inside it can be stepped.

**Comment by jmoenig** [comment]
Hmm, this is entirely intentional. I've made it so that you can use WARP to jump over sections you don't want to step through. It's not ideal, I grant you that, but I've found it to be extremely useful to WARP over code I don't want to step through, but, of course, that also means that you have to un-warp sections you *do* want to debug...
