### ISSUE TITLE
negative indices question

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2786]
If you've got time (if not just ignore)- what is this all about? 

https://github.com/jmoenig/Snap/commit/ecb25fe4736cb88b2889a0e1f81b8c9c13165577

**Comment by brianharvey** [comment]
Jens is trying out an extension to the ITEM block to allow slicing, kinda like your recent forum post except that yours was a separate block, thereby avoiding the need for backward compatibility.  I think I have a somewhat better syntax to acheive backward compatibility than Jens's so I don't think this feature will be in an official release until we settle that.

**Comment by jmoenig** [comment]
Hi Simon,

it's about slicing on multiple dimensions. A prototype that I'm exploring for the curriculum work about AI and Machine Learning Jadga and I are currently developing. It's controversial with Brian who likes to think in terms of syntax instead of blocks and doesn't (want to) understand the design, so don't count on it making it into production, because as usual we'll never agree.

I will demo parts of it next Friday at an invited talk I'm giving at the annual HPI research symposium: https://webinars.sap.com/hpi-symposium/en/home

**Here's how the current prototype in dev works:**

1. When you use a list inside the index slot of the `item _ of _` reporter you get back a list of selected items. Valid Snap! list indices - positive integers - select a single item each. This is already the case since v6: 

![indices1](https://user-images.githubusercontent.com/2596285/108471158-4ba42000-728b-11eb-9487-919c01e92fef.png)

2. The new feature is that zero and negative integers select a *slice* of the list beginning from the item *next* to the *last selected single item* to the indicated offset from its length. If no item has been previously selected the *next* one is the first one. So, specifying the range of `-3` in a 7-item list selects the items 1 to (7 - 3 = ) 4:

![range1](https://user-images.githubusercontent.com/2596285/108472204-ba35ad80-728c-11eb-8d52-3660a03f8ae7.png)

Likewise, specifying the positive integer `3` will select the 3rd item, and a following `0` will select the items *following* the already selected 3rd one up to the end of the list:

![range2](https://user-images.githubusercontent.com/2596285/108473070-d4bc5680-728d-11eb-8d41-4ed271c49eee.png)

Another example: specifying the positive index `2` selects the 2nd item of the list, the following negative integer `-3` then selects the items 3 (the one following 2) up to the length of the list offset by it (7 - 3 =) `4`:

![range3](https://user-images.githubusercontent.com/2596285/108473300-2369f080-728e-11eb-81a3-6f4f35498615.png)

Note that the *next* item is direction aware. This example first selects the 6th item, and then a range up to the (7 - 5 =) 2nd item. In this case the range starts at the *next* item after the chosen 6th one in the direction of the range target, effectively returning a reversed slice of the list:

![range_reverse](https://user-images.githubusercontent.com/2596285/108473716-b014ae80-728e-11eb-9b13-6a88543be0c0.png)

Remember that every number in the index list selects something. This is not about syntax (contrary to what certain people want to believe). Therefore you can accumulate and combine ranges with single elements and also with other ranges. The following example selects the 1st and 4th item, followed by a slice beginning at the *next* item after the fourth one up to the end of the list:

![range_combine1](https://user-images.githubusercontent.com/2596285/108474126-3b8e3f80-728f-11eb-8edd-2a41e0b9cefd.png)

Also note that selecting a *slice* does not advance the "next" item. Therefore you can repeat slices simply by repeating their indicator:

![range_repeat](https://user-images.githubusercontent.com/2596285/108474438-ae97b600-728f-11eb-824c-a096005cdb81.png)

3. Slicing works in all dimensions of a data structure. On a 10 x 10 cell matrix the following example first selects the rows ranging from 1 up to (10 - 3 =) 7, and then the columns 4 and 6 followed by the *next* columns up to the (10 - 2 =) 8th one:

![range_multi-dim](https://user-images.githubusercontent.com/2596285/108474517-cb33ee00-728f-11eb-9c5d-c81e38e738a9.png)


**The disagreement**

Our current disagreement is about whether single items should also be selectable counting backwards from the end of the list, and - as usual  - about notation. When I designed this feature I did it with the `numbers from _ to _` reporter in mind, which I'm constantly using for selecting slices of consecutive elements, and which *already* lets me *reverse* those slices. In my personal projects I hardly ever feel the need to select a *single item* based on its offset from the end of the list, but I often encounter the need to select "all but the last" elements, or "all but the last couple of elements". This is now easily possible by just specifying the slice `-1`.

It's also important to be able to compute the list of selectors in another function. One benefit of using zero and negative integers for that is it's easy to generate these selectors from the `length` attribute we already have, because our lists are index-1 based.

**Comment by cymplecy** [comment]
I am off to make a strong cup of coffee ... :)

**Comment by cymplecy** [comment]
Ta for info :)

Just to say, that to my muggle brain, I'd expect

item(list(list-3)) of (A B C D E F G) to give (A B C D E)

Reasoning: In Snap!, we use 1-based indexing so item 1 == A, so I think item -1 should == G, so item -3 == E) so items (1 to -3) == (A B C D E) as Snap! indices are always inclusive

**Comment by jmoenig** [comment]
so `all but the last one` would be `-2` instead of `-1`?

**Comment by cymplecy** [comment]
If ?Humour then Yes else apples <> oranges :)

**Comment by jmoenig** [comment]
closing because we've decided to take this feature out again for now.
