### ISSUE TITLE
probleme with pain editor

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2793]
replace one color with transparent alters the other colors around

https://snap.berkeley.edu/project?user=gego51&project=bug%20with%20paint%20editor

**Comment by jmoenig** [comment]
yeah, we can't do much about anti-aliasing. But you know, since you can access the pixels in Snap itself you can write your own flood-fill operations.

**Comment by gego51** [comment]
Iyou can disable smoothing and a

**Comment by gego51** [comment]
you couldn't just disable anti-aliasing and add a zoom in paint editor?

![3e3ae4a0c670b99d9df14688c458048d6747aab7](https://user-images.githubusercontent.com/5407223/109779219-04604c80-7c06-11eb-9452-b74717f145d8.png)

look at the content of the js code of this script, I replaced the white with red, then the red with blue before going back to white, if it is the anti-aliasing that does this in the image editor, there is a way to disable it I think, the ant-ialiasing is good to smooth the sprite in the rendering but not during each image modification

**Comment by jmoenig** [comment]
okay, look. The built-in paint and sketch editors are little tools to quickly let you draw up something you think about, they're not professional graphics software. The good thing is that nothing stops you from using just any drawing program, because you can import any picture into Snap. These are design decisions meant to support a wide range of activities. The use case I'm having in mind is kids drawing figures for their games and stories.

**Comment by gego51** [comment]
I do not ask for a professional image software integrated in Snap, just a simple and intuitive tool like in Scratch first name, imagine the child, he gets tired to make a drawing for his project with the Snap tool! , or he imports one on the library, he doesn’t like the color of the jeans of the drawing, he will then click on the bucket to change the color of the jeans, and he sees that it has cropped the contour, and the he realizes that it does not go as he wants, I do not ask that you do Snap! a professional editor but fix a problem that harms the intuitiveness of Snap!
a child will not open 30000 program just to modify an image, the fill that alters the other colors, it is not intuitive for children, a lack of zoom in the tool, it is not intuitive

**Comment by jmoenig** [comment]
This isn't so much a design choice as being "beyond our control". There is only limited support over how to control antialiasing in web canvasses, and if you care look up the specification you'll notice that parts of it are still considered "experimental", and not (yet) full standard. Just because someone claims that there is a setting for something doesn't make it usable for production on a wide variety of browsers and hardware, especially since Snap is used in many schools and kids need to produce graded projects with it, so we need to make sure things work the same for most.

Also, bear in mind that disabling antialiasing for *one* canvas, e.g. in the paint editor, doesn't solve the issue, because costume often end up being used in a variety of different places in Snap, and costumes are even *created* from different sources in Snap, e.g. from pentrails, from a list of pixels etc.

Really you can read the specs and standards as well as I can, and . There are lots and lots of examples where antialiasing is clearly improving kids' projects. We want to support a wide range of ideas and activities, and we care a lot about performance and stability. That's why @brianharvey 's suggestion in the forums to "just keep 2 copies of every canvas" or to "just issue a PR" doesn't help this discussion one bit, especially after we've spent *months* redesigning Snap's architecture to *get rid* of canvasses for the sake of avoiding Snap's crashes.

Hey, I really appreciate all the enthusiasm you put into creating cool animations and nice projects. Just don't let this become a contest about who gets to complain the most about free and open software.

**Comment by gego51** [comment]
ok, I’m sorry to have teased you a bit, I really appreciate what you’ve been doing for 10 years, Snap is an extraordinary tool and not only for the academic environment.
