### ISSUE TITLE
blockify truncates table

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2817]
I have a table that is 1078x5 and blockify produces blocks that produce 72x5 (where the last row is only 3 long). The table just contains text.

If blockify must have some size limit at least a warning should appear.

**Comment by jmoenig** [comment]
it does! The limit is 500 elements regardless of nesting depth, and it's there precisely to prevent users from crashing Snap! by - accidentally or willfully - blockifying giant lists / tables.

Y'all might be seeing too much in "blockify" than is there. The main use case I had in mind when adding this feature was to enable an easy way to let you restructure a (set of) list block(s) with literal values after you find out that you need to insert another item or remove one. Say you're writing a *little* (!) script that plays a melody of notes, and you're *directly* using a list constructor in your script for that. You keep expanding the reporter and add more notes (which might be sublists of pitch and duration). When you're done with that little tune you suddenly realize that you're missing one additional note, or that there's one too many. Instead of fidgeting around with the existing script trying to manually move all the items one slot to the right you can simply evaluate that list block, assign it to a variable, insert another item programmatically, and then blockify *that* to replace your faulty original.
