### ISSUE TITLE
Hitting a limit of 360 when creating new costume from pixel list

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#2831]
I'm creating solid square costumes but seem to have hit a size limit of 360

![image](https://user-images.githubusercontent.com/2357428/118365254-d4cda900-b593-11eb-83bb-1e793b7764f5.png)

![image](https://user-images.githubusercontent.com/2357428/118365221-b10a6300-b593-11eb-9304-dec8f25da36d.png)

I can work around it by stretching

![image](https://user-images.githubusercontent.com/2357428/118365350-4c9bd380-b594-11eb-9e63-c517f5d195b7.png)

But can the limit be removed (or at least increased to 480)?

**Comment by jguille2** [comment]
Hi Simon,

There is not an specific limit. New bitmap costumes (using _new costume_ block and also importing pictures) are fitted to the stage dimensions.
You can change stage dimensions and your limit will be different.

But I guess you won't to do this...

Then, I think "stretching" is the right answer. In fact, you can use the minimum expression (here, 1 pixel, because you use squares) and stretch to the desired size any time...

![stretching](https://user-images.githubusercontent.com/2926315/118381185-aded9200-b5e8-11eb-8778-82a35fd34a80.png)

Joan
