### ISSUE TITLE
Load failed: Project uses newer version of serializer.

### ISSUE THREAD

**Issue by kmwilson** [jmoenig/Snap#2866]
Created offline using 7.0 and can't open offline or online using 6.9.0

**Comment by brianharvey** [comment]
Why would you expect otherwise?  You are using a _development_ version of Snap<i>!</i>, one that hasn't officially been released for public use.  When developing new versions of any software, responsible programmers worry about _backward_ compatibility, e.g., making sure that Snap<i>!</i> 7.0 can open projects developed in earlier versions.  But if we were constrained also to worry about _forward_ compatibility, that would mean we could never add new features to the language.
