### ISSUE TITLE
Chrome Script Pics Have a New and Different Size

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2882]
Sometime in the last few months, the script pics outputted by Chrome (Version 92.0.4515.131) have gotten bigger.  This is a problem for me as a curriculum developer because the script pics in the curriculum are now different sizes 🙁. I've been trying to figure out the issue with Michael and Brian for a while (so I can go back and fix everything), and Brian and I have just pinned it down to being an issue with Snap in my version of Chrome.

**Comment by DarDoro** [comment]
With "Retina display..." pictures are twice times bigger.

**Comment by cycomachead** [comment]
The issue seems different because it’s the same machine (so in theory same device pixel ratio) but different output

**Comment by DarDoro** [comment]
"Retina..." enables itself in any computer (chrome@WIN10) when browser zoom <>100% . Also "Zooms blocks ..." setting is stored in local storage so is user/profile dependant.
It's important to compare those images to see if there is x2 ratio.

**Comment by cycomachead** [comment]
Yeah, but in this case the report is nothing changes about the computer/snap/setings _except_ the Chrome version. We've been comparing with Zoom blocks 1.5x. @maryfries can you post a link to an original block image and now a new one (pre-resizing if you have them)

**Comment by brianharvey** [comment]
The ratio is less than 2; we thought of this retina thing right away, but this honestly is a different issue.

**Comment by maryfries** [comment]
Here's an image I made while we were pinpointing the problem. All four (command) images were made in Chrome. The first two (purple) where on my Air (non-retina, presumably a different version of Chrome; it's on 92.0.4515.131 today, not sure if it was on that version then) and the second two were from my MBP (retina display with Snap_!_ retina support turned on; same Chrome version). We were checking if it was the computer and/or human error (e.g., a change in my zoom blocks setting or my photoshop reduction process). No external monitor was used on either machine.

The second image (air, not-photoshopped) is closest to what the images used to look like by the third process (MBP photoshopped). Then we started checking image sizing across browsers and quickly realized that it's an issue with Chrome on my retina MBP. Outside of Chrome my MBP (with retina support on) creates an image twice the size of the second image and then my photoshop process reduces it to the size of the second).

My MBP is my work machine, so I need to use that, and I prefer Chrome not only because that's what I use, but also because all the images I've made so far have been from Chrome and I believe the script pics look different depending on the browser, right?

![image](https://user-images.githubusercontent.com/6549787/130523797-b8befb1a-71da-408d-803e-525c3ff13580.png)

**Comment by cycomachead** [comment]
Wait, this sounds like a retina issue then. 

Can you try another browser to see if the images come out the same size?
In the javascript console try executing `window.devicePixelRatio`, and report what that says.

'd be curious if Chrome started doing something different with a Canvas and HiDPI displays...it's certainly possible.

**Comment by maryfries** [comment]
In Safari browsers, the images are fine. "Then we started checking image sizing across browsers and quickly realized that it's an issue with Chrome on my retina MBP."

window.devicePixelRatio = 2.5 (Chrome MBP); 2 (Safari MBP)

**Comment by cycomachead** [comment]
Ok. Hmm. That’s weird… 

This seems like a broken chrome thing but in the meantime just resize by 40% and it will work out the same. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by DarDoro** [comment]
> window.devicePixelRatio = 2.5 (Chrome MBP); 2 (Safari MBP); 2 (Firefox)
So Chrome@MBP makes Snap! images tripple as big as for non-retina.
ceil(2.5) = 3

You may try to set window.devicePixelRatio if it's still supported.
Or try to unzoom till DPR<2.

**Comment by jmoenig** [comment]
what's the status of this issue? Have y'all established that Mary's new laptop has a different devicePixelRatio than her old one?

**Comment by maryfries** [comment]
Hi Jens, No update from me. This is the same laptop I've had since 2015. Nothing is new except perhaps an update with Chrome or Snap_!_. I first noticed the new problem sometime around June this summer. Thanks!

**Comment by TheMapotakes** [comment]
Snap! Jr. is so cute too!

**Comment by DarDoro** [comment]
70% zoom does not help?

**Comment by jmoenig** [comment]
Hi Mary, I cannot reproduce this on my MBP, as far as I can see the exported script pictures are the same size and resolution as always, especially that they come out double sized because the browsers doesn't adjust the resolution to 144 dpi but instead leaves it - wrongly - at 72. Did you compare the actual exported images, or the result that comes out of Photoshopping them? Just checking whether maybe Photoshop changed something...

**Comment by maryfries** [comment]
We ruled out Photoshop already. I'm happy to run any tests￼￼ you devise.￼

**Comment by jmoenig** [comment]
the fact that different browsers show different values for `devicePixelRatio` might be hint. In particular the value of `2.5` looks very suspicious, because - I've just looked it up - apparently all Apple MacBook "retina" devices only ever have a devicePixelRatio of exactly 2. Is it possible that you've slightly increased the browser zoom level for Chrome and Snap? This seems like the most plausible explanation to me: I usually increase my browser zoom level to 125% when I make a screen recording, and - lo and behold - that changes the devicePixelRatio to be *exactly* the 2.5 that you're seeing after reloading Snap.

Mary, can you try resetting the browser zoom to 0, then reload Snap (that part is important) and *then* again look at the devicePixelRatio and try exporting a script picture? I'm almost sure it'll be what you'd expect it to be again.

**Comment by TheMapotakes** [comment]
Yes

**Comment by maryfries** [comment]
Jens, you may have solved it!! I can't believe it took us this long to figure that out, but it does seem to help! Thanks!!

**Comment by jmoenig** [comment]
Yay! I'm super glad we've finally discovered and solved that issue. Thanks for testing and confirming!
