### ISSUE TITLE
getters and setters library uses JavaScript

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2942]
![untitled script pic (40)](https://user-images.githubusercontent.com/2138696/146250628-b4713b08-abd7-4f2d-8e38-00563adf9af1.png)

If some libraries aren't updated perhaps their should be some kind of warning.

**Comment by brianharvey** [comment]
Yes, Jens's feeling is that that library is dangerous and people should have to acknowledge that when they use it.  But I agree that we could change the name to "Getters and Setters (Enable JS required)" or something.

**Comment by jmoenig** [comment]
that's right. That library has been superseded by safe-to-use primitives. The remaining options are all not safe to use programmatically, and I'd rather not have them at all. Therefore I'll require users to acknowledge JS for these.
Really, don't use it.

**Comment by ToonTalk** [comment]
Makes sense.

One of the things I was relying upon in some exercises was
![untitled script pic](https://user-images.githubusercontent.com/2138696/146360558-0d4e5526-b705-4b9f-8bb6-159077ca1ac9.png)
They start in presentation mode and then at some point the project leaves presentation mode for the user to tinker with some things set up while in presentation mode.

I guess I'll just implement something to change presentation mode in ecraft2learn. Or is there an alternative?

**Comment by jmoenig** [comment]
Well, you can do whatever you like in your ecraft2learn extension :-)

I'd still like to convince you, however, to leave the user in control of the IDE, especially when it comes to deciding how to view a project (in edit or presentation mode). I know that this is highly controversial and that Brian likes to take the opposite view, claiming that we should let the programmer decide. To me, the IDE guarantees a safe and secure set of features that should let you explore *any* project. Those "guaranteed" features come out of only 2 principles:

1) Stop means stop. Pressing the red stop button stops everything.
2) No locks. You can always look at (and into) everything. Things may be hidden, but never locked.

These principles work both for students and for teachers. Students can trust teachers to configure stub projects and microworlds to their benefit, because if they want they can always see everything. Teachers can trust students not to turn it projects that hijack their browser or won't let them exit again. The same also works for kids sharing projects among their friends and classmates.

Letting projects programmatically change the stage dimensions, edit and presentation modes etc. etc. invites for projects that dodge user input and make the IDE behave in unexptected ways, disempowering others who are exploring your project.

I know that this is highly controversial, and that many educators (and most kids, for sure) love to lock up their projects and to control the "user experience". But I'm convinced that guaranteeing a reliable, consistent ownership of the IDE benefits everybody, especially when sharing a project.

**Comment by ToonTalk** [comment]
If I were exploring someone's project that started doing strange things I would just close the tab. I agree that we don't want to enable projects that make any changes that survive the closing of the tab.

While I personally agree that locks are bad, I'm not sure how I feel about someone who wants to lock their project. I wish they wouldn't but I'm not sure I feel comfortable making it impossible. But as you say this is "highly controversial"

**Comment by brianharvey** [comment]
For me, this _isn't_ just an issue about my general feeling that _everything_ should be doable in a program.  The specific case of presentation mode is something I use all the time while doing presentations.  I'm not trying to "lock" code with it; I'm trying to automate scene switching in a talk or in the tutorial videos I have to finish making someday.

Yes, annoying children can use it to be annoying.  The solution to that, imho, is always to have the stop button showing.  That's inelegant for building apps, but if you want to ensure that users can see each others' code, I'd rather have the restriction of not being able to hide the stop button than the restriction of not being able to use presentation mode programmatically.
