### ISSUE TITLE
Site freezes when click "Show table" in dev mode without any input

### ISSUE THREAD

**Issue by DXLB-Dichter** [jmoenig/Snap#2944]
This is pretty self explantory.

**How to Replicate**

1. Make a Project
2. Go into Developer mode 
3. Go to variables
4. Click Show table without dragging it, or without input

**Specs**
HP Chromebook 14A G5
Chrome OS 94.0.4606.124 (x64)

**Comment by jmoenig** [comment]
Please - it's called *dev* mode for a reason: error catching is turned off, so we can debug the errors in the console. Like all list primitives the expected input type is asserted to be a list, and if you leave it blank it is *supposed* to throw an error. But nothing freezes at all, you can just press the stop button.

The "show table" block is in dev mode for a reason: To help the Snap! devs debug lists. There is literally nothing in there that should interest anyone who is *not* working on Snap itself. We're leaving it open, so everyone is might be interested can look underneath Snap's hood. But I get very annoyed about alleged bug reports in dev mode, especially when it turns out to be perfectly fine and to work exactly as designed.
