### ISSUE TITLE
Continuations act in mysterious ways

### ISSUE THREAD

**Issue by rdococ** [jmoenig/Snap#2969]
![really broken continuations](https://user-images.githubusercontent.com/3169568/150699362-37af1f68-7caa-435e-a3ba-0a605bc21bf9.png)

If Snap!'s continuations were undelimited, as I originally assumed, this script would say 1, and then it would say 2, 3, adds b, b2 and c to the list on loop, as the continuation is invoked, returning execution to a previous point over and over.

However, this is not the case. What actually happens is that they are... "sort of" delimited. The script says 1, 2, 3, 2, 3... adds b, b2, c - then, on the second go-around, it decides to _skip over_ adding b, only adding b2, and then adding d as if the continuation returned like a procedure.

I would get if the script just said 2 and 3 on the go-around without adding b2 again. That would mean these continuations are delimited by the end of the procedure, and I suppose that makes sense. But this behaviour of continuations seems completely unintuitive to me, and I can't seem to make sense of it! Is this behaviour intentional?

**Comment by jmoenig** [comment]
dunno what you mean, you can totally use run/cc to make an infinite loop:
![continuations_loop](https://user-images.githubusercontent.com/2596285/150701102-4ec6c5b0-4b7f-4a1a-bf82-89ff23e0720d.png)

**Comment by brianharvey** [comment]
Confirming that Jens's examples work, but also confirming that rdococ's examples fail as described.

Since Jens's examples _end_ with the RUN CONT, they don't speak to the behavior of rdococ's script, which does ADD D TO LIST after the continuation, and that does happen, even though the continuation shouldn't return.

Moving one of the SAY blocks up a level in nesting:
![untitled script pic](https://user-images.githubusercontent.com/3885074/150703972-1946aadc-ddf0-4008-857e-c525439ce459.png)
says 1, 2, 3, 2 and makes LIST {a, b, b2, c, b2, d} so it's not just that the first instruction after the inner scope is skipped.  Adding another SAY:
![untitled script pic (1)](https://user-images.githubusercontent.com/3885074/150704168-f7f0fa77-b391-48f7-b4ce-17c3f29d6e92.png)
says 1, 2, 3, 4, 2 and makes LIST {a, b, b2, c, b2, d} just as above.

I hypothesize that only the last instruction of the outer RUN is included in the continuation (and that the continuation wrongly returns to its caller).

**Comment by rdococ** [comment]
Some further testing:

![continuation bug reason 1](https://user-images.githubusercontent.com/3169568/150795513-534ad44a-31c1-4e41-a091-8fab58eee504.png)

This is similar to the previous script, except I have added a flag that stops the script before reaching the buggy part. When I set the flag to true and then run the continuation, on the first loop around it works fine - '1, 2, 3, 4' - but when the continuation is invoked again, it says '1, 3, _this should not be said_'.

Using the 'JS function' block to check the continuation's parent context, before running "say 2" the continuation's parent context includes both "say 2" and "say 3" - but after running "say 2", it only contains "say 3" - when in reality, it should still contain both, as invoking the continuation should _return_ to that point and go through both blocks again.

I believe whatever context represents the "say 2 and 3" script is not being copied when it should, and so when the "say 2" block is run, it is removed from the context and the continuation only 'remembers' the last block (which isn't removed, likely because the context is popped instead of removing the last block from it).

**Comment by jmoenig** [comment]
closing this, see my comment in #2976

**Comment by rdococ** [comment]
I don't know whether any curriculums attempt to teach continuations, but if they did and they used Snap! to do so, teachers and students would be left scratching their heads.

You don't have to fix continuations, it's your project, do whatever you want with it. Snap! is a great programming environment already. However, I think if any software being used in production (as I hear Snap! is being used for education) has a non-working, limited, experimental feature, it might be a good idea to show a warning or hide it behind a setting.

**Comment by jmoenig** [comment]
hey, did you read my comments and the conflicting test cases? This isn't about and unwillingness to "fix" continuation but about not "fixing" one behavior while breaking another one.

**Comment by rdococ** [comment]
In that case, why close this issue?
