### ISSUE TITLE
Borrowing?

### ISSUE THREAD

**Issue by MWB6763** [jmoenig/Snap#2991]
I'm writing a program called "Splashy Blocks" and don't know much JavaScript and Morphic. So can I borrow something like this repository code? I'll change it around just a little bit. Still working on this Scratch clone...

**Comment by jguille2** [comment]
Hi @MWB6763 ,

This is open software (see https://github.com/jmoenig/Snap/blob/master/LICENSE) so you can use it, sure! This is the freedom we love...

Only note that this is not a "scratch clone". If you think so... then borrow from Scratch (because better the originals) ... but you'll see it's not.

Joan

**Comment by MWB6763** [comment]
Yes I know you don't use the same code as like&hellip; Scratch 3 does in their editor using <b><i>React.</i></b> I had to ask this <i><b>because</b></i> I didn't the last time I ever used code from someone else. Apparently today, I ran into a copyright infringement problem with Scratch Addons and their website about my Splashy Studio website. So I'll make sure to do that every time I do this from now on.

**Comment by MWB6763** [comment]
By the way, I'm not done! I'll try to remember when I'm ready to make a repository for this which I haven't yet!
