### ISSUE TITLE
Something wonky with dropping a variable into into a reporter ring

### ISSUE THREAD

**Issue by gigamonkey** [jmoenig/Snap#2995]
To reproduce:

Drag this block in:

![image](https://user-images.githubusercontent.com/250053/156280741-40454fdd-5a00-4ad9-97e7-a6c4bec3c819.png)

Then drag a variable into the ring and note that the ring goes away:

![image](https://user-images.githubusercontent.com/250053/156280840-735cf46b-88a0-45c2-8b36-12b720c0b77e.png)

Run the block and get this error:

![image](https://user-images.githubusercontent.com/250053/156281039-1a7941a3-3774-4a58-a41d-dd2eb25d960e.png)

Drag the variable out of the ring and it goes back to this:

![image](https://user-images.githubusercontent.com/250053/156280741-40454fdd-5a00-4ad9-97e7-a6c4bec3c819.png)

Put the variable back in and then right click and select ringify to get this:

![image](https://user-images.githubusercontent.com/250053/156281091-db1656d0-b927-4f5c-a3a6-9533bc999255.png)

Now it works:

![image](https://user-images.githubusercontent.com/250053/156281141-d2351f21-5aa1-4628-8351-35c5c9c3b820.png)

Yet weirdly if I just drag in a ring:

![image](https://user-images.githubusercontent.com/250053/156281187-9633de0a-f696-4483-91c7-02a491c5dc90.png)

And then drop the variable in it works fine:

![image](https://user-images.githubusercontent.com/250053/156281259-8e950c03-7484-4d58-b7cb-afcc72c19cd0.png)

I don't know if this is something about the ask block or any block that has a built in ring but it definitely tripped up first me and then some students I'm working with.

Before I figured out the ringify step, I wrapped the variable in a report block and then dragged that in which worked despite the ring shape not matching the report block shape which may or may not be another issue?

![image](https://user-images.githubusercontent.com/250053/156281593-3cc2e07a-89f5-4f76-86d8-8038f02a5b2c.png)

I don't know if this is a bug or the expected behavior but it definitely was not what _I_ expected.

**Comment by brianharvey** [comment]
This is indeed the expected behavior.  When we designed RUN and CALL, we knew that when people drag a variable into a ringed slot it's because they're writing a higher order function
![untitled script pic](https://user-images.githubusercontent.com/3885074/156284681-8329c7d1-693b-41b5-b471-0f598128f770.png)
![untitled script pic (1)](https://user-images.githubusercontent.com/3885074/156284736-2fdf4ed3-b682-4e9a-820b-3ed4f0227230.png)
and so what they want to call is the function that's the value of the variable, not the variable itself.  And similarly in the recursive call to the HOF.  So we decided that when you drag a variable into a ringed input slot, the ring disappears.  The goal of all this is that newbies can use, and even write, HOFs without really grappling with lambda and anonymous functions.  We figure that people who are advanced enough to actually want the variable itself, rather than its value, to be called are also advanced enough to know about Ringify.

I guess the thing that newbies want from ASK might be different from what they want for CALL.  (It _was_ different, for you!)  This is the trouble with DWIM-style design: you get caught in special cases of the special cases.  It's kind of the same with object inheritance: some properties are shared with the parent, and others are copied from the parent, based on Jens's experience of what users actually want in each case.  I had agitated for sharing _everything,_ and apply a copy-on-write rule, but Jens talked me out of it because of the important case of making a bunch of clones in a loop and wanting each one to have a different serial number.

**Comment by gigamonkey** [comment]
Okay, that makes some sense. So I guess if one is using ASK as a getter for an instance variable you just need to remember to drag the variable in and then right-click and ringify. It does seem (not having thought about it a ton) that might be a more common use case of ask than "apply this function to this sprite and report the result" though I guess I can imagine uses for the later too. Thanks!

**Comment by gigamonkey** [comment]
Ah, great. Hadn't noticed that block yet! Yes, that is much more straightforward.
