### ISSUE TITLE
Bug in "label" option of OF BLOCK

### ISSUE THREAD

**Issue by WarpedWartWars** [jmoenig/Snap#3035]
![untitled script pic - 2022-04-09T233448 614](https://user-images.githubusercontent.com/91039320/162605672-5e8c9574-9199-4526-8cae-96d72d3c28b8.png)

This is because both give `_ of _`. The Lists LENGTH OF would give the same:

![untitled script pic - 2022-04-09T233734 401](https://user-images.githubusercontent.com/91039320/162605715-9fa25396-d328-43f8-9d05-16acb74bec6b.png)
![untitled script pic - 2022-04-09T233738 015](https://user-images.githubusercontent.com/91039320/162605717-3c5c0874-ab4a-45f9-9e28-78a5cb0d1cc5.png)
![untitled script pic - 2022-04-09T233740 886](https://user-images.githubusercontent.com/91039320/162605719-199c949e-7cfd-44e3-8dbc-ccafcfac961e.png)

**Comment by brianharvey** [comment]
This isn't a bug.  It's just a non-feature.  The purpose of LABEL OF BLOCK isn't to make a unique block identifier, but just to give something simple that autograders can use.  Once I get the manual up to date, this will be documented as such.  But thanks for checking.

**Comment by WarpedWartWars** [comment]
Ah. I see. Except for the "autograder" part; what does that mean?

**Comment by brianharvey** [comment]
A program that grades school assignments.  Until recently, autograders worked only for multiple-choice questions, which is why there are so many of those in the world of schooling.  But people would like to be able to autograde computer programs, and if they're Snap<i>!</i> programs, that's helped by turning the blocks into text.
