### ISSUE TITLE
Incorrect value in watcher when replacing item in linked list

### ISSUE THREAD

**Issue by brollb** [jmoenig/Snap#3070]
Sorry for the brief description but see the scripts pic below (and attached project). This bug isn't the case when the blocks are all connected in a single script.
![untitled script pic (3)](https://user-images.githubusercontent.com/4982789/179806183-fd769c6c-0c9c-4e86-b49b-86e2a052263d.png)

[watcher-not-updating.zip](https://github.com/jmoenig/Snap/files/9143129/watcher-not-updating.zip)

**Comment by jmoenig** [comment]
Ah, yes, thank you for this great reproducible case, @brollb. I think @brianharvey and I discussed this very case way back when we first discussed the internally hybrid data structure that we call "list" in Snap, and decided that mixing functional and imperative style, particularly mutating an internally linked list would be something where we could both live with an watcher occasionally getting out of synch. It's important that the actual data is always correct and that we absolutely have sublist-identity, it'd just that the watcher doesn't sometimes keep track of internal modifications.

But ... given your easy-to-reproduce and somehow compelling example makes me want to give it a quick try, maybe the fix is easier than I believed some years ago. Will do so now.

Thanks!

**Comment by jmoenig** [comment]
Hmm.. okay, I've looked into this and I remember why we decided not to catch such changes. When you use `replace` on a linked list it gets converted to an arrayed one. In your example the list named "a" now is a hybrid list which is partially linked and partially arrayed. In order to find out whether parts of it have changed elsewhere (here in list "b") we'd have to iterate over *all* its elements polling for a change indicator every couple of milliseconds, which would make watchers terribly inefficient. Therefore I'm again convinced that it's okay not to try to catch this case.

I'm curious, did this come out of a student project? Or is this for some feature you're building into Netsblox?

**Comment by brollb** [comment]
One of our graduate students, @dragazo, has been working on a native VM to open up another model of integrating NetsBlox with robots. Currently, we support remote robotics via message passing with the robots but this would allow us to support actually running the code on the device (like microblocks, et al).

As a result, he has been digging in all the nuances of the current VM and stumbled upon this :)
