### ISSUE TITLE
A global variable is not accessible from a ring created by join

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3115]
![untitled script pic (61)](https://user-images.githubusercontent.com/2138696/188541129-0fe5eb4d-b12b-4499-8c0c-0cab3dbda946.png)
![untitled script pic (62)](https://user-images.githubusercontent.com/2138696/188541135-e390850b-cd49-4726-8511-e1672757b6fc.png)
![untitled script pic (63)](https://user-images.githubusercontent.com/2138696/188541303-db53d385-9096-49e9-86d5-c3ab3da9f67a.png)

**Comment by ToonTalk** [comment]
Nor are custom reporters accessible

**Comment by jmoenig** [comment]
yep, that's right and by design. JOINing blocks produces just blocks, i.e. structure, in the form of an unbound ring. It needs to be bound to an environment to be able to access the environment. Environments are either sprites or scripts (other rings):

![binding_to_an_environment](https://user-images.githubusercontent.com/2596285/188557664-aec66512-33cc-41cb-9479-5cfc80890b38.png)

**Comment by ToonTalk** [comment]
OK. Though this design is based upon an unusual interpretation of what "global" means.

If you forget the `of` `this script` if the following you get an unreported error (turns red and does nothing)

Using
![untitled script pic (64)](https://user-images.githubusercontent.com/2138696/188768866-57b600a7-6b3e-428c-b481-8e3cbb85ed4a.png)

![untitled script pic (68)](https://user-images.githubusercontent.com/2138696/188769457-2095385c-4d8b-4a4c-9514-654b807fe7af.png)

P.S. My images import as a script but your image just becomes a costume.

**Comment by ToonTalk** [comment]
Also I searched the 8.0 version of the manual for mention of using `join` with `of` `this script` and couldn't find any mention of this.

**Comment by brianharvey** [comment]
The "does nothing" part seems wrong.

It's not our interpretation of "global" that's unusual.  It's that the result of the JOIN block is our equivalent of a lambda expression, i.e., the text of a procedure, but not connected to an environment.  Jens is adamant about this distinction so that the OF <environment> block just adds to the text, rather than having to strip off an existing environment and add another one.

I'm not sure why this does what it does:

![untitled script pic](https://user-images.githubusercontent.com/3885074/188777731-56b3e52d-dd78-4b85-b64a-e43355075e2f.png)

![untitled script pic (1)](https://user-images.githubusercontent.com/3885074/188777877-c03f9dd7-78e9-47d8-bb4c-662b93c1fda8.png)

![untitled script pic (2)](https://user-images.githubusercontent.com/3885074/188777632-327752d8-328f-4658-a96c-f3e68712cff9.png)

I expected the bottom one to report 87.

As to your two manual issues, yes and yes.  I just added a paragraph about this to the source file but it'll take a while for that to propagate onward.  And about pictures, MS Word strips the xml when it reads smart pictures.  Maybe translating the manual to TeXInfo will help.
