### ISSUE TITLE
strange behavior from library block "substring of ... from position ..."

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3120]
![illustrated story generator script pic (7)](https://user-images.githubusercontent.com/2138696/192136883-2de550f8-853f-45b4-bd30-b8745a2076a3.png)

I would have expected the empty string

**Comment by brianharvey** [comment]
Yeah, what you're seeing is Javascript's weird ideas about out-of-range indices.  Maybe we should rationalize it, but if so, we should do it in Snap! altogether, not in this library alone, I think.

**Comment by cymplecy** [comment]
@ToonTalk I rolled my own version that will return empty string if either of the position values lies outside of the length of input
![sliceExample](https://user-images.githubusercontent.com/2357428/192144041-029c5c35-c356-4dc1-878a-35515f2cf485.png)
Also works on lists as well hence the red colouring to indicate dual function

**Comment by ToonTalk** [comment]
And @cymplecy I was able to load the block from the PNG file.  Works fine, thanks.

**Comment by bh** [comment]
> @bh Don't blame JavaScript
> 
> It ends up doing `join `of
> 
> ![illustrated story generator script pic](https://user-images.githubusercontent.com/2138696/192145784-c2633284-7be9-424a-b18e-ce46b804a284.png)

@ToonTalk  ?

**Comment by ToonTalk** [comment]
The 2 comes from the from the second input and the 1 from the length of the first input

**Comment by cycomachead** [comment]
Asking for a substring where start > stop will reverse the string. That's an intended feature of the block, which also happens because it's the same with the `numbers....` block. 


Indices outside of the length of the text map to the empty string, which gets ignored when you join things back into a list.

**Comment by brianharvey** [comment]
Who was that commenting three back?  It wasn't me...

**Comment by ToonTalk** [comment]
Brian - if you hover over 'bh' you see

![image](https://user-images.githubusercontent.com/2138696/192171010-82f10e61-2894-440f-84d8-7daac94b16e3.png)

**Comment by ToonTalk** [comment]
@cycomachead - I think the issue is how to interpret an empty last input. Using the length of the string doesn't make sense when that is less than the second input.

**Comment by ToonTalk** [comment]
Can I point out that JavaScript's [substring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) behaves more sensibly here

> If indexEnd is omitted, substring() extracts characters to the end of the string.

**Comment by cycomachead** [comment]
I get that this is weird but to me “empty input means length of string” is at least consistent. Given that start > stop is a supported / intended feature, I don’t think it necessarily makes sense that this particular case return an empty string. It could be argued that if start > length(string) then we should set stop just to 1, which would make this reverse(). If you omit the stop value and pass in a valid start then this function should be what JS does. -- Michael BallFrom my iPhonemichaelball.coOn Sep 25, 2022, at 4:59 PM, Ken Kahn ***@***.***> wrote:﻿
Can I point out that JavaScript's substring behaves more sensibly here

If indexEnd is omitted, substring() extracts characters to the end of the string.

**Comment by ToonTalk** [comment]
I feel I should also point out that Logo's `ButFirst `works for text and lists. It is like Snap!'s `all but first` but that works only for lists. BUTFIRST 'a is the empty string in Logo, right?

How should one define a text-oriented `ButFirst `in Snap!? 

Note that cymplecy posted a version that seems to work fine.

**Comment by brianharvey** [comment]
Well to answer your most recent comment, there is a "Word/Sentence" library that has all the Logo text functions, working correctly.  It accepts either a string with spaces or a list of words as a sentence.  The former has the advantage of being readable, but the latter has the advantage of being able to apply the higher order functions to it.  I wish we could have both at once, as in Logo, but this is a price we pay for visual representation of lists.  The library functions whose range is sentences return a list, and there's the PRINTABLE function to make the string of words with spaces.

About SUBSTRING and NUMBERS FROM:  When I first wrote the BYOB version of the FOR block, I made it work in either direction in order to have an excuse to show off the ability to put functions in variables and then CALL them.
![untitled script pic](https://user-images.githubusercontent.com/3885074/192182871-5d3aa0c4-a34b-4223-b17d-032f838829ac.png)
Jens really liked that behavior, and when we promoted FOR to a primitive he kept it.  I keep being bitten by that and would rather it just did nothing, but Jens keeps finding projects in which it's useful the way it is.

On my list of lesser features to bug Jens about, I'd like both FOR and NUMBERS FROM to replace the title text word TO with a dropdown {TO, UP TO} so we can both be happy.

The popular convention of using negative indices to count from the end is useful, but in a perfect world an index of 0 or with magnitude > length would give an error message saying that the recursion lacks a base case.
