### ISSUE TITLE
Drawing with white pen over black line leaves residue

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#3134]
Doesn't happen with direction = 90

![untitled script pic](https://user-images.githubusercontent.com/2138696/199418689-754952c8-f3bd-4cb9-b0ab-bbaaa47a8490.png)
![Stage (1)](https://user-images.githubusercontent.com/2138696/199418703-bc796125-ee4e-40b2-82bf-3eceacf28485.png)

**Comment by ToonTalk** [comment]
By the way I'm not sure why the script pic is so large. I was using zoom of 1.6 and just dragged the script pic here.

**Comment by brianharvey** [comment]
The script pic is big because you're on a Retina (4X) display and Snap<i>!</i> doesn't scale down to normal size when exporting pictures (a misfeature).

The underlying problem is caused by the fact that we don't sort the endpoints of a line segment before drawing it, so the antialiasing goes on the wrong side of the line.

**Comment by ToonTalk** [comment]
But the problem persists if I redraw the same line in the same direction.
![untitled script pic (70)](https://user-images.githubusercontent.com/2138696/199629266-76fcce3c-02c9-4668-b5d6-80ee004188ee.png)

**Comment by brianharvey** [comment]
Hmm, okay, I guess I'm wrong.

**Comment by jmoenig** [comment]
Guys - antialiasing is background sensitive. That's how it works.

**Comment by ToonTalk** [comment]
Right.

I fixed my project by increasing the pen size by 1 in white and then restoring by decrementing by 1
