### ISSUE TITLE
Sprite has a costume that it doesn't have...?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3158]
The sprite has a soccer ball costume, which I added, but it doesn't have the costume in the costumes tab. (New project, newly opened window, Chrome Version 108.0.5359.124)

<img width="651" alt="Screen Shot 2023-01-05 at 12 02 07 PM" src="https://user-images.githubusercontent.com/6549787/210838391-3a75b66f-107e-487f-bc49-6abc7268bc27.png">

**Comment by jmoenig** [comment]
Yes, sprites can have a current costume that's not in the wardrobe, e.g. if you directly tell it to switch to a generated costume (which can also be a copied costume of another sprite). Did you add the costume to the wardrobe?

**Comment by maryfries** [comment]
Also, Hi! Happy New Year!! :)

**Comment by jguille2** [comment]
Hi Mary!
And happy new year!!

The "wardrobe" is just the collection of costumes that sprites have in that "costumes" tab.

I can't reproduce your issue. I import different costumes (png, jpg, svg...) and they are appearing inside the wardrobe immediately.

If you continue with this issue, please, send us the project or the original image that is not well-imported to test it. One possibility would be that the image (the original) did not have the "standard" headers right and there was an "interpretation" problem. Sometimes it happens with some images (usually svg) that don't have the sizes well informed in their header.

Joan

**Comment by maryfries** [comment]
Hi Joan! I can't reproduce it either now. I'll set you know if I see it again. Thanks! Best wishes, Mary

**Comment by maryfries** [comment]
Hi! This happened again tonight. Here's a video as proof. ;)

You can see on the stage that I'm adding the costumes, and they do appear after I leave the wardrobe and come back, but they don't reliably appear at first (often they do though).

https://user-images.githubusercontent.com/6549787/211961257-8f359f18-c25d-4821-b9f9-316d783cf827.mov

Here's the XML project included as a TXT file (since XML isn't an allowable extension for this platform).

[Sparks - Interactive Project.txt](https://github.com/jmoenig/Snap/files/10397644/Sparks.-.Interactive.Project.txt)

**Comment by jmoenig** [comment]
Hmm... I can see it in your video and I totally believe you, but no matter how hard I try I can't reproduce it myself...

**Comment by jmoenig** [comment]
Ah, wait! I *think* I *can* reproduce it now. It only happens when the wardrobe needs to scroll. Ah, *that's* probably a hint here. Lemme check....

**Comment by jmoenig** [comment]
nope, now I can't reproduce it anymore. Dang!

**Comment by jguille2** [comment]
Hi!
I have not been able to reproduce it at any time (and I have done many tests).

But if it happened to you... it seems to be a problem with the calculation of the pixels... Then, in some specific size of the wardrobe area, the calculation with JS of the numbers (because of the issue of resolution and the floating point ) do it wrong and "break" some condition.

We should find where it is and add some rounding or change the condition.
Joan

**Comment by jguille2** [comment]
Hi Jens (@jmoenig )!

I see where is the problem! And yes, it's about scrolling... but not when the wardrobe needs scroll. It's a morphic issue, about when the step function of the a ScrollFrameMorph (and yes, the wardrobe is a scrollframemorph) is blocked (turned to "nop") because our system consider we are interacting (autoscrolling or dragging)

Just these two functions:
https://github.com/jmoenig/Snap/blob/master/src/morphic.js#L10704-L10812

I was finally able to reproduce that issue and I can confirm the problem is there because:
- I saw `wardrobe.costumesVersion` and `wardrobe.spriteVersions` were not updated
- Then, i thought `wardrobe.step()` was not running
- But I saw `wardrobe.stepFrame()` was running and `wardrobe.lastTime`was updated
- Then I see `wardrobe.step` had changed to `nop`!!
- So, I found that "temporal_step_blocker" for Scroll Frames was doing the fake.

Now, knowing the origin, I can reproduce the issue (yes, it's the world upside down... but that's how it went :) )
 - Open the wardrobe
 - Open the costumes selector
 - Click on the wardrobe (outside the costumes selector that is focused)
 - Then, the fake is done, and the wardrobe.step function is "nop" and it is not updated.

Then, the problem is on `ScrollFrameMorph.prototype.mouseDownLeft` when we have a popup focused.

**Comment by cycomachead** [comment]
That's amazing Joan! 😀

**Comment by jmoenig** [comment]
awesome, thank you, Joan!

**Comment by jmoenig** [comment]
nope, that didn't fix it....

**Comment by jmoenig** [comment]
... but this apparently did ;)

**Comment by jguille2** [comment]
Hi Jens.

I have no time now to see this (I'm overwhelmed with work) and I'll try to find time later...

But this doesn't work for me. I see the same behaviour that was reported.
I thing the image (image or SVG) uploading process is an asynchronous task and then, your `updateList` (that is the function the `step` have to call) is done before the real addition.

I think we have to fix that "step blocker". We have here two scrollframes. And then, that "step blocker" (when leftmousedown) is more permanent that it have to be.

I see this later...

Joan

**Comment by jguille2** [comment]
Hi Jens!

Sorry... I think I was wrong.
I had no time... and I tested wrongly :(

It is possible to have an async issue (not sure, maybe not) with that loading (I will test later) but I'm wrong. The main behaviour is fixed. And also, a second upload will fix any async problem.

Then, this is rightly closed.

Maybe the inner problem is still there, about more than one scrollframes (is something like our "focusing system") where we are blocking something (those step functions) than have not to be blocked.
But this issue is gone!

Thanks and sorry for my poorly thought out answer...

Joan

**Comment by maryfries** [comment]
I ran into this issue again today with importing sounds. Chrome Version 110.0.5481.177
