### ISSUE TITLE
Can't make script pics of some color library blocks

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3161]
The ones that don't initialize global variables work fine:
![untitled script pic (7)](https://user-images.githubusercontent.com/3885074/212205047-1bf6846d-d00a-4e4a-9d14-13a1c4d55281.png)

The ones that _do_ initialize global variables work when called:
<img width="223" alt="Screen Shot 2023-01-12 at 3 49 38 PM" src="https://user-images.githubusercontent.com/3885074/212207643-8731dbe2-6b70-4ef4-8837-669bbee2f18a.png">
but when I try "script pic" nothing visibly happens at all, and "result pic" freezes Snap<i>!</i>:
<img width="208" alt="Screen Shot 2023-01-12 at 4 15 11 PM" src="https://user-images.githubusercontent.com/3885074/212207942-2de4e9bb-210f-4f6a-af1d-d9feb92c4337.png">

**Comment by jmoenig** [comment]
seems to be a smart-image issue, your library has horrific interdependencies among the blocks that bloat any export to humongous size (basically including the whole gargantuan library into everything that gets exported). Recursively crawling the dependencies exceeds the JS callstack. Sigh. Lemme search for a solution.

**Comment by jmoenig** [comment]
further investigation reveals that the issue seems to stem from the code that embeds data into a PNG. It does some fancy stream-slicing which overwhelms the JS stack when the sheer size of the embeddable data (here: the gargantuan colors library) exceeds some undocumented internal memory limit. I think I'll try to catch this issue and skip embedding the xml when this happens rather than try to "fix" the stream-fidgeting...

**Comment by brianharvey** [comment]
Oh, that's brilliant!  I figured it was a problem with the library, but I couldn't imagine how I could make it fail _without running the code!_

I think that "initialize variables" doesn't depend on any other procedure, and isn't picturable, so that alone must be too big.
