### ISSUE TITLE
Loading old project in 8.1 doesn't show all control blocks

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#3175]
It may just be me or it may be intended and I've just not noticed in the past when new release comes out

When loading a project made in 8.0, the new control blocks are not in the category (and neither are the "scripting" type ones)

old project
![image](https://user-images.githubusercontent.com/2357428/216306644-9638d1d0-d251-42ea-8e8f-31289d55e28d.png)

new project
![image](https://user-images.githubusercontent.com/2357428/216306508-1d95225c-8c63-4d58-ba80-b1e71b6a8cb2.png)

**Comment by cymplecy** [comment]
I rarely hide blocks and I've opened 3 projects (2 of mine and 1 of someone elses posted in forum) and all show same effect

**Comment by cymplecy** [comment]
They are just hidden not missing :)
![image](https://user-images.githubusercontent.com/2357428/216312913-2c804d34-0de8-40af-95f8-5a39e8591ae4.png)

**Comment by jmoenig** [comment]
yes, that's totally intentional, so existing microworlds don't suddenly show the new blocks. The rule here is that if an existing old project has *any* hidden blocks the new ones since that version will be also hidden. Your projects that don't show the new blocks probably use a library that has at least one hidden block, maybe a hidden variable.

**Comment by cymplecy** [comment]
OK but this project has no libs or hidden variables AFAIK/AFAICR
https://snap.berkeley.edu/snap/snap.html#present:Username=cymplecy&ProjectName=broadcast&editMode

**Comment by jmoenig** [comment]
in your project the "position" block is hidden

**Comment by brianharvey** [comment]
Sounds to me like the criterion for hiding new blocks should be tighter, because this will confuse users (and they won't find out about cool new features!).  Ideally we'd be able to distinguish between blocks hidden in a library and blocks hidden explicitly by the author of this project.  Failing that, maybe we need a "microworld" checkbox in Settings?

**Comment by jmoenig** [comment]
yes, this looks like a bug, it's too strict, you're right.

**Comment by jmoenig** [comment]
thanks! Please give my fix a try at: https://snap.berkeley.edu/versions/dev/

**Comment by cymplecy** [comment]
Fine for me now :)
