### ISSUE TITLE
XML Image Appearance Doesn't Match XML

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3260]
![gossip2-definition](https://github.com/jmoenig/Snap/assets/6549787/2b25f9e1-d16c-485d-aea9-a99743ed28bf)

This script pic looks different than the code that's in its XML metadata (note the first input to JOIN).

**Comment by ego-lay-atman-bay** [comment]
I don't get that issue when creating a script pic of the code that was in the image
![untitled script pic (41)](https://github.com/jmoenig/Snap/assets/70973578/3c3449ef-aaf7-45e4-b4d6-e381071ead29)

**Comment by cycomachead** [comment]
Yeah, but the question is how could a script pic be made from Snap! which looks different than the code?

(I mean it's possible using funny business, but that wasn't how this was made)

**Comment by jguille2** [comment]
Here we are crating a pic of a custom block definition.
So my hypothesis is:
- You edit the block and modify the definition, without applying the changes.
- If you create the pic, the image will have the modification (it is just what you have on the screen), but the code inside has not that modification because the block definition has not changed.

**Comment by cycomachead** [comment]
Ahhhh. Thanks Joan!Always great guesses as usual. :)I think editing the block but not applying the result makes sense. I can see how that would have happened. (Hmm. This is a useful unexpected effect but a little confusing.)-- Michael BallFrom my iPhonemichaelball.coOn Oct 12, 2023, at 3:54 PM, Joan Guillén i Pelegay ***@***.***> wrote:﻿
Here we are crating a pic of a custom block definition.
So my hypothesis is:

You edit the block and modify the definition, without applying the changes.
If you create the pic, the image will have the modification (it is just what you have on the screen), but the code inside has not that modification because the block definition has not changed.

**Comment by maryfries** [comment]
Thank you Joan!! :)
