### ISSUE TITLE
Set flag block error: 

### ISSUE THREAD

**Issue by sudo-000** [jmoenig/Snap#3281]
![image](https://github.com/jmoenig/Snap/assets/107282563/63d6b9ca-0b57-40dd-95bc-2c1712c80cad)
![image](https://github.com/jmoenig/Snap/assets/107282563/1c6ee1ad-7eb7-439c-a646-a34c4ed95223)

I guess this is probably an option that exist earlier but deprecated in later versions. 
But it's still kept in the set flag block. 
Which could possibly be the cause of this error. 

BTW could you please make a powerful set flag library without using java script? 
It's annoying to need to turn on java script every time I load my project just for a single set flag block. 
All my other code works without java script but this set flag block.

**Comment by sudo-000** [comment]
PLZ update it to support the latest version ASAP!

**Comment by jmoenig** [comment]
This library is largely obsolete, because all relevant settings have now been or will soon be implemented as metaprogramming features.

**Comment by brianharvey** [comment]
Jens, since the beginning of time we've disagreed about your use of the word "relevant" here.  It means relevant to _you,_ not relevant to users.  _Every_ setting is or should be accessible through the library.  Yes, every.

**Comment by brianharvey** [comment]
Yeah, I didn't agree with him about that part. But I think you must be wrong about smooth animations _never_ being a user setting, because I remember we had to explain it to users all the time, back on the Scratch forum.

I think you are arguing circularly when you talk about my "knee-jerk reaction."  _Because_ you disagree with Eisenberg's Law, you imagine that I'm siding with (individual) users rather than siding with Mike Eisenberg, which is what I'm doing, as a principled position.

**Comment by sudo-000** [comment]
Why you closed it? 
Really you've done it? 
I haven't seen any commits saying update the set flag lib?
