### ISSUE TITLE
Snap not asking to save?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3386]
PD observation: It seems like Snap no longer stops you from closing a window with unsaved work (this was in 10.0.0; I can't replicate today in 10.0.2). I saw the warning/question pop up briefly, but then the window closed anyway. (Sorry I don't have more details; I was taking notes quickly while running a training.)

**Comment by jmoenig** [comment]
That's only partially right, Mary. As of v10 Snap! *only* stops you from closing a tab *with* unsaved work. If you've saved the current state of the project, i.e. if there are no unsaved changes, Snap! just lets you close the tab without popping up an alert. This was a contribution from a very skilled programmer from the FOSS community who correctly pointed out that *always* popping up an alert really confuses users, because it constantly makes them - wrongly! - believe, that they didn't save their work, even if they already did so.
