### ISSUE TITLE
Unused blocks broken?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#3388]
PD observation: We were demoing the unused blocks feature, and it didn't work correctly (v.10.0.0 at the time). We have this one on video [here](https://berkeley.zoom.us/rec/play/LvOeCw1h7GdhQIjCiQT5VQ0hV3Nk5D72mqlJFgooI_Nh1hMWmq14wnAgICzf0nzf84V22Q2F-4GMBdGx.Tl5aPS3vwssrOp5k?canPlayFromShare=true&from=share_recording_detail&startTime=1721931959000&componentName=rec-play&originRequestUrl=https%3A%2F%2Fberkeley.zoom.us%2Frec%2Fshare%2FjshzBL8lhWepgXcIll383i4T3IklQnbmSONOFdK-WzBA7_wthFkaaSj7J4N0yt6e.Ar-TstP-0kIZdtwU%3FstartTime%3D1721931959000) (Passcode: m!p+E*1s) around 1:03:00.

**Comment by jmoenig** [comment]
Thanks for the video, I've found the recording of your session. So, actually the unused blocks feature *did* work perfectly fine in your example, but the one block which you've decided to keep ended up relying on so many others blocks, that you didn't see a dramatic effect of removing many unused blocks. This is especially a problem with esoteric libraries such as colors and crayons, which really are less of a tool and more of a political manifesto about brown :D

**Comment by maryfries** [comment]
Haha! I suspect I know whose manifesto it is: the person who taught me that brown is actually dark orange! ;)

**Comment by brianharvey** [comment]
Hey, no fair.  Colors and Crayons would have almost all of the same complexity without brown in the Fair Hue scale -- which might come to pass in a later revision because Jadga is so strongly opposed.  It's not my fault that human color perception is so weird, or (for example) that you can't tell how a paint will combine with another paint just by looking at its color; you have to look at its chemistry (or just experiment).  The interconnectedness of large libraries is just part of their largeness; I bet SciSnap has the same behavior.

Do you really think that Colors and Crayons isn't useful?  Just like SciSnap, you don't use all of it in any one project, but sometimes your project _is_ about mixing paints or whatever.

**Comment by jmoenig** [comment]
naw, colors and crayons are, in fact nice! But, like all really well designed libraries there are strong dependencies among the blocks, which is actually a sign of a good design - reusing modules!. However, as a result it's hard to cherry-pick only a single block without getting many of the others, too. And this has been what Mary tried to demo.
