### ISSUE TITLE
encode/parse has a slight issue

### ISSUE THREAD

**Issue by cymplecy** [jmoenig/Snap#3394]
I noticed this issue when playing around with my large timestamp reporter but I can come up with this simple reporter to show the issue
![untitled script pic (40)](https://github.com/user-attachments/assets/3733daa1-1e06-4f1a-9c65-9e9472886e7b)
![image](https://github.com/user-attachments/assets/cc5ee8bc-a64f-473e-afa6-726b1e1e4ac0)

when encoded and then parsed gives
![untitled script pic (41)](https://github.com/user-attachments/assets/1ea320b0-bc22-4510-a349-fb7a8e18cf2d)

This only seems to happen if the first block in the script is a script var declaration
If another block is inserted before the script var block then it encodes/decodes fine
![image](https://github.com/user-attachments/assets/8f24f9ea-73b4-4899-9eb5-0c3375993581)
![untitled script pic (43)](https://github.com/user-attachments/assets/5cc7000e-310e-48f0-a4ee-1d5ddd68dbf9)

**Comment by jmoenig** [comment]
yep, if the first expression's last input is variadic the ring argument gets appended to the variadic input list. This is - only - an issue when encoding as text, not when splitting into a syntax tree, because the latter preserves the number of sub-slots, whereas the LISP text-format cannot do that. Therefore, for the LISP encoding to handle such an edge case you'd need to quote the function/ring, i.e. also ringify it before encoding it.
I'm afraid this is an as of now unsolvable issue...

**Comment by jmoenig** [comment]
hmm... somehow I don't like my previous answer, this bug "bugs" me. Lemme try to fix it...

**Comment by jmoenig** [comment]
I've fixed this - I hope! - in the v10.1 dev version, which you can play with at the usual known location: https://snap.berkeley.edu/versions/dev please let me know if you come across any other issues. Thank you!

**Comment by cymplecy** [comment]
Done a few tests - seems to work fine - even with my enormous datetime reporter :)

**Comment by jmoenig** [comment]
thanks for the quick tests and confirmation, Simon!
