### ISSUE TITLE
Can you add Dog, Kilo, Hectro, Omigto Yocto, Zepto, Atto, Femto, Milli, Centi, Deci, Deka, Hecto, Bronto, Yotta, Zetta, Exa and Omega to Snap! costumes?

### ISSUE THREAD

**Issue by TheMapotakes** [jmoenig/Snap#3399]
Hello Jens @jmoenig, please add Dog, Kilo, Hectro, Omigto Yocto, Zepto, Atto, Femto, Milli, Centi, Deci, Deka, Hecto, Bronto, Yotta, Zetta, Exa and Omega to Snap! costumes. If not, I will tell MJM3, Turtle_Takeover, Prof_Red and, others.
Here is the image to add characters from costumes:

![costume4](https://github.com/user-attachments/assets/2ff29f72-e605-437c-b090-926cd1b89152)

**Comment by TheMapotakes** [comment]
Expect Pico, Nano, Tera, Giga, an ripoff to Scratch,

**Comment by TheMapotakes** [comment]
Here is an image like Scratch Cat's brother.
![costume1](https://github.com/user-attachments/assets/ffee5d2e-631a-4238-81a5-58f6ae31e075)

**Comment by ego-lay-atman-bay** [comment]
Since Pico, Nano, Tera, Giga, and the Scratch Cat are mascots of Scratch, Snap would need permission from the Scratch Team in order to use modified versions of them. The only reason they're able to use a modified version of Gobo as their mascot, is because they got permission from the Scratch Team. You could use those modifications in your projects, but I don't think Snap is allowed to distribute them in the costumes dialog.

**Comment by TheMapotakes** [comment]
Oh, I will be an contributor!

**Comment by TheMapotakes** [comment]
Can I be a contributor?

**Comment by TheMapotakes** [comment]
oh
