### ISSUE TITLE
Some libraries don't import

### ISSUE THREAD

**Issue by xota** [jmoenig/Snap#3408]
when trying to import "Text to Speech" I got a "Unable to retrieve libraries/speech_module.xml"

checked some other libraries, and the following have the same issue
strings.xml
textformat_module.xml
SciSnap3Blocks.xml

I'm using Arc browser on Mac OSX 14.6.1
![image](https://github.com/user-attachments/assets/468a3a32-9d92-43c9-8771-21c178dc35fb)

**Comment by jmoenig** [comment]
Hi Joek, I cannot reproduce this, all libraries load fine on my Mac. But there was an issue with one of Eckart's library files when the current Chrome(-ium) version 129 came out a few weeks ago which forced me to disable asset caching until I found out what was causing it. I've since turned caching on again in v10.1, but maybe some browsers are now "confused" about which resources are available through which protocol. Could you perhaps retry loading those libraries in an "anonymous" tab, or try flushing your browser's cached files? If that doesn't work please let me know, and I'll investigate further. Thanks, and sorry for the hasse!

**Comment by xota** [comment]
Thank you! Emptying cache solved my problem.
