### ISSUE TITLE
Autosaving

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#411]
(I'm going through some student feedback for CS10, so there will probably a few non-urgent, nice-to-have requests).

It would be cool if Snap! could autosave a project. Every 5-10mins it could just update the wherever the project is stored. However, right now, the loading time of saving a project might be a bit of a jarring experience.

**Comment by davelai** [comment]
Nice discussion! I know this thread hasn't been active since Jul 2014, but...

To simplify things, couldn't user-interaction with auto-save only be triggered with certain events? (computer froze? power got cut? internet died?). An idea to simplify things:

(1) When closing a project, a pop-up window asks the user to save if any changes have been made since last saving. The user can save or close without saving. In this case, regardless of their selection (as long as they make one), any auto-saved version is purged.
(2) If that dialog box doesn't receive a user response, then this signals the likelihood of one of those most helpful auto-saving cases, and the auto-save interface kicks in next time the project is opened. Auto-save interface: When this project is opened (auto-saved version is different from the saved version), the user is prompted with those 3 choices a la @brianharvey.

In the practical K12 classroom side of things, students make savings mistakes all the time. The biggest annoyance I've seen is when they couldn't control the event (power went out, etc).

**Comment by wcyuan** [comment]
I often have students who lose work because they forgot to save.  I would be in favor of anything that helps them remember.  I think almost any idea that has been mentioned here would help, so I don't have a strong opinion about the design, I just want to cast a vote in favor of doing something.  

Thanks!

**Comment by timdoodle** [comment]
I am currently teaching CS in middle school. Without an automatic save feature I don't think that I can use Snap! in the classroom. These students are used to the way Google docs and Scratch automatically save their work.

If, at the end of a class period, when they are in a hurry to get to their next class, they might lose their work without an autosave feature. Then, because they have other classes all day, they cannot try to recreate what they had done until hours later. By then they will have forgotten almost everything they did.

I'm surprised there has been no action on this item...marked **important**...in almost two years.
