### ISSUE TITLE
Interactive Debugger (BYOB's `debug` block)

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap#453]
Upon opening BYOB again, I was reminded of how useful it is to sometimes have a single stepping mechanism, like the old `debug` blocks. It'd be nice to have something similar in _Snap!_. I know the discussion has come up a bit before, but I think it would be a useful tool to have. (I'm not set on any interface, but the ability to step through code is a nice skill to practice!)

**Comment by harid001** [comment]
Would this feature just be a block that paused execution and allowed users to step through to the next block? Or were you thinking of a full fledged debugger (step into button, ability to see error messages, etc..)?

**Comment by cycomachead** [comment]
I haven't put much thought into this, but my view for a first pass feature would be very similar to BYOB, a/k/a Snap! 3.

That is there's a block called `debug` which when run will open a window that is a semi-featured debugger. There was control of execuition (next step, step into / step over) and it allowed you to inspect variables. We didn't really have "error" messages in the same ways in BYOB, but that would be something that should be easy to see, I'd hope.

I would personally like to see some way of showing data types, since those can be even more helpful for students . (Is this thing _actually_ a number?, etc)

**Comment by jmoenig** [comment]
we now have visible stepping. I'm closing this. Thanks!

**Comment by cycomachead** [comment]
Visual stepping doesn't really address this though. That shows you where you are, but I don't think you have the range of flexibility. 

Also the part about it being a block was useful. I think we might be able to build that though with a JS function.

**Comment by bromagosa** [comment]
I agree with @cycomachead that a stepping debugger is not the same as visual stepping. For many cases, visual stepping works, but in complex programs you may not even know where the bug is and so you may not know where to look at while the program steps. A stepping debugger takes you along with the execution so you can track exactly what the interpreter is doing at each step. And, ideally, you can modify the program live, just like in Squeak :)

However, I don't think we need an issue to remember that it'd be awesome to eventually have a stepping debugger.

Ah, if we actually had the time to work on the fun stuff... :cry:
