### ISSUE TITLE
touching (sprite) block regression

### ISSUE THREAD

**Issue by inthemedium** [jmoenig/Snap#472]
One of our students noticed recently that the `touching (sprite)` block reports _true_ when one sprite is touching another and hidden using the `hide` block. We'd expect it to report _false_ in these conditions.

Example:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=tealsintro&ProjectName=hide%2Fshow%20touching%20regression

**Comment by stooj** [comment]
We hit this issue during a class, and our teaching material often uses `hide` as a means of preventing sprites from activating any collision detection.

From a teaching point of view, I find it far easier to use `touching` to detect collisions with visible sprites only, and `hide` sprites that we don't want to deal with at the moment than it is to explain the difference between ghost and hidden (still not sure of the difference myself :D )

**Comment by brianharvey** [comment]
I think I was the only one holding out for asymmetrical touching, and even though I still think I'm right on the merits, and even though using ghost doesn't really serve because then touching is still symmetrical, in the spirit of picking my battles I'm willing to go along with Scratch compatibility.

And I think Jens is okay with that also, so I'm removing Misfeature and Discussion and adding Bug.

**Comment by jmoenig** [comment]
this is now fixed in the way @brianharvey has laid out above. Thanks, everybody! Closing...
