### ISSUE TITLE
Suggestion: know the current position of a sprite

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap#685]
It would be good if coordinates X and Y of the sprites appear somewhere.

**Comment by jmoenig** [comment]
you can select the check box for the x and y position of each sprite to display them in stage watchers

**Comment by geaplanet** [comment]
Yes, but if you have several sprites it is dificult to work with.

**Comment by deader69** [comment]
1) There's an 'xygrid.gif' in the File > Backgrounds menu, which is somewhat useful.
2) As mentioned above. you can watch the x,y of any sprite (though the floating point display is bit difficult)
3) You can also watch the 'mouse x' and 'mouse y' variable under "Sensing"... these display simple integer values, a bit easier to read.
4) There's an art to programming without numbers, using hidden sprites who's only purpose is define locations on the Stage. So you just use a 'goto [foo]' Motion block, instead of 'goto x y' block.

I know none of these are 'fixes', but there's something educational about learning tricks within a given set of limitations. I explicitly teach these techniques to kids :-)

**Comment by geaplanet** [comment]
I think you forget that each sprite has a specific point where your frame of reference is taken (it is not always the tip of a triangle). You can use all the tricks you want, or add a grid to guide you, but at the moment of truth, if you want a sprite to a specific position you have to take it there and see its exact coordinates. You can use the xy position check box, but if you have many sprites is becoming annoying fill the stage with a lot of labels.
It would be great if, for example, up in the middle (where you can find some properties of a sprite like the name, draggable, orientation...) appears current x and y values.

**Comment by deader69** [comment]
I agree completely... the Snap team just has to walk that line between adding useful features, versus keeping it simple simple SIMPLE!

I wish I could get the x,y,w,h of any sprite, and especially the Stage!

We've written an in-house library to get this info via the 'javascript' operator... but I don't like creating projects dependent on external libraries... partly to avoid confusion, partly because libraries actually take a bit too long to load for my tastes!

**Comment by introlinux** [comment]
I think @geaplanet was talking about this:
[x_y_direction_info_in_BYOB](https://s3.postimg.org/tptme6pn7/image.png)

I miss it too.

**Comment by introlinux** [comment]
And this info was useful too:
![mouse_x_y_info_in_BYOB](https://s3.postimg.org/rreccnx1v/mousexy.png)

**Comment by liam4** [comment]
FWIW this feature wasn't abandoned in Scratch 2.0, either:

![Demo](https://cloud.githubusercontent.com/assets/9948030/17798496/f447e8b8-65a7-11e6-80a0-9c4d51480dfa.png)

**Comment by brianharvey** [comment]
I admit, I like those things in Scratch too.  I work around them by checking the position checkboxes just for the one sprite I'm working with right now, then unchecking them after noting the position.

But for the application I think you have in mind, although you do need the exact position, you don't have to *see* it.  You can do this:
![dropped](https://cloud.githubusercontent.com/assets/3885074/18031645/c9740690-6c9f-11e6-807f-005efbbbb550.png)
but with a more descriptive name than "position," and then later you can GO TO the saved position.  (One of my standard tools for myself is a GO TO block that takes a list of two numbers as input.)
