### ISSUE TITLE
Feature request : add dynamic multiple choice input in custom blocks

### ISSUE THREAD

**Issue by show0k** [jmoenig/Snap#778]
Some built-in block like <set #variable to #variable> have a multiple choice input. It is very convenient for user when the choice is limited. 
Is there a way to put a reporter block or a list variable as a predefined value to make multiple choice input ? 
If no, is it planned for further versions ?

**Comment by brianharvey** [comment]
Yes, open the long input dialog (the one that lets you set the type of an input) and right-click on the dark background of the type array.

**Comment by show0k** [comment]
OK, thanks. But I think my problem is still unsolved.
On the SnapManual p30 I can read "For now, at least, you can have only fixed options, not, for example, all sprites,” let alone “all sprites that are on the left half of the stage right now.”
So, I cannot put  the list returned by a reporter block as a multiple choice, neither a list variable which is accessible in the project ? Putting only hard-coded choices is very limiting.
I should perhaps rename it in a "Feature request" ?

**Comment by cycomachead** [comment]
Currently dropdowns only support hard coded values -- I think a feature that allows a set of built in values (like the current ones that exist) would be cool.

**Comment by brianharvey** [comment]
Yeah, the obvious thing is to provide a Snap! reporter that reports a list of values for the pulldown, but Jens doesn't like that because he doesn't want to have to run the reporter every time the user clicks the arrowhead.  Maybe I can negotiate a compromise in which we call the reporter when the block is defined, rather than when it's used.  And separately have a truly dynamic option for predefined categories such as sprites.  But neither of those will get you the sprites on the left side of the stage "right now"; is that a serious request?  "Now" would still have to mean when the user puts the block in a script and pulls down the pulldown, not when the enclosing script actually runs.  I'm not sure that's useful.

**Comment by show0k** [comment]
>Jens doesn't like that because he doesn't want to have to run the reporter every time the user clicks the arrowhead. 

I understand, it would be a bad idea to do that.
> "Now" would still have to mean when the user puts the block in a script and pulls down the pulldown, not when the enclosing script actually runs.

We doesn't need more. Execute the reporter when the user pulls down the pulldown is enough for most of use case I see.

**Comment by cycomachead** [comment]
> And separately have a truly dynamic option for predefined categories such as sprites.

Yeah, what if we started with the built-in options defined for all primitives? Like `%sprites` or `%date`, that would likely cover many cases.

"All" we'd need to do is modify the input selection dialog to have a dropdown of the built-in options, but with human readable names, which isn't too hard to create a mapping in blocks.js, especially since most of that exists as a code comment.

**Comment by jmoenig** [comment]
Actually, the Process constructor already has all the necessary hooks for using it on Snap itself. I'm thinking of maybe simply experimenting with a version of allowing totally dynamic drop-downs (in addition to the current static ones) by alternatively specifying reporter that gets called whenever the user invokes the drop down.

The issue really is whether we are prepared to deal with issues that might arise when there is a bug in that reporter. How are we going to let the user know that (and where) an error occurs? How are we letting them stop reporters that keep gong on forever? What if such a reporter ```launch``` -es other processes, clones sprites, or has any other unexpected side effects? Are we ready to let teachers deal with such situations? I can see how it would be fun, though...

**Comment by cycomachead** [comment]
> The issue really is whether we are prepared to deal with issues that might arise when there is a bug in that reporter. How are we going to let the user know that (and where) an error occurs?

If the reporter is run when the dropdown is clicked, I like the idea of putting a spinner in an empty dropdown until the process is complete. Errors I, I feel like, could either bubble up to the block on the stage (red-ring the current script) or be a pop-up type warning, since these errors should only occur during development, right? Once a dropdown item is selected, there's no need to re-run the process until a change is going to be made.

**Comment by show0k** [comment]
Hi, 
Any advances on that point ? With some user experiences, I think this is a big missing feature for our project. 
We should maybe make a fork for integrating that feature but it's a pity to become incompatible to the "official" Snap!.

**Comment by jmoenig** [comment]
Hi Théo, we should maybe discuss this in private... I do have two experiments that I'm contemplating, but I don't feel they're ready for general consumption yet...

**Comment by bromagosa** [comment]
There's further discussion of this issue in #2565, so I'm closing this one (even though it's older)
