### ISSUE TITLE
Issue with Firefox not executing command properly

### ISSUE THREAD

**Issue by sharived** [jmoenig/Snap#801]
In my project http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=robosnap&ProjectName=basic
I have 2 custom blocks that I call one after another
![bug](https://cloud.githubusercontent.com/assets/1163591/7599763/c098caf2-f8b9-11e4-92ec-e4bf7e827d46.png)

When using firefox the show last picture doesn't show the picture.  I can see from my code that it is executed though.  I've tried putting in a delay between the blocks (up to 20 sec), but didn't help.

If I call it separately it works fine.   Any idea on what might be causing this or a workaround?  Or should I just tell my users not to use firefox.

**Comment by jmoenig** [comment]
I'm investigating into this right now...

**Comment by jmoenig** [comment]
I'm sorry, I cannot reproduce this, since I don't have the hardware (I guess). When I use the online test image (commented out in your code) instead of the actual last one this seems to work in my Firefox, but, of course, I cannot runt the "take a picture" block, so the test isn't of much use.

I want to support Firefox, and sadly recent Firefox version have - once again! - introduced a number of issues. I really hate browsers, because in every new version they'll break something that used to perfectly work before :-)

Can you maybe come up with another test case that I can reproduce which doesn't involve access to your hardware? That would be fantastic!

**Comment by sharived** [comment]
Not surprising.  I've just launched my kickstarter https://www.kickstarter.com/projects/robosnap/robosnap-vision-for-your-robot so you can order one!  

I'll work on coming up with another example as things settle down.  I want firefox to work as well.

**Comment by sharived** [comment]
Just tried Safari for the first time and have the same issue.  I had always used chrome which works fine.  Will still plan on finding a easier example.

**Comment by jmoenig** [comment]
Okay, I've just backed your Kickstarter, this is exciting!

**Comment by sharived** [comment]
Thanks @jmoenig!
