### ISSUE TITLE
How to mouse touching color?

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap#874]
Hi, how to do something if the mouse is touching a color?

I tried with a red pixel and doing "forever go to mouse-pointer", then in the other sprite (blue) I tried to do something if color blue is touching color red, but it doesn't work.  It seems that my pixel is not always present, I can see sometimes in the screen but not always.

Really the problem I want to solve is how to rotate a sprite when I press the mouse in their corners. That is, the sprite sould be point towards mouse-pointer when I press its corners (blue corners, in my case).

**Comment by cycomachead** [comment]
> Really the problem I want to solve is how to rotate a sprite when I press the mouse in their corners. That is, the sprite sould be point towards mouse-pointer when I press its corners (blue corners, in my case).

Rather than doing color detection, you could also check for the screen coordinates, though you would need to know the size of the sprite's current costume to detect the corners. You could use the logic from a `when I am clicked` hat block.

**Comment by geaplanet** [comment]
But it would be very dificult because that would mean I'd have to have absolute control over all the figures all the time (sizes, positions, angle, form...). What I want to do is a simple tangram for 5-7 years old kids where I show a simple model and you have to try to clone it with the basic geometric figures. They should be able to move the sprites freely on the screen.

**Comment by bromagosa** [comment]
Or just nest four little sprites in the corners of your big sprite, then use { when I am [ clicked v] } hat blocks in all of them :)

Example here: http://snap.berkeley.edu/snapsource/snap.html#present:Username=bromagosa&ProjectName=nesting%20example

**Comment by jmoenig** [comment]
Thanks, Bernat! Excellent example, I love it!

**Comment by cycomachead** [comment]
> Or just nest four little sprites in the corners of your big sprite, then use { when I am [ clicked v] } hat blocks in all of them :)

This was going to be my next suggestion!

Cool project too!

**Comment by bromagosa** [comment]
Although wait a second, @geaplanet's first suggestion does work too!

http://snap.berkeley.edu/snapsource/snap.html#present:Username=bromagosa&ProjectName=color%20dectection%20example

**Comment by jmoenig** [comment]
right. Color detection has several issue, though, the most severe being that it's *accurate* and therefore doesn't play well with anti-aliasing which is often a side-effect of scaling. That's why reducing color-sensing to very tiny, barely visible pixel-like costumes is likely to be unreliable.

**Comment by jmoenig** [comment]
... btw that's one reason why Scratch 1.4 didn't anti-alias anything. They changed that in Scratch 2.0, and they also worked around some of the color touching issues by experimenting with color thresholds. But, you know, that's when it starts to loose its appeal...

**Comment by bromagosa** [comment]
Indeed, I'm aware of how costly color detection is. This is related to #846, for which I still haven't found an alternative solution. Maybe we could cache each sprite's color masks so they don't have to be calculated all the time?

**Comment by jmoenig** [comment]
Yeah, caching is always a good idea if you know somebody is probably going to ask the same question again :-) But caching is sooo problematic because you really need to make sure to flush the cache in all the right situations (and not forget any). Also, it can totally wreck your memory, and - worst of all - it makes response times unpredictable. In your example the *first* time would be slow, the *next* time(s) would be fast, but only *if* the sprite did not redraw in the meantime (and flush its cache).

Often you can instead implement a more sensible approach in Snap itself. For example only test for color collision *after* you've tested for sprite collision...

**Comment by bromagosa** [comment]
That's a nice approach! However, I can't test for sprite collision because I'm dealing with clones of the same sprite. But I'll keep this idea, maybe I can turn it around! :)

**Comment by jmoenig** [comment]
Oh sure, we need to refine collision detection for clones, and for breeds of clones!

**Comment by geaplanet** [comment]
@bromagosa, I don't understand how do you did your blue arrow "detector" sprite without any sprite O_o? I used a one pixel sprite, and if I use it again in your project, I don't get it to work.

**Comment by geaplanet** [comment]
And another question about nested sprited, is there any way to keep "glued" differents parts when you use nested sprites (even if you use the mouse to move it)? Something like "group" option in vector graphics editors.

**Comment by jmoenig** [comment]
@geaplanet yes, absolutely coming (I'm working on this *right now* and it's already done in my dev version). This will be in the next release sometime next week.

**Comment by geaplanet** [comment]
@jmoenig Super!

**Comment by jmoenig** [comment]
here's a sneak preview of the upcoming release:

http://snap.berkeley.edu/snapsource/dev/snap_402.html#cloud:Username=jens&ProjectName=Ferris%20wheel

Note that you can move a nested sprite by dragging any of its parts. It's also useful to know that double-clicking on a sprite activates its scripting pane (because you want to activate the root anchor if you're changing the direction or size of the whole), and that you can adjust the position of individual parts via the "move" option in the part's context menu.

(there's also a bunch of other stuff in there, but that's for another time...)

**Comment by geaplanet** [comment]
Really cool. Do you think Snap! could become a good platform to make physics simulations (http://phet.colorado.edu/en/simulations/category/physics) in the future?

**Comment by jmoenig** [comment]
Whoa, nice link, thanks! Dunno whether Snap will be a good platform to deploy simulations, but I certainly want Snap to be a great tool to explore *authoring* (and tinkering with) them!

**Comment by bromagosa** [comment]
(trying to unclutter gh issues a little bit)

Closing this as the forum is a much more appropriate space for Q&A :)
