### ISSUE TITLE
Color the cloud icon to indicate status

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#914]
Green: logged in
White (like now): not logged in
Red: cloud unavailable

**Comment by cycomachead** [comment]
Easy enough, except for Red? What does "unavailable" mean?
Such as: we have planned downtime or something can't currently be connected?

**Comment by brianharvey** [comment]
I was thinking it'd turn red when a connection attempt failed.

**Comment by jmoenig** [comment]
if you click on the cloud button you'll currently see whether you're logged in or not. I don't want to chsnge anything about this urgently

Von meinem iPhone gesendet

**Comment by brianharvey** [comment]
It's not urgent, just a feature request.  The part about the red cloud I added.  The teacher wants the green cloud so that as he's walking around the room he can see at a glance if someone isn't logged in.

**Comment by jmoenig** [comment]
I'm not convinced about this feature. Basically I'm *very* reluctant to burden the main window with any additional information, colors, symbols etc. Ultimately adding little lights, color indicators and switches only adds to confusion and "Office-ization" of the UI and makes Snap harder for everybody to use.

Already you can find out whether you're logged in by clicking the cloud button: If you're logged in the menu will offer to let you log out, including your user-id.

**Comment by brianharvey** [comment]
The original suggestion was from a teacher who wants to be able to walk around the room looking over shoulders and see at a glance who isn't logged in.  The thing about the green cloud is that it lets the teacher do that non-intrusively.

**Comment by jmoenig** [comment]
I understand. But I'm still not convinced ... :-)

**Comment by khotchkiss13** [comment]
Wouldn't some kind of visual representation of whether or not they are logged in be nice though? What if a user opens Snap!, starts working on a new project, and then wants to save to the cloud using the keyboard shortcut? If they are not already logged in, when they go to save to the cloud, they will be told they are not logged in, which means that they would have to cancel the save, log in, and then save it. If we have the color indicator, they would know before their initial save that they need to log in first, and that saves them the steps of figuring that out.

**Comment by khotchkiss13** [comment]
Any more discussion on this? I still think it would be a good idea, and I would like to here some other opinions. :)

**Comment by jathak** [comment]
What about having this as a feature that's disabled by default? Would that work?

**Comment by khotchkiss13** [comment]
I like the idea of making it an optional feature. This would allow for users to pick whether or not they want the visual indication, while keeping things simple for those who don't

**Comment by cycomachead** [comment]
I don't have much opinion about whether the green icon is a bad, idea..I don't mind it.

However, an optional feature completely defeats the purpose of the indication. A colored icon would be useful to me because I could tell whether I'm logged in -- but if it's off by default, that means I'd need to remember on every browser to change the setting. (By my count that is at least 8 instances of browses where I regularly use Snap<i>!</i>.) Aside from my (somewhat) esoteric testing habits, an optional flag doesn't solve the original problem here -- which is for teachers / others to make sure someone is signed in. Basically, it means that whenever a user sees a white cloud, they still don't know why they're logged in -- it could be two reasons: either a configuration issue, or a not being signed in.

In terms of Jens' concerns, a setting has almost the same burden as a colored icon, and the settings menu itself is already too crazy IMO. :cry: 

In terms of #946 - that works in 95% of cases, but doesn't really determine whether a user is connected to the cloud - to properly do that, we'd basically need to do a `ping` to the cloud when Snap<i>!</i> loads, which would be a lot of complexity. (though honestly, the basic check is probably good enough.)

**Comment by bromagosa** [comment]
This was finally implemented by Jens in Snap! 6 :)
